//Generated By SceModuleGenerator
#include "pset_libSceWebBrowserDialog.h"


int PSET_SYSV_ABI Pset_sceWebBrowserDialogClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogGetEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogGetEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogGetStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogGetStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogNavigate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogNavigate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogOpenForPredeterminedContent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogOpenForPredeterminedContent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogResetCookie(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogResetCookie");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogSetCookie(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogSetCookie");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogSetZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogSetZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogTerminate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogTerminate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceWebBrowserDialogUpdateStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceWebBrowserDialogUpdateStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncF2BE042771625F8C(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncF2BE042771625F8C");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceWebBrowserDialog_libSceWebBrowserDialog[] =
{
 { 0x3D22BE12293DD7D4, (void*)Pset_sceWebBrowserDialogClose },
 { 0x5A2B782E37A8797E, (void*)Pset_sceWebBrowserDialogGetEvent },
 { 0xBC2696D1F8154267, (void*)Pset_sceWebBrowserDialogGetResult },
 { 0x0854C6E9AF138CE5, (void*)Pset_sceWebBrowserDialogGetStatus },
 { 0x8EA6FB1E7B454057, (void*)Pset_sceWebBrowserDialogInitialize },
 { 0xB9810B38C56798D4, (void*)Pset_sceWebBrowserDialogNavigate },
 { 0x16B68FEDD79B71D8, (void*)Pset_sceWebBrowserDialogOpen },
 { 0x3BB748650AF05456, (void*)Pset_sceWebBrowserDialogOpenForPredeterminedContent },
 { 0x0B26BE8EF4ED3EA8, (void*)Pset_sceWebBrowserDialogResetCookie },
 { 0x4D99C35643FDD518, (void*)Pset_sceWebBrowserDialogSetCookie },
 { 0x44B84A04EA0DC976, (void*)Pset_sceWebBrowserDialogSetZoom },
 { 0xA1C1EDC81C077F2B, (void*)Pset_sceWebBrowserDialogTerminate },
 { 0x875751FEDE484A08, (void*)Pset_sceWebBrowserDialogUpdateStatus },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceWebBrowserDialogLimited_libSceWebBrowserDialog[] =
{
 { 0xF2BE042771625F8C, (void*)NullNameFuncF2BE042771625F8C },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceWebBrowserDialog[] =
{
 {"libSceWebBrowserDialog", gSymTable_libSceWebBrowserDialog_libSceWebBrowserDialog },
 {"libSceWebBrowserDialogLimited", gSymTable_libSceWebBrowserDialogLimited_libSceWebBrowserDialog },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceWebBrowserDialog("libSceWebBrowserDialog", gLibTable_libSceWebBrowserDialog);