//Generated By SceModuleGenerator
#include "pset_libSceNetCtl.h"


int PSET_SYSV_ABI Pset_sceNetBweCheckCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweCheckCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweClearEventIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweClearEventIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweFinishInternetConnectionTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweFinishInternetConnectionTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweGetInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweGetInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweRegisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweRegisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweSetInternetConnectionTestResultIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweSetInternetConnectionTestResultIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweStartInternetConnectionTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweStartInternetConnectionTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweUnregisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweUnregisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfoV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfoV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResultV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResultV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetStateV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetStateV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectConfIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectConfIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectWithRetryIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectWithRetryIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlDisableBandwidthManagementIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlDisableBandwidthManagementIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlDisconnectIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlDisconnectIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlEnableBandwidthManagementIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlEnableBandwidthManagementIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetBandwidthInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetBandwidthInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetEtherLinkMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetEtherLinkMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetIfStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetIfStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNatInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNatInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNatInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNatInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNetEvConfigInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNetEvConfigInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResultIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResultIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoBssidIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoBssidIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoByBssidIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoByBssidIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoForSsidScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoForSsidScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetState2IpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetState2IpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetStateIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetStateIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetWifiType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetWifiType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlSetErrorNotificationEnabledIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlSetErrorNotificationEnabledIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlSetStunWithPaddingFlagIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlSetStunWithPaddingFlagIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncD8DCB6973537A3DC(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncD8DCB6973537A3DC");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApClearEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApClearEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetConnectInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetConnectInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApStop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApStop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApUnregisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppInitWpaKey(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppInitWpaKey");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppInitWpaKeyForQa(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppInitWpaKeyForQa");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppStartWithRetry(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppStartWithRetry");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppStartWithRetryPid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppStartWithRetryPid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRestart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRestart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpClearEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpClearEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStartConf(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStartConf");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStartWithRetry(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStartWithRetry");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpUnregisterCallback");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetBwe_libSceNetCtl[] =
{
 { 0x5ED0A548E0B5C5C5,"Pset_sceNetBweCheckCallbackIpcInt", (void*)Pset_sceNetBweCheckCallbackIpcInt },
 { 0x6002EAA18E1A798D,"Pset_sceNetBweClearEventIpcInt", (void*)Pset_sceNetBweClearEventIpcInt },
 { 0xA2EC9139684651B3,"Pset_sceNetBweFinishInternetConnectionTestIpcInt", (void*)Pset_sceNetBweFinishInternetConnectionTestIpcInt },
 { 0x1B8BE5B50D15B3ED,"Pset_sceNetBweGetInfoIpcInt", (void*)Pset_sceNetBweGetInfoIpcInt },
 { 0x1AA1132F9F883615,"Pset_sceNetBweRegisterCallbackIpcInt", (void*)Pset_sceNetBweRegisterCallbackIpcInt },
 { 0x98452DFE98467791,"Pset_sceNetBweSetInternetConnectionTestResultIpcInt", (void*)Pset_sceNetBweSetInternetConnectionTestResultIpcInt },
 { 0xA502C957948402A9,"Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt", (void*)Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt },
 { 0x73E698875DF4495D,"Pset_sceNetBweStartInternetConnectionTestIpcInt", (void*)Pset_sceNetBweStartInternetConnectionTestIpcInt },
 { 0xD255623DA4C1FD1F,"Pset_sceNetBweUnregisterCallbackIpcInt", (void*)Pset_sceNetBweUnregisterCallbackIpcInt },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlV6_libSceNetCtl[] =
{
 { 0x272D443B919D95C3,"Pset_sceNetCtlGetInfoV6", (void*)Pset_sceNetCtlGetInfoV6 },
 { 0x1F9C80460DFB5398,"Pset_sceNetCtlGetResultV6", (void*)Pset_sceNetCtlGetResultV6 },
 { 0xFA5C6A20A794F546,"Pset_sceNetCtlGetStateV6", (void*)Pset_sceNetCtlGetStateV6 },
 { 0xD4D13D396741230C,"Pset_sceNetCtlRegisterCallbackV6", (void*)Pset_sceNetCtlRegisterCallbackV6 },
 { 0x8485157943710307,"Pset_sceNetCtlUnregisterCallbackV6", (void*)Pset_sceNetCtlUnregisterCallbackV6 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtl_libSceNetCtl[] =
{
 { 0x890C378903E1BD44,"Pset_sceNetCtlCheckCallback", (void*)Pset_sceNetCtlCheckCallback },
 { 0x505E87EBE923C90B,"Pset_sceNetCtlCheckCallbackForLibIpcInt", (void*)Pset_sceNetCtlCheckCallbackForLibIpcInt },
 { 0xBEFEA0F33A1A9CBE,"Pset_sceNetCtlClearEventForLibIpcInt", (void*)Pset_sceNetCtlClearEventForLibIpcInt },
 { 0xF0E27CEAF16E71FA,"Pset_sceNetCtlClearEventIpcInt", (void*)Pset_sceNetCtlClearEventIpcInt },
 { 0x1C20F8E87553C908,"Pset_sceNetCtlConnectConfIpcInt", (void*)Pset_sceNetCtlConnectConfIpcInt },
 { 0x203F86AB70DDCDB8,"Pset_sceNetCtlConnectIpcInt", (void*)Pset_sceNetCtlConnectIpcInt },
 { 0x68FA6273C2BBE580,"Pset_sceNetCtlConnectWithRetryIpcInt", (void*)Pset_sceNetCtlConnectWithRetryIpcInt },
 { 0xF72E0872C25D4C27,"Pset_sceNetCtlDisableBandwidthManagementIpcInt", (void*)Pset_sceNetCtlDisableBandwidthManagementIpcInt },
 { 0xA8E79F729A12B349,"Pset_sceNetCtlDisconnectIpcInt", (void*)Pset_sceNetCtlDisconnectIpcInt },
 { 0xC7D6D2991484FA17,"Pset_sceNetCtlEnableBandwidthManagementIpcInt", (void*)Pset_sceNetCtlEnableBandwidthManagementIpcInt },
 { 0x782508940DADE421,"Pset_sceNetCtlGetBandwidthInfoIpcInt", (void*)Pset_sceNetCtlGetBandwidthInfoIpcInt },
 { 0xD847E33D754F937B,"Pset_sceNetCtlGetEtherLinkMode", (void*)Pset_sceNetCtlGetEtherLinkMode },
 { 0xB5EB8AE109C94C68,"Pset_sceNetCtlGetIfStat", (void*)Pset_sceNetCtlGetIfStat },
 { 0xA1BBB17538B0905F,"Pset_sceNetCtlGetInfo", (void*)Pset_sceNetCtlGetInfo },
 { 0xC6CB5C4EA0214F2B,"Pset_sceNetCtlGetInfoIpcInt", (void*)Pset_sceNetCtlGetInfoIpcInt },
 { 0x24EE32B93B8CA0A2,"Pset_sceNetCtlGetNatInfo", (void*)Pset_sceNetCtlGetNatInfo },
 { 0xC7E727B00C4A487A,"Pset_sceNetCtlGetNatInfoIpcInt", (void*)Pset_sceNetCtlGetNatInfoIpcInt },
 { 0x8614EC76FF7D6B35,"Pset_sceNetCtlGetNetEvConfigInfoIpcInt", (void*)Pset_sceNetCtlGetNetEvConfigInfoIpcInt },
 { 0xD1C06076E3D147E3,"Pset_sceNetCtlGetResult", (void*)Pset_sceNetCtlGetResult },
 { 0x344B67BAC6D9C80B,"Pset_sceNetCtlGetResultIpcInt", (void*)Pset_sceNetCtlGetResultIpcInt },
 { 0xC0FD006F699A4756,"Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt", (void*)Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt },
 { 0x5A7FFEF3CECBB76B,"Pset_sceNetCtlGetScanInfoBssidIpcInt", (void*)Pset_sceNetCtlGetScanInfoBssidIpcInt },
 { 0x144764386D556D0A,"Pset_sceNetCtlGetScanInfoByBssidIpcInt", (void*)Pset_sceNetCtlGetScanInfoByBssidIpcInt },
 { 0x8AB57CBE82001C3C,"Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt", (void*)Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt },
 { 0x2FDEDE007234C71B,"Pset_sceNetCtlGetScanInfoForSsidScanIpcInt", (void*)Pset_sceNetCtlGetScanInfoForSsidScanIpcInt },
 { 0xB813E5AF495BBA22,"Pset_sceNetCtlGetState", (void*)Pset_sceNetCtlGetState },
 { 0x257948F446558DFE,"Pset_sceNetCtlGetState2IpcInt", (void*)Pset_sceNetCtlGetState2IpcInt },
 { 0x82F9C93CC912A006,"Pset_sceNetCtlGetStateIpcInt", (void*)Pset_sceNetCtlGetStateIpcInt },
 { 0x0575BD6F7475370E,"Pset_sceNetCtlGetWifiType", (void*)Pset_sceNetCtlGetWifiType },
 { 0x824CB4FA868D3389,"Pset_sceNetCtlInit", (void*)Pset_sceNetCtlInit },
 { 0x62D0270A44D1D0AE,"Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt", (void*)Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt },
 { 0x509F99ED0FB8724D,"Pset_sceNetCtlRegisterCallback", (void*)Pset_sceNetCtlRegisterCallback },
 { 0x591BC3936B326AD1,"Pset_sceNetCtlRegisterCallbackForLibIpcInt", (void*)Pset_sceNetCtlRegisterCallbackForLibIpcInt },
 { 0xAEA921DA45EF2D2C,"Pset_sceNetCtlRegisterCallbackIpcInt", (void*)Pset_sceNetCtlRegisterCallbackIpcInt },
 { 0xADE22C1EBC820F1E,"Pset_sceNetCtlScanIpcInt", (void*)Pset_sceNetCtlScanIpcInt },
 { 0x2C96228884B81C1D,"Pset_sceNetCtlSetErrorNotificationEnabledIpcInt", (void*)Pset_sceNetCtlSetErrorNotificationEnabledIpcInt },
 { 0x0E3BAAAAA574F0D9,"Pset_sceNetCtlSetStunWithPaddingFlagIpcInt", (void*)Pset_sceNetCtlSetStunWithPaddingFlagIpcInt },
 { 0x678C3008588110B4,"Pset_sceNetCtlTerm", (void*)Pset_sceNetCtlTerm },
 { 0x46A9B63A764C0B3D,"Pset_sceNetCtlUnregisterCallback", (void*)Pset_sceNetCtlUnregisterCallback },
 { 0xBAB59A5169041998,"Pset_sceNetCtlUnregisterCallbackForLibIpcInt", (void*)Pset_sceNetCtlUnregisterCallbackForLibIpcInt },
 { 0x6F2F5C6C1EC91891,"Pset_sceNetCtlUnregisterCallbackIpcInt", (void*)Pset_sceNetCtlUnregisterCallbackIpcInt },
 { 0xD474AF90DF68C4EE,"Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt", (void*)Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt },
 { 0xD8DCB6973537A3DC,"NullNameFuncD8DCB6973537A3DC", (void*)NullNameFuncD8DCB6973537A3DC },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlForNpToolkit_libSceNetCtl[] =
{
 { 0xBB9A2AB6520FF85C,"Pset_sceNetCtlCheckCallbackForNpToolkit", (void*)Pset_sceNetCtlCheckCallbackForNpToolkit },
 { 0xB1A601D1BD995AD2,"Pset_sceNetCtlClearEventForNpToolkit", (void*)Pset_sceNetCtlClearEventForNpToolkit },
 { 0xC08B0ACBE4DF78BB,"Pset_sceNetCtlRegisterCallbackForNpToolkit", (void*)Pset_sceNetCtlRegisterCallbackForNpToolkit },
 { 0xDA852A291E687467,"Pset_sceNetCtlUnregisterCallbackForNpToolkit", (void*)Pset_sceNetCtlUnregisterCallbackForNpToolkit },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlAp_libSceNetCtl[] =
{
 { 0xD7D11CED690C15F4,"Pset_sceNetCtlApCheckCallback", (void*)Pset_sceNetCtlApCheckCallback },
 { 0x99E14C683A5DB152,"Pset_sceNetCtlApClearEvent", (void*)Pset_sceNetCtlApClearEvent },
 { 0x85F90B55D5E67E75,"Pset_sceNetCtlApGetConnectInfo", (void*)Pset_sceNetCtlApGetConnectInfo },
 { 0x2D7003CD323333D2,"Pset_sceNetCtlApGetInfo", (void*)Pset_sceNetCtlApGetInfo },
 { 0xE2390B25CF79E3E4,"Pset_sceNetCtlApGetResult", (void*)Pset_sceNetCtlApGetResult },
 { 0x00A64ECEC6FDC217,"Pset_sceNetCtlApGetState", (void*)Pset_sceNetCtlApGetState },
 { 0x15D37E79D351B62C,"Pset_sceNetCtlApInit", (void*)Pset_sceNetCtlApInit },
 { 0xA668E86D2547B98D,"Pset_sceNetCtlApRegisterCallback", (void*)Pset_sceNetCtlApRegisterCallback },
 { 0xAFFA4EC8DE8086C3,"Pset_sceNetCtlApStop", (void*)Pset_sceNetCtlApStop },
 { 0x72FE58D9E7CE4DE8,"Pset_sceNetCtlApTerm", (void*)Pset_sceNetCtlApTerm },
 { 0x3694DC16D690FF41,"Pset_sceNetCtlApUnregisterCallback", (void*)Pset_sceNetCtlApUnregisterCallback },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlApIpcInt_libSceNetCtl[] =
{
 { 0x47FE1AF58878B46F,"Pset_sceNetCtlApAppInitWpaKey", (void*)Pset_sceNetCtlApAppInitWpaKey },
 { 0xE682C9A0E5416C65,"Pset_sceNetCtlApAppInitWpaKeyForQa", (void*)Pset_sceNetCtlApAppInitWpaKeyForQa },
 { 0x62D4F0677A5AE1A4,"Pset_sceNetCtlApAppStartWithRetry", (void*)Pset_sceNetCtlApAppStartWithRetry },
 { 0xB2059E0EB12DDB85,"Pset_sceNetCtlApAppStartWithRetryPid", (void*)Pset_sceNetCtlApAppStartWithRetryPid },
 { 0x6A6A92187F25FFFB,"Pset_sceNetCtlApRestart", (void*)Pset_sceNetCtlApRestart },
 { 0x0EE7D06601F92127,"Pset_sceNetCtlApRpCheckCallback", (void*)Pset_sceNetCtlApRpCheckCallback },
 { 0xAA165B3A2FB6A8B6,"Pset_sceNetCtlApRpClearEvent", (void*)Pset_sceNetCtlApRpClearEvent },
 { 0x550975E90FAA5DE6,"Pset_sceNetCtlApRpGetInfo", (void*)Pset_sceNetCtlApRpGetInfo },
 { 0xDE9C7062A1F319CC,"Pset_sceNetCtlApRpGetResult", (void*)Pset_sceNetCtlApRpGetResult },
 { 0x2C49FC146CED2967,"Pset_sceNetCtlApRpGetState", (void*)Pset_sceNetCtlApRpGetState },
 { 0xA1F1AC2BEC6801A3,"Pset_sceNetCtlApRpRegisterCallback", (void*)Pset_sceNetCtlApRpRegisterCallback },
 { 0x9A3160A6A35ABC78,"Pset_sceNetCtlApRpStart", (void*)Pset_sceNetCtlApRpStart },
 { 0x1CCBDA1E8656B27F,"Pset_sceNetCtlApRpStartConf", (void*)Pset_sceNetCtlApRpStartConf },
 { 0xF43C60ED74A5AF6B,"Pset_sceNetCtlApRpStartWithRetry", (void*)Pset_sceNetCtlApRpStartWithRetry },
 { 0xEAEBC09784651329,"Pset_sceNetCtlApRpStop", (void*)Pset_sceNetCtlApRpStop },
 { 0xF1EC87DFB36CF2D9,"Pset_sceNetCtlApRpUnregisterCallback", (void*)Pset_sceNetCtlApRpUnregisterCallback },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceNetCtl[] =
{
 {"libSceNetBwe", gSymTable_libSceNetBwe_libSceNetCtl },
 {"libSceNetCtlV6", gSymTable_libSceNetCtlV6_libSceNetCtl },
 {"libSceNetCtl", gSymTable_libSceNetCtl_libSceNetCtl },
 {"libSceNetCtlForNpToolkit", gSymTable_libSceNetCtlForNpToolkit_libSceNetCtl },
 {"libSceNetCtlAp", gSymTable_libSceNetCtlAp_libSceNetCtl },
 {"libSceNetCtlApIpcInt", gSymTable_libSceNetCtlApIpcInt_libSceNetCtl },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceNetCtl("libSceNetCtl", gLibTable_libSceNetCtl);