//Generated By SceModuleGenerator
#include "pset_libSceAudioOut.h"


int PSET_SYSV_ABI Pset_sceAudioOutDeviceIdOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutDeviceIdOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioDeviceControlGet(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioDeviceControlGet");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioDeviceControlSet(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioDeviceControlSet");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutA3dControl(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutA3dControl");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutA3dExit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutA3dExit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutA3dInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutA3dInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutAttachToApplicationByPid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutAttachToApplicationByPid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutChangeAppModuleState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutChangeAppModuleState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutDetachFromApplicationByPid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutDetachFromApplicationByPid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExConfigureOutputMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExConfigureOutputMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExGetSystemInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExGetSystemInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExPtClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExPtClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExPtGetLastOutputTime(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExPtGetLastOutputTime");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExPtOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExPtOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutExSystemInfoIsSupportedAudioOutExMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutExSystemInfoIsSupportedAudioOutExMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetFocusEnablePid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetFocusEnablePid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetHandleStatusInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetHandleStatusInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetInfoOpenNum(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetInfoOpenNum");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetLastOutputTime(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetLastOutputTime");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetPortState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetPortState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetSimulatedBusUsableStatusByBusType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetSimulatedBusUsableStatusByBusType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetSimulatedHandleStatusInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetSimulatedHandleStatusInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetSimulatedHandleStatusInfo2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetSimulatedHandleStatusInfo2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetSparkVss(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetSparkVss");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutGetSystemState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutGetSystemState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutInitIpmiGetSession(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutInitIpmiGetSession");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutMasteringGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutMasteringGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutMasteringInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutMasteringInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutMasteringSetParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutMasteringSetParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutMasteringTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutMasteringTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutMbusInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutMbusInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutOpenEx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutOpenEx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutOutput(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutOutput");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutOutputs(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutOutputs");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutPtClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutPtClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutPtGetLastOutputTime(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutPtGetLastOutputTime");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutPtOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutPtOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetConnections(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetConnections");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetConnectionsForUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetConnectionsForUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetDevConnection(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetDevConnection");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetHeadphoneOutMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetHeadphoneOutMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetJediJackVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetJediJackVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetJediSpkVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetJediSpkVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetMainOutput(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetMainOutput");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetMixLevelPadSpk(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetMixLevelPadSpk");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetMorpheusParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetMorpheusParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetMorpheusWorkingMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetMorpheusWorkingMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetPortConnections(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetPortConnections");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetPortStatuses(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetPortStatuses");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetRecMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetRecMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetSparkParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetSparkParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetUsbVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetUsbVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetVolumeDown(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetVolumeDown");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutStartAuxBroadcast(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutStartAuxBroadcast");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutStartSharePlay(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutStartSharePlay");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutStopAuxBroadcast(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutStopAuxBroadcast");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutStopSharePlay(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutStopSharePlay");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSuspendResume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSuspendResume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSysConfigureOutputMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSysConfigureOutputMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSysGetHdmiMonitorInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSysGetHdmiMonitorInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSysGetSystemInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSysGetSystemInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSystemControlGet(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSystemControlGet");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSystemControlSet(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSystemControlSet");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSparkControlSetEqCoef(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSparkControlSetEqCoef");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceAudioOutSetSystemDebugState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceAudioOutSetSystemDebugState");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceAudioOutDeviceService_libSceAudioOut[] =
{
 { 0x731D9D6056F32008, (void*)Pset_sceAudioOutDeviceIdOpen },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceAudioDeviceControl_libSceAudioOut[] =
{
 { 0xB4ABA68D04B3872B, (void*)Pset_sceAudioDeviceControlGet },
 { 0xE4285F70739FDD23, (void*)Pset_sceAudioDeviceControlSet },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceAudioOut_libSceAudioOut[] =
{
 { 0x233F57EC84A5761B, (void*)Pset_sceAudioOutA3dControl },
 { 0xF51548A2870E540A, (void*)Pset_sceAudioOutA3dExit },
 { 0x9FB2A0C44F2B3AE1, (void*)Pset_sceAudioOutA3dInit },
 { 0x58100EEBF9F4FF83, (void*)Pset_sceAudioOutAttachToApplicationByPid },
 { 0x3B714CD965C825A2, (void*)Pset_sceAudioOutChangeAppModuleState },
 { 0xB35FFFB84F66045C, (void*)Pset_sceAudioOutClose },
 { 0xA25E0B6DE4C6F267, (void*)Pset_sceAudioOutDetachFromApplicationByPid },
 { 0xAF557D205104F93B, (void*)Pset_sceAudioOutExConfigureOutputMode },
 { 0xC196A4450B161A8B, (void*)Pset_sceAudioOutExGetSystemInfo },
 { 0xC638E14F9BB0D3CA, (void*)Pset_sceAudioOutExPtClose },
 { 0x0EC493ED336CC9FA, (void*)Pset_sceAudioOutExPtGetLastOutputTime },
 { 0xE14956DC24AE09AE, (void*)Pset_sceAudioOutExPtOpen },
 { 0x5DC8FC553B67670D, (void*)Pset_sceAudioOutExSystemInfoIsSupportedAudioOutExMode },
 { 0x237170726920E4FA, (void*)Pset_sceAudioOutGetFocusEnablePid },
 { 0x6379577C21445856, (void*)Pset_sceAudioOutGetHandleStatusInfo },
 { 0xFF4D0E02EB40C3E7, (void*)Pset_sceAudioOutGetInfo },
 { 0x46A98AC41A81F01E, (void*)Pset_sceAudioOutGetInfoOpenNum },
 { 0x3ED96DB37DBAA5DB, (void*)Pset_sceAudioOutGetLastOutputTime },
 { 0x1AB43DB3822B35A4, (void*)Pset_sceAudioOutGetPortState },
 { 0x73B995A33C4990F5, (void*)Pset_sceAudioOutGetSimulatedBusUsableStatusByBusType },
 { 0xA56992ECB6A3625A, (void*)Pset_sceAudioOutGetSimulatedHandleStatusInfo },
 { 0xA0F2E086101680C3, (void*)Pset_sceAudioOutGetSimulatedHandleStatusInfo2 },
 { 0xE7EAFB2581E99178, (void*)Pset_sceAudioOutGetSparkVss },
 { 0x47985E9A828A203F, (void*)Pset_sceAudioOutGetSystemState },
 { 0x25F10F5D5C6116A0, (void*)Pset_sceAudioOutInit },
 { 0x9F5E8A768C67BE5D, (void*)Pset_sceAudioOutInitIpmiGetSession },
 { 0xAFEA8AC3EB9E0FE4, (void*)Pset_sceAudioOutMasteringGetState },
 { 0xC57E112DE81AADB8, (void*)Pset_sceAudioOutMasteringInit },
 { 0xE34E79C9A520DC46, (void*)Pset_sceAudioOutMasteringSetParam },
 { 0x4555AD520A227F9A, (void*)Pset_sceAudioOutMasteringTerm },
 { 0xFCB5E1706011C379, (void*)Pset_sceAudioOutMbusInit },
 { 0x7A436FB13DB6AEC6, (void*)Pset_sceAudioOutOpen },
 { 0xA8BA522BBE655C8E, (void*)Pset_sceAudioOutOpenEx },
 { 0x40E42D6DE0EAB13E, (void*)Pset_sceAudioOutOutput },
 { 0xC373DD6924D2C061, (void*)Pset_sceAudioOutOutputs },
 { 0x31AA474E07A881B9, (void*)Pset_sceAudioOutPtClose },
 { 0x6196AAF9429BAE24, (void*)Pset_sceAudioOutPtGetLastOutputTime },
 { 0xC724FC21408BDC22, (void*)Pset_sceAudioOutPtOpen },
 { 0xA3838B410AAA03DD, (void*)Pset_sceAudioOutSetConnections },
 { 0x407AB6CA514E6749, (void*)Pset_sceAudioOutSetConnectionsForUser },
 { 0xAFD286A86A704E98, (void*)Pset_sceAudioOutSetDevConnection },
 { 0xD3C30A8B613F45C1, (void*)Pset_sceAudioOutSetHeadphoneOutMode },
 { 0xD7C2151AB2100D4E, (void*)Pset_sceAudioOutSetJediJackVolume },
 { 0x874A3E0F8618AF59, (void*)Pset_sceAudioOutSetJediSpkVolume },
 { 0x288F5C976DADA3B1, (void*)Pset_sceAudioOutSetMainOutput },
 { 0xC15C0F539D294B57, (void*)Pset_sceAudioOutSetMixLevelPadSpk },
 { 0x79E46C6DE1987B6D, (void*)Pset_sceAudioOutSetMorpheusParam },
 { 0x219AC8B4F9DF9413, (void*)Pset_sceAudioOutSetMorpheusWorkingMode },
 { 0x1B2D1178E8175B4D, (void*)Pset_sceAudioOutSetPortConnections },
 { 0xA110457E522B0A0D, (void*)Pset_sceAudioOutSetPortStatuses },
 { 0x69EFC854F3125A35, (void*)Pset_sceAudioOutSetRecMode },
 { 0x77758BDAE3C4D5E1, (void*)Pset_sceAudioOutSetSparkParam },
 { 0x5FB09FB22BA39BC6, (void*)Pset_sceAudioOutSetUsbVolume },
 { 0x6FEB8057CF489711, (void*)Pset_sceAudioOutSetVolume },
 { 0xAE1A3D0C7FF47A1B, (void*)Pset_sceAudioOutSetVolumeDown },
 { 0x23DD4FD0700FA63C, (void*)Pset_sceAudioOutStartAuxBroadcast },
 { 0xBA8F9EA0FCDD43FB, (void*)Pset_sceAudioOutStartSharePlay },
 { 0x0089A269816B29D7, (void*)Pset_sceAudioOutStopAuxBroadcast },
 { 0xB5E0B228A64F8CC1, (void*)Pset_sceAudioOutStopSharePlay },
 { 0xF796DDB4774D5227, (void*)Pset_sceAudioOutSuspendResume },
 { 0xA112599D7C6893F3, (void*)Pset_sceAudioOutSysConfigureOutputMode },
 { 0x4DFF7FC8E27017F0, (void*)Pset_sceAudioOutSysGetHdmiMonitorInfo },
 { 0xCB6FE13FF2A84CC2, (void*)Pset_sceAudioOutSysGetSystemInfo },
 { 0x615F9B9CCBCC7D88, (void*)Pset_sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode },
 { 0x2441E100D44470BB, (void*)Pset_sceAudioOutSystemControlGet },
 { 0xF421D656FEABDC38, (void*)Pset_sceAudioOutSystemControlSet },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceAudioOutSparkControl_libSceAudioOut[] =
{
 { 0x32DEC907794EC899, (void*)Pset_sceAudioOutSparkControlSetEqCoef },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceDbgAudioOut_libSceAudioOut[] =
{
 { 0xED4B1D0CE12F8E59, (void*)Pset_sceAudioOutSetSystemDebugState },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceAudioOut[] =
{
 {"libSceAudioOutDeviceService", gSymTable_libSceAudioOutDeviceService_libSceAudioOut },
 {"libSceAudioDeviceControl", gSymTable_libSceAudioDeviceControl_libSceAudioOut },
 {"libSceAudioOut", gSymTable_libSceAudioOut_libSceAudioOut },
 {"libSceAudioOutSparkControl", gSymTable_libSceAudioOutSparkControl_libSceAudioOut },
 {"libSceDbgAudioOut", gSymTable_libSceDbgAudioOut_libSceAudioOut },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceAudioOut("libSceAudioOut", gLibTable_libSceAudioOut);