//Generated By SceModuleGenerator
#include "pset_libSceMsgDialog.h"


int PSET_SYSV_ABI Pset_sceMsgDialogClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogGetStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogGetStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogProgressBarInc(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogProgressBarInc");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogProgressBarSetMsg(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogProgressBarSetMsg");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogProgressBarSetValue(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogProgressBarSetValue");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogTerminate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogTerminate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceMsgDialogUpdateStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceMsgDialogUpdateStatus");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceMsgDialog_libSceMsgDialog[] =
{
 { 0x1D3ADC0CA9452AE3,"Pset_sceMsgDialogClose", (void*)Pset_sceMsgDialogClose },
 { 0x2EBF28BC71FD97A0,"Pset_sceMsgDialogGetResult", (void*)Pset_sceMsgDialogGetResult },
 { 0x096556EFC41CDDF2,"Pset_sceMsgDialogGetStatus", (void*)Pset_sceMsgDialogGetStatus },
 { 0x943AB1698D546C4A,"Pset_sceMsgDialogInitialize", (void*)Pset_sceMsgDialogInitialize },
 { 0x6F4E878740CF11A1,"Pset_sceMsgDialogOpen", (void*)Pset_sceMsgDialogOpen },
 { 0x19CE64D6A70AE1FB,"Pset_sceMsgDialogProgressBarInc", (void*)Pset_sceMsgDialogProgressBarInc },
 { 0xE87FFBD4E76BA573,"Pset_sceMsgDialogProgressBarSetMsg", (void*)Pset_sceMsgDialogProgressBarSetMsg },
 { 0xC13A5F825926BF7E,"Pset_sceMsgDialogProgressBarSetValue", (void*)Pset_sceMsgDialogProgressBarSetValue },
 { 0x78FC3F92A6667A5A,"Pset_sceMsgDialogTerminate", (void*)Pset_sceMsgDialogTerminate },
 { 0xE9F202DD72ADDA4D,"Pset_sceMsgDialogUpdateStatus", (void*)Pset_sceMsgDialogUpdateStatus },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceMsgDialog[] =
{
 {"libSceMsgDialog", gSymTable_libSceMsgDialog_libSceMsgDialog },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceMsgDialog("libSceMsgDialog", gLibTable_libSceMsgDialog);