//Generated By SceModuleGenerator
#include "pset_libSceNetCtl.h"


int PSET_SYSV_ABI Pset_sceNetBweCheckCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweCheckCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweClearEventIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweClearEventIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweFinishInternetConnectionTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweFinishInternetConnectionTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweGetInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweGetInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweRegisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweRegisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweSetInternetConnectionTestResultIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweSetInternetConnectionTestResultIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweStartInternetConnectionTestIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweStartInternetConnectionTestIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetBweUnregisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetBweUnregisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfoV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfoV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResultV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResultV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetStateV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetStateV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackV6(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackV6");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectConfIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectConfIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlConnectWithRetryIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlConnectWithRetryIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlDisableBandwidthManagementIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlDisableBandwidthManagementIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlDisconnectIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlDisconnectIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlEnableBandwidthManagementIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlEnableBandwidthManagementIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetBandwidthInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetBandwidthInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetEtherLinkMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetEtherLinkMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetIfStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetIfStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNatInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNatInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNatInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNatInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetNetEvConfigInfoIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetNetEvConfigInfoIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetResultIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetResultIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoBssidIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoBssidIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoByBssidIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoByBssidIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetScanInfoForSsidScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetScanInfoForSsidScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetState2IpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetState2IpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetStateIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetStateIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlGetWifiType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlGetWifiType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlScanIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlScanIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlSetErrorNotificationEnabledIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlSetErrorNotificationEnabledIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlSetStunWithPaddingFlagIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlSetStunWithPaddingFlagIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackForLibIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackForLibIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncD8DCB6973537A3DC(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncD8DCB6973537A3DC");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlCheckCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlCheckCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlClearEventForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlClearEventForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlRegisterCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlRegisterCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlUnregisterCallbackForNpToolkit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlUnregisterCallbackForNpToolkit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApClearEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApClearEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetConnectInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetConnectInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApStop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApStop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApUnregisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppInitWpaKey(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppInitWpaKey");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppInitWpaKeyForQa(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppInitWpaKeyForQa");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppStartWithRetry(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppStartWithRetry");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApAppStartWithRetryPid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApAppStartWithRetryPid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRestart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRestart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpCheckCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpCheckCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpClearEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpClearEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpGetState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpGetState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpRegisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpRegisterCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStartConf(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStartConf");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStartWithRetry(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStartWithRetry");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpStop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpStop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNetCtlApRpUnregisterCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNetCtlApRpUnregisterCallback");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetBwe_libSceNetCtl[] =
{
 { 0x5ED0A548E0B5C5C5, (void*)Pset_sceNetBweCheckCallbackIpcInt },
 { 0x6002EAA18E1A798D, (void*)Pset_sceNetBweClearEventIpcInt },
 { 0xA2EC9139684651B3, (void*)Pset_sceNetBweFinishInternetConnectionTestIpcInt },
 { 0x1B8BE5B50D15B3ED, (void*)Pset_sceNetBweGetInfoIpcInt },
 { 0x1AA1132F9F883615, (void*)Pset_sceNetBweRegisterCallbackIpcInt },
 { 0x98452DFE98467791, (void*)Pset_sceNetBweSetInternetConnectionTestResultIpcInt },
 { 0xA502C957948402A9, (void*)Pset_sceNetBweStartInternetConnectionTestBandwidthTestIpcInt },
 { 0x73E698875DF4495D, (void*)Pset_sceNetBweStartInternetConnectionTestIpcInt },
 { 0xD255623DA4C1FD1F, (void*)Pset_sceNetBweUnregisterCallbackIpcInt },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlV6_libSceNetCtl[] =
{
 { 0x272D443B919D95C3, (void*)Pset_sceNetCtlGetInfoV6 },
 { 0x1F9C80460DFB5398, (void*)Pset_sceNetCtlGetResultV6 },
 { 0xFA5C6A20A794F546, (void*)Pset_sceNetCtlGetStateV6 },
 { 0xD4D13D396741230C, (void*)Pset_sceNetCtlRegisterCallbackV6 },
 { 0x8485157943710307, (void*)Pset_sceNetCtlUnregisterCallbackV6 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtl_libSceNetCtl[] =
{
 { 0x890C378903E1BD44, (void*)Pset_sceNetCtlCheckCallback },
 { 0x505E87EBE923C90B, (void*)Pset_sceNetCtlCheckCallbackForLibIpcInt },
 { 0xBEFEA0F33A1A9CBE, (void*)Pset_sceNetCtlClearEventForLibIpcInt },
 { 0xF0E27CEAF16E71FA, (void*)Pset_sceNetCtlClearEventIpcInt },
 { 0x1C20F8E87553C908, (void*)Pset_sceNetCtlConnectConfIpcInt },
 { 0x203F86AB70DDCDB8, (void*)Pset_sceNetCtlConnectIpcInt },
 { 0x68FA6273C2BBE580, (void*)Pset_sceNetCtlConnectWithRetryIpcInt },
 { 0xF72E0872C25D4C27, (void*)Pset_sceNetCtlDisableBandwidthManagementIpcInt },
 { 0xA8E79F729A12B349, (void*)Pset_sceNetCtlDisconnectIpcInt },
 { 0xC7D6D2991484FA17, (void*)Pset_sceNetCtlEnableBandwidthManagementIpcInt },
 { 0x782508940DADE421, (void*)Pset_sceNetCtlGetBandwidthInfoIpcInt },
 { 0xD847E33D754F937B, (void*)Pset_sceNetCtlGetEtherLinkMode },
 { 0xB5EB8AE109C94C68, (void*)Pset_sceNetCtlGetIfStat },
 { 0xA1BBB17538B0905F, (void*)Pset_sceNetCtlGetInfo },
 { 0xC6CB5C4EA0214F2B, (void*)Pset_sceNetCtlGetInfoIpcInt },
 { 0x24EE32B93B8CA0A2, (void*)Pset_sceNetCtlGetNatInfo },
 { 0xC7E727B00C4A487A, (void*)Pset_sceNetCtlGetNatInfoIpcInt },
 { 0x8614EC76FF7D6B35, (void*)Pset_sceNetCtlGetNetEvConfigInfoIpcInt },
 { 0xD1C06076E3D147E3, (void*)Pset_sceNetCtlGetResult },
 { 0x344B67BAC6D9C80B, (void*)Pset_sceNetCtlGetResultIpcInt },
 { 0xC0FD006F699A4756, (void*)Pset_sceNetCtlGetScanInfoBssidForSsidListScanIpcInt },
 { 0x5A7FFEF3CECBB76B, (void*)Pset_sceNetCtlGetScanInfoBssidIpcInt },
 { 0x144764386D556D0A, (void*)Pset_sceNetCtlGetScanInfoByBssidIpcInt },
 { 0x8AB57CBE82001C3C, (void*)Pset_sceNetCtlGetScanInfoForSsidListScanIpcInt },
 { 0x2FDEDE007234C71B, (void*)Pset_sceNetCtlGetScanInfoForSsidScanIpcInt },
 { 0xB813E5AF495BBA22, (void*)Pset_sceNetCtlGetState },
 { 0x257948F446558DFE, (void*)Pset_sceNetCtlGetState2IpcInt },
 { 0x82F9C93CC912A006, (void*)Pset_sceNetCtlGetStateIpcInt },
 { 0x0575BD6F7475370E, (void*)Pset_sceNetCtlGetWifiType },
 { 0x824CB4FA868D3389, (void*)Pset_sceNetCtlInit },
 { 0x62D0270A44D1D0AE, (void*)Pset_sceNetCtlIsBandwidthManagementEnabledIpcInt },
 { 0x509F99ED0FB8724D, (void*)Pset_sceNetCtlRegisterCallback },
 { 0x591BC3936B326AD1, (void*)Pset_sceNetCtlRegisterCallbackForLibIpcInt },
 { 0xAEA921DA45EF2D2C, (void*)Pset_sceNetCtlRegisterCallbackIpcInt },
 { 0xADE22C1EBC820F1E, (void*)Pset_sceNetCtlScanIpcInt },
 { 0x2C96228884B81C1D, (void*)Pset_sceNetCtlSetErrorNotificationEnabledIpcInt },
 { 0x0E3BAAAAA574F0D9, (void*)Pset_sceNetCtlSetStunWithPaddingFlagIpcInt },
 { 0x678C3008588110B4, (void*)Pset_sceNetCtlTerm },
 { 0x46A9B63A764C0B3D, (void*)Pset_sceNetCtlUnregisterCallback },
 { 0xBAB59A5169041998, (void*)Pset_sceNetCtlUnregisterCallbackForLibIpcInt },
 { 0x6F2F5C6C1EC91891, (void*)Pset_sceNetCtlUnregisterCallbackIpcInt },
 { 0xD474AF90DF68C4EE, (void*)Pset_sceNetCtlUnsetStunWithPaddingFlagIpcInt },
 { 0xD8DCB6973537A3DC, (void*)NullNameFuncD8DCB6973537A3DC },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlForNpToolkit_libSceNetCtl[] =
{
 { 0xBB9A2AB6520FF85C, (void*)Pset_sceNetCtlCheckCallbackForNpToolkit },
 { 0xB1A601D1BD995AD2, (void*)Pset_sceNetCtlClearEventForNpToolkit },
 { 0xC08B0ACBE4DF78BB, (void*)Pset_sceNetCtlRegisterCallbackForNpToolkit },
 { 0xDA852A291E687467, (void*)Pset_sceNetCtlUnregisterCallbackForNpToolkit },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlAp_libSceNetCtl[] =
{
 { 0xD7D11CED690C15F4, (void*)Pset_sceNetCtlApCheckCallback },
 { 0x99E14C683A5DB152, (void*)Pset_sceNetCtlApClearEvent },
 { 0x85F90B55D5E67E75, (void*)Pset_sceNetCtlApGetConnectInfo },
 { 0x2D7003CD323333D2, (void*)Pset_sceNetCtlApGetInfo },
 { 0xE2390B25CF79E3E4, (void*)Pset_sceNetCtlApGetResult },
 { 0x00A64ECEC6FDC217, (void*)Pset_sceNetCtlApGetState },
 { 0x15D37E79D351B62C, (void*)Pset_sceNetCtlApInit },
 { 0xA668E86D2547B98D, (void*)Pset_sceNetCtlApRegisterCallback },
 { 0xAFFA4EC8DE8086C3, (void*)Pset_sceNetCtlApStop },
 { 0x72FE58D9E7CE4DE8, (void*)Pset_sceNetCtlApTerm },
 { 0x3694DC16D690FF41, (void*)Pset_sceNetCtlApUnregisterCallback },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNetCtlApIpcInt_libSceNetCtl[] =
{
 { 0x47FE1AF58878B46F, (void*)Pset_sceNetCtlApAppInitWpaKey },
 { 0xE682C9A0E5416C65, (void*)Pset_sceNetCtlApAppInitWpaKeyForQa },
 { 0x62D4F0677A5AE1A4, (void*)Pset_sceNetCtlApAppStartWithRetry },
 { 0xB2059E0EB12DDB85, (void*)Pset_sceNetCtlApAppStartWithRetryPid },
 { 0x6A6A92187F25FFFB, (void*)Pset_sceNetCtlApRestart },
 { 0x0EE7D06601F92127, (void*)Pset_sceNetCtlApRpCheckCallback },
 { 0xAA165B3A2FB6A8B6, (void*)Pset_sceNetCtlApRpClearEvent },
 { 0x550975E90FAA5DE6, (void*)Pset_sceNetCtlApRpGetInfo },
 { 0xDE9C7062A1F319CC, (void*)Pset_sceNetCtlApRpGetResult },
 { 0x2C49FC146CED2967, (void*)Pset_sceNetCtlApRpGetState },
 { 0xA1F1AC2BEC6801A3, (void*)Pset_sceNetCtlApRpRegisterCallback },
 { 0x9A3160A6A35ABC78, (void*)Pset_sceNetCtlApRpStart },
 { 0x1CCBDA1E8656B27F, (void*)Pset_sceNetCtlApRpStartConf },
 { 0xF43C60ED74A5AF6B, (void*)Pset_sceNetCtlApRpStartWithRetry },
 { 0xEAEBC09784651329, (void*)Pset_sceNetCtlApRpStop },
 { 0xF1EC87DFB36CF2D9, (void*)Pset_sceNetCtlApRpUnregisterCallback },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceNetCtl[] =
{
 {"libSceNetBwe", gSymTable_libSceNetBwe_libSceNetCtl },
 {"libSceNetCtlV6", gSymTable_libSceNetCtlV6_libSceNetCtl },
 {"libSceNetCtl", gSymTable_libSceNetCtl_libSceNetCtl },
 {"libSceNetCtlForNpToolkit", gSymTable_libSceNetCtlForNpToolkit_libSceNetCtl },
 {"libSceNetCtlAp", gSymTable_libSceNetCtlAp_libSceNetCtl },
 {"libSceNetCtlApIpcInt", gSymTable_libSceNetCtlApIpcInt_libSceNetCtl },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceNetCtl("libSceNetCtl", gLibTable_libSceNetCtl);