//Generated By SceModuleGenerator
#include "pset_libSceXml.h"


int PSET_SYSV_ABI Pset__ZN3sce3Xml10SimpleDataC1EPKcm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml10SimpleDataC1EPKcm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml10SimpleDataC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml10SimpleDataC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml10SimpleDataC2EPKcm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml10SimpleDataC2EPKcm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml10SimpleDataC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml10SimpleDataC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11Initializer10initializeEPKNS0_13InitParameterE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11Initializer10initializeEPKNS0_13InitParameterE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11Initializer9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11Initializer9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11InitializerC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11InitializerC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11InitializerC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11InitializerC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11InitializerD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11InitializerD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml11InitializerD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml11InitializerD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml12MemAllocatorC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml12MemAllocatorC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml12MemAllocatorD0Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml12MemAllocatorD0Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml12MemAllocatorD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml12MemAllocatorD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml12MemAllocatorD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml12MemAllocatorD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeList10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeList10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeList12addAttributeEPKNS0_6StringES4_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeList12addAttributeEPKNS0_6StringES4_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeList5clearEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeList5clearEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeList9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeList9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListC1ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListC1ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListC2ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListC2ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml13AttributeListD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml13AttributeListD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml18SerializeParameterC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml18SerializeParameterC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml18SerializeParameterC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml18SerializeParameterC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom13invalidNodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom13invalidNodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder11getDocumentEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder11getDocumentEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder16setResolveEntityEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder16setResolveEntityEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder20setSkipIgnorableTextEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder20setSkipIgnorableTextEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder26setSkipIgnorableWhiteSpaceEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder26setSkipIgnorableWhiteSpaceEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder5parseEPKNS0_6StringEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder5parseEPKNS0_6StringEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilder9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilder9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilderC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilderC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilderC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilderC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilderD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilderD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom15DocumentBuilderD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom15DocumentBuilderD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4Node11appendChildENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4Node11appendChildENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4Node11removeChildENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4Node11removeChildENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4Node12insertBeforeENS1_6NodeIdES3_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4Node12insertBeforeENS1_6NodeIdES3_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeaSERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeaSERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeC1ENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeC1ENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeC1ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeC1ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeC2ENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeC2ENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeC2ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeC2ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom4NodeD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom4NodeD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdaSES2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdaSES2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdC1EPvS3_b(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdC1EPvS3_b");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdC2EPvS3_b(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdC2EPvS3_b");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdcvPvEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdcvPvEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdeqEi(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdeqEi");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdeqES2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdeqES2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdneEi(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdneEi");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdneES2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdneES2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom6NodeIdntEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom6NodeIdntEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document10importNodeENS1_6NodeIdES3_PKS2_S3_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document10importNodeENS1_6NodeIdES3_PKS2_S3_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document10insertNodeENS1_6NodeIdES3_S3_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document10insertNodeENS1_6NodeIdES3_S3_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document11removeChildENS1_6NodeIdES3_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document11removeChildENS1_6NodeIdES3_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document11resetStatusEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document11resetStatusEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document11setWritableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document11setWritableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document12importParentEPKS2_NS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document12importParentEPKS2_NS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document12setAttributeENS1_6NodeIdEPKNS0_6StringES6_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document12setAttributeENS1_6NodeIdEPKNS0_6StringES6_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document12setAttrValueENS1_6NodeIdEPKNS0_6StringES6_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document12setAttrValueENS1_6NodeIdEPKNS0_6StringES6_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document13createElementEPKNS0_6StringEPKNS0_13AttributeListES5_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document13createElementEPKNS0_6StringEPKNS0_13AttributeListES5_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document13recurseDeleteENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document13recurseDeleteENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document14createTextNodeEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document14createTextNodeEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document15addElementChildENS1_6NodeIdEPKNS0_6StringEPKNS0_13AttributeListES6_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document15addElementChildENS1_6NodeIdEPKNS0_6StringEPKNS0_13AttributeListES6_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document15removeAttributeENS1_6NodeIdEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document15removeAttributeENS1_6NodeIdEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document16removeAttributesENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document16removeAttributesENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document16setAttributeListENS1_6NodeIdEPKNS0_13AttributeListE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document16setAttributeListENS1_6NodeIdEPKNS0_13AttributeListE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document7setTextENS1_6NodeIdEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document7setTextENS1_6NodeIdEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document9serializeEPKNS0_18SerializeParameterEPNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document9serializeEPKNS0_18SerializeParameterEPNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8Document9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8Document9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentaSERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentaSERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentC1ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentC1ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentC2ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentC2ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8DocumentD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8DocumentD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList10insertLastENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList10insertLastENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList10removeItemENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList10removeItemENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList11insertFirstENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList11insertFirstENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList5clearEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList5clearEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeList9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeList9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListC1ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListC1ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListC2ERKS2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListC2ERKS2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Dom8NodeListD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Dom8NodeListD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser11setUserDataEPv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser11setUserDataEPv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser16setResolveEntityEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser16setResolveEntityEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser18setDocumentHandlerEPNS1_15DocumentHandlerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser18setDocumentHandlerEPNS1_15DocumentHandlerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser26setSkipIgnorableWhiteSpaceEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser26setSkipIgnorableWhiteSpaceEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser5parseEPKNS0_6StringEb(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser5parseEPKNS0_6StringEb");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser5resetEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser5resetEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6Parser9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6Parser9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6ParserC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6ParserC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6ParserC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6ParserC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6ParserD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6ParserD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml3Sax6ParserD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml3Sax6ParserD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4Attr10initializeEPKNS0_11InitializerE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4Attr10initializeEPKNS0_11InitializerE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4Attr7setNameEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4Attr7setNameEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4Attr8setValueEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4Attr8setValueEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4Attr9terminateEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4Attr9terminateEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttraSERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttraSERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrC1ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrC1ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrC2ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrC2ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrD1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrD1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4AttrD2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4AttrD2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml4Util9strResultEi(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml4Util9strResultEi");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringaSERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringaSERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC1EPKc(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC1EPKc");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC1EPKcm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC1EPKcm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC1ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC1ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC1Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC1Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC2EPKc(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC2EPKc");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC2EPKcm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC2EPKcm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC2ERKS1_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC2ERKS1_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZN3sce3Xml6StringC2Ev(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZN3sce3Xml6StringC2Ev");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml13AttributeList11isAvailableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml13AttributeList11isAvailableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml13AttributeList12getAttributeEj(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml13AttributeList12getAttributeEj");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml13AttributeList12getAttributeEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml13AttributeList12getAttributeEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml13AttributeList9getLengthEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml13AttributeList9getLengthEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node11getNodeNameEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node11getNodeNameEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node11getNodeTypeEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node11getNodeTypeEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node11isAvailableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node11isAvailableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node12getLastChildEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node12getLastChildEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node12getNodeValueEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node12getNodeValueEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13getAttributesEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13getAttributesEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13getChildNodesEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13getChildNodesEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13getFirstChildEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13getFirstChildEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13getParentNodeEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13getParentNodeEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13hasAttributesEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13hasAttributesEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node13hasChildNodesEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node13hasChildNodesEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node14getNextSiblingEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node14getNextSiblingEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom4Node16getOwnerDocumentEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom4Node16getOwnerDocumentEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document10getDocRootEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document10getDocRootEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document10getSiblingENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document10getSiblingENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document10getXmlMetaEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document10getXmlMetaEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document10isReadOnlyEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document10isReadOnlyEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document11getAttrNameENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document11getAttrNameENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document11getNextAttrENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document11getNextAttrENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document11getNodeNameENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document11getNodeNameENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document11getNodeTypeENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document11getNodeTypeENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document11isAvailableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document11isAvailableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document12getAttributeENS1_6NodeIdEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document12getAttributeENS1_6NodeIdEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document12getAttrValueENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document12getAttrValueENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document12getFirstAttrENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document12getFirstAttrENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document12getLastChildENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document12getLastChildENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13getAttributesENS1_6NodeIdEPNS1_8NodeListE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13getAttributesENS1_6NodeIdEPNS1_8NodeListE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13getChildNodesENS1_6NodeIdEPNS1_8NodeListE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13getChildNodesENS1_6NodeIdEPNS1_8NodeListE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13getEntityTypeENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13getEntityTypeENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13getFirstChildENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13getFirstChildENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13hasAttributesENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13hasAttributesENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document13hasChildNodesENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document13hasChildNodesENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document14getSkippedTextENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document14getSkippedTextENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document20getElementsByTagNameENS1_6NodeIdEPKNS0_6StringEPNS1_8NodeListE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document20getElementsByTagNameENS1_6NodeIdEPKNS0_6StringEPNS1_8NodeListE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document7getRootEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document7getRootEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document7getTextENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document7getTextENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document9getEntityENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document9getEntityENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document9getParentENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document9getParentENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8Document9getStatusEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8Document9getStatusEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeList11isAvailableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeList11isAvailableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeList4itemEj(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeList4itemEj");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeList8findItemENS1_6NodeIdE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeList8findItemENS1_6NodeIdE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeList8findItemEPKNS0_6StringE(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeList8findItemEPKNS0_6StringE");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeList9getLengthEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeList9getLengthEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml3Dom8NodeListixEj(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml3Dom8NodeListixEj");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml4Attr11isAvailableEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml4Attr11isAvailableEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml4Attr7getNameEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml4Attr7getNameEv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset__ZNK3sce3Xml4Attr8getValueEv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__ZNK3sce3Xml4Attr8getValueEv");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceXml_libSceXml[] =
{
 { 0x3C6E82DFE6363C6E, (void*)Pset__ZN3sce3Xml10SimpleDataC1EPKcm },
 { 0x7C4BE30265BE22EB, (void*)Pset__ZN3sce3Xml10SimpleDataC1Ev },
 { 0x6E3B0BD0631C1CC2, (void*)Pset__ZN3sce3Xml10SimpleDataC2EPKcm },
 { 0x42E8573EEB9A7E2D, (void*)Pset__ZN3sce3Xml10SimpleDataC2Ev },
 { 0xD1AE36C5959346A0, (void*)Pset__ZN3sce3Xml11Initializer10initializeEPKNS0_13InitParameterE },
 { 0x4767610B26834F8F, (void*)Pset__ZN3sce3Xml11Initializer9terminateEv },
 { 0x64980A37EA309F7C, (void*)Pset__ZN3sce3Xml11InitializerC1Ev },
 { 0x1F39AC8927D88374, (void*)Pset__ZN3sce3Xml11InitializerC2Ev },
 { 0x3940DD71FD6DBFCD, (void*)Pset__ZN3sce3Xml11InitializerD1Ev },
 { 0xEA511CD44C610DB1, (void*)Pset__ZN3sce3Xml11InitializerD2Ev },
 { 0x717435986B1452CA, (void*)Pset__ZN3sce3Xml12MemAllocatorC2Ev },
 { 0xE6795A381658AAE2, (void*)Pset__ZN3sce3Xml12MemAllocatorD0Ev },
 { 0x5B21A41A308C6E17, (void*)Pset__ZN3sce3Xml12MemAllocatorD1Ev },
 { 0x91A4E7EC2F07EA25, (void*)Pset__ZN3sce3Xml12MemAllocatorD2Ev },
 { 0x52B0E11E3D3104BB, (void*)Pset__ZN3sce3Xml13AttributeList10initializeEPKNS0_11InitializerE },
 { 0x6675FFA5F427B9DC, (void*)Pset__ZN3sce3Xml13AttributeList12addAttributeEPKNS0_6StringES4_ },
 { 0x5DAAD298CAF545FD, (void*)Pset__ZN3sce3Xml13AttributeList5clearEv },
 { 0x7B3CE40962F3988D, (void*)Pset__ZN3sce3Xml13AttributeList9terminateEv },
 { 0x354D552A5A8A0EB0, (void*)Pset__ZN3sce3Xml13AttributeListC1ERKS1_ },
 { 0x06625220BCAECFDD, (void*)Pset__ZN3sce3Xml13AttributeListC1Ev },
 { 0x679EA2AD4B625EDD, (void*)Pset__ZN3sce3Xml13AttributeListC2ERKS1_ },
 { 0x318A2730BF6BD2C4, (void*)Pset__ZN3sce3Xml13AttributeListC2Ev },
 { 0x5F83627A4B4AEF61, (void*)Pset__ZN3sce3Xml13AttributeListD1Ev },
 { 0x5709206DF30836C7, (void*)Pset__ZN3sce3Xml13AttributeListD2Ev },
 { 0xCE5F1A9A7D7B1319, (void*)Pset__ZN3sce3Xml18SerializeParameterC1Ev },
 { 0x6A4D3D43E9983349, (void*)Pset__ZN3sce3Xml18SerializeParameterC2Ev },
 { 0x28F2A257F59D22BF, (void*)Pset__ZN3sce3Xml3Dom13invalidNodeIdE },
 { 0x70666072BABF2FD0, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder10initializeEPKNS0_11InitializerE },
 { 0x857F23F725422F86, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder11getDocumentEv },
 { 0x60350A27FC888DA1, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder16setResolveEntityEb },
 { 0x2E43855226E51929, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder20setSkipIgnorableTextEb },
 { 0xE2CFE47CA160FB9A, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder26setSkipIgnorableWhiteSpaceEb },
 { 0x375881DC8F155E2B, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder5parseEPKNS0_6StringEb },
 { 0x4765D5D1EC23DDD2, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilder9terminateEv },
 { 0x48481E723BD5BED3, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilderC1Ev },
 { 0x6A1AC5FFB7E6518F, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilderC2Ev },
 { 0xAC6D84493A0BDCAD, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilderD1Ev },
 { 0x76AB2F011BF406F7, (void*)Pset__ZN3sce3Xml3Dom15DocumentBuilderD2Ev },
 { 0xC712E5B1391264DF, (void*)Pset__ZN3sce3Xml3Dom4Node11appendChildENS1_6NodeIdE },
 { 0xEB586A42A3AF2F4D, (void*)Pset__ZN3sce3Xml3Dom4Node11removeChildENS1_6NodeIdE },
 { 0x9CFF1BD445E66F87, (void*)Pset__ZN3sce3Xml3Dom4Node12insertBeforeENS1_6NodeIdES3_ },
 { 0x666FB704DD6B6943, (void*)Pset__ZN3sce3Xml3Dom4NodeaSERKS2_ },
 { 0x017B2FCAFC1E21C9, (void*)Pset__ZN3sce3Xml3Dom4NodeC1ENS1_6NodeIdE },
 { 0x946CD1CF3E19A7DA, (void*)Pset__ZN3sce3Xml3Dom4NodeC1ERKS2_ },
 { 0x218537D71B47041C, (void*)Pset__ZN3sce3Xml3Dom4NodeC2ENS1_6NodeIdE },
 { 0x71DA3FE6556CD599, (void*)Pset__ZN3sce3Xml3Dom4NodeC2ERKS2_ },
 { 0xAB57B275A9341D53, (void*)Pset__ZN3sce3Xml3Dom4NodeD1Ev },
 { 0x92C9B2F967670BEF, (void*)Pset__ZN3sce3Xml3Dom4NodeD2Ev },
 { 0xC2D0C1C3F3D0841F, (void*)Pset__ZN3sce3Xml3Dom6NodeIdaSES2_ },
 { 0xEAB760BE95410462, (void*)Pset__ZN3sce3Xml3Dom6NodeIdC1EPvS3_b },
 { 0xDD2B1D433610CE8E, (void*)Pset__ZN3sce3Xml3Dom6NodeIdC1Ev },
 { 0xAF6AC3593A02D4C4, (void*)Pset__ZN3sce3Xml3Dom6NodeIdC2EPvS3_b },
 { 0xDC748F45D4C5D5FC, (void*)Pset__ZN3sce3Xml3Dom6NodeIdC2Ev },
 { 0x845AAEE70E332220, (void*)Pset__ZN3sce3Xml3Dom6NodeIdcvPvEv },
 { 0x069A84694CE2D582, (void*)Pset__ZN3sce3Xml3Dom6NodeIdeqEi },
 { 0x6954C89D1073B06D, (void*)Pset__ZN3sce3Xml3Dom6NodeIdeqES2_ },
 { 0xFC099894008EAE20, (void*)Pset__ZN3sce3Xml3Dom6NodeIdneEi },
 { 0x347B0DDA72405663, (void*)Pset__ZN3sce3Xml3Dom6NodeIdneES2_ },
 { 0x0E9426CA01C4D0CA, (void*)Pset__ZN3sce3Xml3Dom6NodeIdntEv },
 { 0x53BF4FFECAC38A5F, (void*)Pset__ZN3sce3Xml3Dom8Document10importNodeENS1_6NodeIdES3_PKS2_S3_ },
 { 0x217CE918A1467471, (void*)Pset__ZN3sce3Xml3Dom8Document10initializeEPKNS0_11InitializerE },
 { 0x30EB3C3E71A13C75, (void*)Pset__ZN3sce3Xml3Dom8Document10insertNodeENS1_6NodeIdES3_S3_ },
 { 0x10CE4D2CFAA95257, (void*)Pset__ZN3sce3Xml3Dom8Document11removeChildENS1_6NodeIdES3_ },
 { 0x9442D46FECA6CD01, (void*)Pset__ZN3sce3Xml3Dom8Document11resetStatusEv },
 { 0x2986A7D47CE3DFA7, (void*)Pset__ZN3sce3Xml3Dom8Document11setWritableEv },
 { 0x713AB652B15197FB, (void*)Pset__ZN3sce3Xml3Dom8Document12importParentEPKS2_NS1_6NodeIdE },
 { 0x0303BF8F1CB9DAE1, (void*)Pset__ZN3sce3Xml3Dom8Document12setAttributeENS1_6NodeIdEPKNS0_6StringES6_ },
 { 0x015B24724E848B90, (void*)Pset__ZN3sce3Xml3Dom8Document12setAttrValueENS1_6NodeIdEPKNS0_6StringES6_ },
 { 0xFDBE8C7935FFA0AB, (void*)Pset__ZN3sce3Xml3Dom8Document13createElementEPKNS0_6StringEPKNS0_13AttributeListES5_ },
 { 0x81B6DDA18CA038E6, (void*)Pset__ZN3sce3Xml3Dom8Document13recurseDeleteENS1_6NodeIdE },
 { 0x41F0761E8C64C97C, (void*)Pset__ZN3sce3Xml3Dom8Document14createTextNodeEPKNS0_6StringE },
 { 0xB04756CDEC96CD4D, (void*)Pset__ZN3sce3Xml3Dom8Document15addElementChildENS1_6NodeIdEPKNS0_6StringEPKNS0_13AttributeListES6_ },
 { 0x76A105EC0D4D152C, (void*)Pset__ZN3sce3Xml3Dom8Document15removeAttributeENS1_6NodeIdEPKNS0_6StringE },
 { 0xD009B7B016D2C28D, (void*)Pset__ZN3sce3Xml3Dom8Document16removeAttributesENS1_6NodeIdE },
 { 0x0D88D7490A6669F7, (void*)Pset__ZN3sce3Xml3Dom8Document16setAttributeListENS1_6NodeIdEPKNS0_13AttributeListE },
 { 0x1F20B59609C63805, (void*)Pset__ZN3sce3Xml3Dom8Document7setTextENS1_6NodeIdEPKNS0_6StringE },
 { 0x093DA0B635A008DD, (void*)Pset__ZN3sce3Xml3Dom8Document9serializeEPKNS0_18SerializeParameterEPNS0_6StringE },
 { 0xA5744EEE18876D9C, (void*)Pset__ZN3sce3Xml3Dom8Document9terminateEv },
 { 0x6E7F90CC41FEC865, (void*)Pset__ZN3sce3Xml3Dom8DocumentaSERKS2_ },
 { 0x85790D65D08EFAA5, (void*)Pset__ZN3sce3Xml3Dom8DocumentC1ERKS2_ },
 { 0x14DCAB8AA0DEB4C6, (void*)Pset__ZN3sce3Xml3Dom8DocumentC1Ev },
 { 0x0961D58DE27A3190, (void*)Pset__ZN3sce3Xml3Dom8DocumentC2ERKS2_ },
 { 0x2F76533ABBE89324, (void*)Pset__ZN3sce3Xml3Dom8DocumentC2Ev },
 { 0xCC1F8A8CA2314F75, (void*)Pset__ZN3sce3Xml3Dom8DocumentD1Ev },
 { 0x8285137A7BA6E508, (void*)Pset__ZN3sce3Xml3Dom8DocumentD2Ev },
 { 0xC50105BDECC1B634, (void*)Pset__ZN3sce3Xml3Dom8NodeList10initializeEPKNS0_11InitializerE },
 { 0x94EE5613523EDFF7, (void*)Pset__ZN3sce3Xml3Dom8NodeList10insertLastENS1_6NodeIdE },
 { 0xE7F668428101CA69, (void*)Pset__ZN3sce3Xml3Dom8NodeList10removeItemENS1_6NodeIdE },
 { 0x0C3632C007ABE4AD, (void*)Pset__ZN3sce3Xml3Dom8NodeList11insertFirstENS1_6NodeIdE },
 { 0xC8701223C5433CCA, (void*)Pset__ZN3sce3Xml3Dom8NodeList5clearEv },
 { 0x09FFF690D259FE48, (void*)Pset__ZN3sce3Xml3Dom8NodeList9terminateEv },
 { 0x7C05A87F89FE6899, (void*)Pset__ZN3sce3Xml3Dom8NodeListC1ERKS2_ },
 { 0xE961FB441057BCD1, (void*)Pset__ZN3sce3Xml3Dom8NodeListC1Ev },
 { 0xD4A5122F745CADC5, (void*)Pset__ZN3sce3Xml3Dom8NodeListC2ERKS2_ },
 { 0x63A932E4AF6DF9FA, (void*)Pset__ZN3sce3Xml3Dom8NodeListC2Ev },
 { 0x85C23F565167D346, (void*)Pset__ZN3sce3Xml3Dom8NodeListD1Ev },
 { 0x063B713C6436FDF4, (void*)Pset__ZN3sce3Xml3Dom8NodeListD2Ev },
 { 0x267D3AE893474507, (void*)Pset__ZN3sce3Xml3Sax6Parser10initializeEPKNS0_11InitializerE },
 { 0x9E239A90CCE8F154, (void*)Pset__ZN3sce3Xml3Sax6Parser11setUserDataEPv },
 { 0x6BFC60AA94AA617F, (void*)Pset__ZN3sce3Xml3Sax6Parser16setResolveEntityEb },
 { 0x8B0190A8E28CC5E7, (void*)Pset__ZN3sce3Xml3Sax6Parser18setDocumentHandlerEPNS1_15DocumentHandlerE },
 { 0x4353CBB924EA1C75, (void*)Pset__ZN3sce3Xml3Sax6Parser26setSkipIgnorableWhiteSpaceEb },
 { 0x9DC638C1A588C955, (void*)Pset__ZN3sce3Xml3Sax6Parser5parseEPKNS0_6StringEb },
 { 0x711E32C283422743, (void*)Pset__ZN3sce3Xml3Sax6Parser5resetEv },
 { 0x7354FEC65F74088F, (void*)Pset__ZN3sce3Xml3Sax6Parser9terminateEv },
 { 0x12921FA3D4BAE187, (void*)Pset__ZN3sce3Xml3Sax6ParserC1Ev },
 { 0x13541B7CE36B06B2, (void*)Pset__ZN3sce3Xml3Sax6ParserC2Ev },
 { 0x832B9576926286FD, (void*)Pset__ZN3sce3Xml3Sax6ParserD1Ev },
 { 0xC4E0B444CA318483, (void*)Pset__ZN3sce3Xml3Sax6ParserD2Ev },
 { 0x953FA19B84075542, (void*)Pset__ZN3sce3Xml4Attr10initializeEPKNS0_11InitializerE },
 { 0xD8DAD0B3939CE4D5, (void*)Pset__ZN3sce3Xml4Attr7setNameEPKNS0_6StringE },
 { 0xCED3D1A7782715EA, (void*)Pset__ZN3sce3Xml4Attr8setValueEPKNS0_6StringE },
 { 0xA013ED3DBEC668C8, (void*)Pset__ZN3sce3Xml4Attr9terminateEv },
 { 0xE1BFEFA29DD6B91E, (void*)Pset__ZN3sce3Xml4AttraSERKS1_ },
 { 0x8781033C3CC7897D, (void*)Pset__ZN3sce3Xml4AttrC1ERKS1_ },
 { 0x189B9C36B4D8E649, (void*)Pset__ZN3sce3Xml4AttrC1Ev },
 { 0xB757E866D8E8176C, (void*)Pset__ZN3sce3Xml4AttrC2ERKS1_ },
 { 0x63EEF9FCB9C74D5A, (void*)Pset__ZN3sce3Xml4AttrC2Ev },
 { 0xB1F457B8E422C7D0, (void*)Pset__ZN3sce3Xml4AttrD1Ev },
 { 0xA42102EAF6D195D7, (void*)Pset__ZN3sce3Xml4AttrD2Ev },
 { 0x6C2DCED2D85C1D2F, (void*)Pset__ZN3sce3Xml4Util9strResultEi },
 { 0xBE584ABAB98ED9D3, (void*)Pset__ZN3sce3Xml6StringaSERKS1_ },
 { 0xB76756D582427411, (void*)Pset__ZN3sce3Xml6StringC1EPKc },
 { 0x5267D53C05DBB11D, (void*)Pset__ZN3sce3Xml6StringC1EPKcm },
 { 0x7BD4CD1FA78D1270, (void*)Pset__ZN3sce3Xml6StringC1ERKS1_ },
 { 0x67D92FBA57C42155, (void*)Pset__ZN3sce3Xml6StringC1Ev },
 { 0x07A7BB1FF08A70F4, (void*)Pset__ZN3sce3Xml6StringC2EPKc },
 { 0x2CE740326D985C8B, (void*)Pset__ZN3sce3Xml6StringC2EPKcm },
 { 0xDB4C2E78774BD0D9, (void*)Pset__ZN3sce3Xml6StringC2ERKS1_ },
 { 0x514C9D35D360E40C, (void*)Pset__ZN3sce3Xml6StringC2Ev },
 { 0x8CEE85F81E446F35, (void*)Pset__ZNK3sce3Xml13AttributeList11isAvailableEv },
 { 0x58B6945DC8B160FC, (void*)Pset__ZNK3sce3Xml13AttributeList12getAttributeEj },
 { 0xAF961280066C3B8A, (void*)Pset__ZNK3sce3Xml13AttributeList12getAttributeEPKNS0_6StringE },
 { 0x05C083DD5DF4C6C9, (void*)Pset__ZNK3sce3Xml13AttributeList9getLengthEv },
 { 0x1724A55CECA4E34A, (void*)Pset__ZNK3sce3Xml3Dom4Node11getNodeNameEv },
 { 0xB0BD683501DC0CDD, (void*)Pset__ZNK3sce3Xml3Dom4Node11getNodeTypeEv },
 { 0xE87691CEFDFBF5EC, (void*)Pset__ZNK3sce3Xml3Dom4Node11isAvailableEv },
 { 0x707F22175F2AA65C, (void*)Pset__ZNK3sce3Xml3Dom4Node12getLastChildEv },
 { 0xBB0893FACCFD1BC6, (void*)Pset__ZNK3sce3Xml3Dom4Node12getNodeValueEv },
 { 0xFA402D02101571DD, (void*)Pset__ZNK3sce3Xml3Dom4Node13getAttributesEv },
 { 0xB3D4E9402DF7D8D5, (void*)Pset__ZNK3sce3Xml3Dom4Node13getChildNodesEv },
 { 0x51049D7CB2FBAB1B, (void*)Pset__ZNK3sce3Xml3Dom4Node13getFirstChildEv },
 { 0x53080146CB3BD9D6, (void*)Pset__ZNK3sce3Xml3Dom4Node13getParentNodeEv },
 { 0xD66DB2F9EF35D710, (void*)Pset__ZNK3sce3Xml3Dom4Node13hasAttributesEv },
 { 0xFEFA88D06EB2B4CF, (void*)Pset__ZNK3sce3Xml3Dom4Node13hasChildNodesEv },
 { 0x8A6A93E397851C3E, (void*)Pset__ZNK3sce3Xml3Dom4Node14getNextSiblingEv },
 { 0x29D4177472BA60F8, (void*)Pset__ZNK3sce3Xml3Dom4Node16getOwnerDocumentEv },
 { 0x610DD91ED52F7409, (void*)Pset__ZNK3sce3Xml3Dom8Document10getDocRootEv },
 { 0x4DD9ED4B18D4E2C9, (void*)Pset__ZNK3sce3Xml3Dom8Document10getSiblingENS1_6NodeIdE },
 { 0x9AE13D380DF162FE, (void*)Pset__ZNK3sce3Xml3Dom8Document10getXmlMetaEv },
 { 0xBA23D5412C5796C7, (void*)Pset__ZNK3sce3Xml3Dom8Document10isReadOnlyEv },
 { 0x44470EEEB2E8D1F0, (void*)Pset__ZNK3sce3Xml3Dom8Document11getAttrNameENS1_6NodeIdE },
 { 0x6FD6FA3C0E5329CD, (void*)Pset__ZNK3sce3Xml3Dom8Document11getNextAttrENS1_6NodeIdE },
 { 0x19C78CE96136592E, (void*)Pset__ZNK3sce3Xml3Dom8Document11getNodeNameENS1_6NodeIdE },
 { 0xD4901936C38AB9AD, (void*)Pset__ZNK3sce3Xml3Dom8Document11getNodeTypeENS1_6NodeIdE },
 { 0x9DFA16510D5E0E5F, (void*)Pset__ZNK3sce3Xml3Dom8Document11isAvailableEv },
 { 0x9A255819B9372C7B, (void*)Pset__ZNK3sce3Xml3Dom8Document12getAttributeENS1_6NodeIdEPKNS0_6StringE },
 { 0x7F0E3EB4867FE2DF, (void*)Pset__ZNK3sce3Xml3Dom8Document12getAttrValueENS1_6NodeIdE },
 { 0x8CC5934CEE97FE4C, (void*)Pset__ZNK3sce3Xml3Dom8Document12getFirstAttrENS1_6NodeIdE },
 { 0xE49CA1575D06A501, (void*)Pset__ZNK3sce3Xml3Dom8Document12getLastChildENS1_6NodeIdE },
 { 0x3593160D349D3D73, (void*)Pset__ZNK3sce3Xml3Dom8Document13getAttributesENS1_6NodeIdEPNS1_8NodeListE },
 { 0x008EA60E93713D89, (void*)Pset__ZNK3sce3Xml3Dom8Document13getChildNodesENS1_6NodeIdEPNS1_8NodeListE },
 { 0x237A28B5B38CFF4D, (void*)Pset__ZNK3sce3Xml3Dom8Document13getEntityTypeENS1_6NodeIdE },
 { 0x3D798B621D33175E, (void*)Pset__ZNK3sce3Xml3Dom8Document13getFirstChildENS1_6NodeIdE },
 { 0xBD6035AFD0A23E02, (void*)Pset__ZNK3sce3Xml3Dom8Document13hasAttributesENS1_6NodeIdE },
 { 0xBA52CFF9FE61D2B8, (void*)Pset__ZNK3sce3Xml3Dom8Document13hasChildNodesENS1_6NodeIdE },
 { 0x5E5CC54FC9E700C5, (void*)Pset__ZNK3sce3Xml3Dom8Document14getSkippedTextENS1_6NodeIdE },
 { 0x1C66740D3B82BEE4, (void*)Pset__ZNK3sce3Xml3Dom8Document20getElementsByTagNameENS1_6NodeIdEPKNS0_6StringEPNS1_8NodeListE },
 { 0x98E0F2682A720E73, (void*)Pset__ZNK3sce3Xml3Dom8Document7getRootEv },
 { 0xECCB18BF80F50278, (void*)Pset__ZNK3sce3Xml3Dom8Document7getTextENS1_6NodeIdE },
 { 0x6991FEDBD6D2B049, (void*)Pset__ZNK3sce3Xml3Dom8Document9getEntityENS1_6NodeIdE },
 { 0xA7421E31E9AF64AA, (void*)Pset__ZNK3sce3Xml3Dom8Document9getParentENS1_6NodeIdE },
 { 0x58FCA7E6B132D831, (void*)Pset__ZNK3sce3Xml3Dom8Document9getStatusEv },
 { 0x8DCECBDC74A5B53D, (void*)Pset__ZNK3sce3Xml3Dom8NodeList11isAvailableEv },
 { 0x43FAF25E88F87B3D, (void*)Pset__ZNK3sce3Xml3Dom8NodeList4itemEj },
 { 0x37FDAA04962FEA5C, (void*)Pset__ZNK3sce3Xml3Dom8NodeList8findItemENS1_6NodeIdE },
 { 0x66693C31BF6A350D, (void*)Pset__ZNK3sce3Xml3Dom8NodeList8findItemEPKNS0_6StringE },
 { 0xB598A82ACBB9A71B, (void*)Pset__ZNK3sce3Xml3Dom8NodeList9getLengthEv },
 { 0x55D62873D9067B20, (void*)Pset__ZNK3sce3Xml3Dom8NodeListixEj },
 { 0xC2580CF1C2E5D664, (void*)Pset__ZNK3sce3Xml4Attr11isAvailableEv },
 { 0x2A0CC16E2DC35030, (void*)Pset__ZNK3sce3Xml4Attr7getNameEv },
 { 0x40E9886A85C53628, (void*)Pset__ZNK3sce3Xml4Attr8getValueEv },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceXml[] =
{
 {"libSceXml", gSymTable_libSceXml_libSceXml },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceXml("libSceXml", gLibTable_libSceXml);