//Generated By SceModuleGenerator
#include "pset_libSceNpScore.h"


int PSET_SYSV_ABI Pset_sceNpScoreAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCensorComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCensorComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCensorCommentAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCensorCommentAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreChangeModeForOtherSaveDataOwners(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreChangeModeForOtherSaveDataOwners");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCreateNpTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCreateNpTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCreateNpTitleCtxA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCreateNpTitleCtxA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreCreateTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreCreateTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreDeleteNpTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreDeleteNpTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetBoardInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetBoardInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetBoardInfoAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetBoardInfoAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRanking(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRanking");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRankingA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRankingA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRankingAAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRankingAAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRankingAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRankingAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRankingForCrossSave(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRankingForCrossSave");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetFriendsRankingForCrossSaveAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetFriendsRankingForCrossSaveAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetGameData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetGameData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetGameDataAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetGameDataAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetGameDataByAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetGameDataByAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetGameDataByAccountIdAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetGameDataByAccountIdAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdForCrossSave(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdForCrossSave");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdForCrossSaveAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdForCrossSaveAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdPcId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdPcId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdPcIdAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdPcIdAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSave(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSave");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByNpId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByNpId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByNpIdAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByNpIdAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByNpIdPcId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByNpIdPcId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByNpIdPcIdAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByNpIdPcIdAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRange(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRange");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRangeA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRangeA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRangeAAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRangeAAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRangeAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRangeAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRangeForCrossSave(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRangeForCrossSave");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreGetRankingByRangeForCrossSaveAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreGetRankingByRangeForCrossSaveAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScorePollAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScorePollAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreRecordGameData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreRecordGameData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreRecordGameDataAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreRecordGameDataAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreRecordScore(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreRecordScore");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreRecordScoreAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreRecordScoreAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreSanitizeComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreSanitizeComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreSanitizeCommentAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreSanitizeCommentAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreSetPlayerCharacterId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreSetPlayerCharacterId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreSetThreadParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreSetThreadParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreSetTimeout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreSetTimeout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpScoreWaitAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpScoreWaitAsync");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpScore_libSceNpScore[] =
{
 { 0xD62EE498A6D7EA19,"Pset_sceNpScoreAbortRequest", (void*)Pset_sceNpScoreAbortRequest },
 { 0xD9BDD32349836222,"Pset_sceNpScoreCensorComment", (void*)Pset_sceNpScoreCensorComment },
 { 0xE1E3AF0F237F6997,"Pset_sceNpScoreCensorCommentAsync", (void*)Pset_sceNpScoreCensorCommentAsync },
 { 0x7535C2F9871E3ED3,"Pset_sceNpScoreChangeModeForOtherSaveDataOwners", (void*)Pset_sceNpScoreChangeModeForOtherSaveDataOwners },
 { 0x2A7340D53120B412,"Pset_sceNpScoreCreateNpTitleCtx", (void*)Pset_sceNpScoreCreateNpTitleCtx },
 { 0x1969D640D5D91F93,"Pset_sceNpScoreCreateNpTitleCtxA", (void*)Pset_sceNpScoreCreateNpTitleCtxA },
 { 0x816F2ACA362B51B9,"Pset_sceNpScoreCreateRequest", (void*)Pset_sceNpScoreCreateRequest },
 { 0xA96F4CD1B43F671D,"Pset_sceNpScoreCreateTitleCtx", (void*)Pset_sceNpScoreCreateTitleCtx },
 { 0x1B4A44F91342C1F9,"Pset_sceNpScoreDeleteNpTitleCtx", (void*)Pset_sceNpScoreDeleteNpTitleCtx },
 { 0x74AF3F4A061FEABE,"Pset_sceNpScoreDeleteRequest", (void*)Pset_sceNpScoreDeleteRequest },
 { 0x2E854C56B8A354E9,"Pset_sceNpScoreGetBoardInfo", (void*)Pset_sceNpScoreGetBoardInfo },
 { 0x43402F8BD91E6EC6,"Pset_sceNpScoreGetBoardInfoAsync", (void*)Pset_sceNpScoreGetBoardInfoAsync },
 { 0xF24B88CD4C3ABAD4,"Pset_sceNpScoreGetFriendsRanking", (void*)Pset_sceNpScoreGetFriendsRanking },
 { 0x80C6CE9FEFFA7970,"Pset_sceNpScoreGetFriendsRankingA", (void*)Pset_sceNpScoreGetFriendsRankingA },
 { 0xEBF1BD3B12F90CA8,"Pset_sceNpScoreGetFriendsRankingAAsync", (void*)Pset_sceNpScoreGetFriendsRankingAAsync },
 { 0xED2B8C52537B43A2,"Pset_sceNpScoreGetFriendsRankingAsync", (void*)Pset_sceNpScoreGetFriendsRankingAsync },
 { 0x02073181C79A1FC9,"Pset_sceNpScoreGetFriendsRankingForCrossSave", (void*)Pset_sceNpScoreGetFriendsRankingForCrossSave },
 { 0x9BA17BB04D474195,"Pset_sceNpScoreGetFriendsRankingForCrossSaveAsync", (void*)Pset_sceNpScoreGetFriendsRankingForCrossSaveAsync },
 { 0xCCAA15A24E851442,"Pset_sceNpScoreGetGameData", (void*)Pset_sceNpScoreGetGameData },
 { 0x2633854553DD4167,"Pset_sceNpScoreGetGameDataAsync", (void*)Pset_sceNpScoreGetGameDataAsync },
 { 0x2E6B5CF469637940,"Pset_sceNpScoreGetGameDataByAccountId", (void*)Pset_sceNpScoreGetGameDataByAccountId },
 { 0x3CFF63C7CB34E7BE,"Pset_sceNpScoreGetGameDataByAccountIdAsync", (void*)Pset_sceNpScoreGetGameDataByAccountIdAsync },
 { 0x2BDB653834D0C777,"Pset_sceNpScoreGetRankingByAccountId", (void*)Pset_sceNpScoreGetRankingByAccountId },
 { 0x751B3334DC865A4C,"Pset_sceNpScoreGetRankingByAccountIdAsync", (void*)Pset_sceNpScoreGetRankingByAccountIdAsync },
 { 0xDD86E3E04D6A36D6,"Pset_sceNpScoreGetRankingByAccountIdForCrossSave", (void*)Pset_sceNpScoreGetRankingByAccountIdForCrossSave },
 { 0x29CFB740AF3800A3,"Pset_sceNpScoreGetRankingByAccountIdForCrossSaveAsync", (void*)Pset_sceNpScoreGetRankingByAccountIdForCrossSaveAsync },
 { 0xC093D6C9C546CEBB,"Pset_sceNpScoreGetRankingByAccountIdPcId", (void*)Pset_sceNpScoreGetRankingByAccountIdPcId },
 { 0x6C55630E0C456A97,"Pset_sceNpScoreGetRankingByAccountIdPcIdAsync", (void*)Pset_sceNpScoreGetRankingByAccountIdPcIdAsync },
 { 0xA178D589E1FA6464,"Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSave", (void*)Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSave },
 { 0x9D7685D41C5BFCDC,"Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync", (void*)Pset_sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync },
 { 0xF66644828884ABA6,"Pset_sceNpScoreGetRankingByNpId", (void*)Pset_sceNpScoreGetRankingByNpId },
 { 0x45DDBB76A505655F,"Pset_sceNpScoreGetRankingByNpIdAsync", (void*)Pset_sceNpScoreGetRankingByNpIdAsync },
 { 0x1134BFB8CFEF1FD4,"Pset_sceNpScoreGetRankingByNpIdPcId", (void*)Pset_sceNpScoreGetRankingByNpIdPcId },
 { 0x16CA2E48DD3290DF,"Pset_sceNpScoreGetRankingByNpIdPcIdAsync", (void*)Pset_sceNpScoreGetRankingByNpIdPcIdAsync },
 { 0x2811F10E3CA4FE30,"Pset_sceNpScoreGetRankingByRange", (void*)Pset_sceNpScoreGetRankingByRange },
 { 0x300F6F4ADEC92266,"Pset_sceNpScoreGetRankingByRangeA", (void*)Pset_sceNpScoreGetRankingByRangeA },
 { 0xCB98DAED6234E6BB,"Pset_sceNpScoreGetRankingByRangeAAsync", (void*)Pset_sceNpScoreGetRankingByRangeAAsync },
 { 0xAD2866A971F0A101,"Pset_sceNpScoreGetRankingByRangeAsync", (void*)Pset_sceNpScoreGetRankingByRangeAsync },
 { 0x9D1A18576C9E52EC,"Pset_sceNpScoreGetRankingByRangeForCrossSave", (void*)Pset_sceNpScoreGetRankingByRangeForCrossSave },
 { 0x019E1E025183CBF4,"Pset_sceNpScoreGetRankingByRangeForCrossSaveAsync", (void*)Pset_sceNpScoreGetRankingByRangeForCrossSaveAsync },
 { 0x9B50DF351B2D9124,"Pset_sceNpScorePollAsync", (void*)Pset_sceNpScorePollAsync },
 { 0x6DCA15C1C06343D1,"Pset_sceNpScoreRecordGameData", (void*)Pset_sceNpScoreRecordGameData },
 { 0xD602F93F0633AEBC,"Pset_sceNpScoreRecordGameDataAsync", (void*)Pset_sceNpScoreRecordGameDataAsync },
 { 0xCD3D1706D82D3922,"Pset_sceNpScoreRecordScore", (void*)Pset_sceNpScoreRecordScore },
 { 0x00D26CB0FCF7998D,"Pset_sceNpScoreRecordScoreAsync", (void*)Pset_sceNpScoreRecordScoreAsync },
 { 0xAF8A00A3D8A7D130,"Pset_sceNpScoreSanitizeComment", (void*)Pset_sceNpScoreSanitizeComment },
 { 0xDD456A1897837F7D,"Pset_sceNpScoreSanitizeCommentAsync", (void*)Pset_sceNpScoreSanitizeCommentAsync },
 { 0x6F281B29D1E68E7E,"Pset_sceNpScoreSetPlayerCharacterId", (void*)Pset_sceNpScoreSetPlayerCharacterId },
 { 0xCB12BAF39F382405,"Pset_sceNpScoreSetThreadParam", (void*)Pset_sceNpScoreSetThreadParam },
 { 0x4B7C598F7E6FF19F,"Pset_sceNpScoreSetTimeout", (void*)Pset_sceNpScoreSetTimeout },
 { 0x7EA93C482EB7A755,"Pset_sceNpScoreWaitAsync", (void*)Pset_sceNpScoreWaitAsync },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpScoreCompat_libSceNpScore[] =
{
 { 0x2A7340D53120B412,"Pset_sceNpScoreCreateNpTitleCtx", (void*)Pset_sceNpScoreCreateNpTitleCtx },
 { 0xF24B88CD4C3ABAD4,"Pset_sceNpScoreGetFriendsRanking", (void*)Pset_sceNpScoreGetFriendsRanking },
 { 0xED2B8C52537B43A2,"Pset_sceNpScoreGetFriendsRankingAsync", (void*)Pset_sceNpScoreGetFriendsRankingAsync },
 { 0xCCAA15A24E851442,"Pset_sceNpScoreGetGameData", (void*)Pset_sceNpScoreGetGameData },
 { 0x2633854553DD4167,"Pset_sceNpScoreGetGameDataAsync", (void*)Pset_sceNpScoreGetGameDataAsync },
 { 0xF66644828884ABA6,"Pset_sceNpScoreGetRankingByNpId", (void*)Pset_sceNpScoreGetRankingByNpId },
 { 0x45DDBB76A505655F,"Pset_sceNpScoreGetRankingByNpIdAsync", (void*)Pset_sceNpScoreGetRankingByNpIdAsync },
 { 0x1134BFB8CFEF1FD4,"Pset_sceNpScoreGetRankingByNpIdPcId", (void*)Pset_sceNpScoreGetRankingByNpIdPcId },
 { 0x16CA2E48DD3290DF,"Pset_sceNpScoreGetRankingByNpIdPcIdAsync", (void*)Pset_sceNpScoreGetRankingByNpIdPcIdAsync },
 { 0x2811F10E3CA4FE30,"Pset_sceNpScoreGetRankingByRange", (void*)Pset_sceNpScoreGetRankingByRange },
 { 0xAD2866A971F0A101,"Pset_sceNpScoreGetRankingByRangeAsync", (void*)Pset_sceNpScoreGetRankingByRangeAsync },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceNpScore[] =
{
 {"libSceNpScore", gSymTable_libSceNpScore_libSceNpScore },
 {"libSceNpScoreCompat", gSymTable_libSceNpScoreCompat_libSceNpScore },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceNpScore("libSceNpScore", gLibTable_libSceNpScore);