//Generated By SceModuleGenerator
#include "pset_libSceNpFriendListDialog.h"


int PSET_SYSV_ABI Pset_sceNpFriendListDialogClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogGetResultA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogGetResultA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogGetStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogGetStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogOpenA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogOpenA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogTerminate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogTerminate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpFriendListDialogUpdateStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpFriendListDialogUpdateStatus");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpFriendListDialog_libSceNpFriendListDialog[] =
{
 { 0xF98D5A7071A89864, (void*)Pset_sceNpFriendListDialogClose },
 { 0x6782498570A722F6, (void*)Pset_sceNpFriendListDialogGetResult },
 { 0x84AD020A58F32666, (void*)Pset_sceNpFriendListDialogGetResultA },
 { 0xF0154FE7A24866E0, (void*)Pset_sceNpFriendListDialogGetStatus },
 { 0xD8BFD6FD9627D90A, (void*)Pset_sceNpFriendListDialogInitialize },
 { 0xCD433F446E479B27, (void*)Pset_sceNpFriendListDialogOpen },
 { 0xBCDF6C4CFEB7593F, (void*)Pset_sceNpFriendListDialogOpenA },
 { 0x10213393E2BD2F69, (void*)Pset_sceNpFriendListDialogTerminate },
 { 0x7EBC33DDECAE03AC, (void*)Pset_sceNpFriendListDialogUpdateStatus },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpFriendListDialogCompat_libSceNpFriendListDialog[] =
{
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceNpFriendListDialog[] =
{
 {"libSceNpFriendListDialog", gSymTable_libSceNpFriendListDialog_libSceNpFriendListDialog },
 {"libSceNpFriendListDialogCompat", gSymTable_libSceNpFriendListDialogCompat_libSceNpFriendListDialog },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceNpFriendListDialog("libSceNpFriendListDialog", gLibTable_libSceNpFriendListDialog);