//Generated By SceModuleGenerator
#include "pset_libSceNpUtility.h"


int PSET_SYSV_ABI Pset_sceNpAppInfoIntAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckAvailability(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckAvailability");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckAvailabilityA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckAvailabilityA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckAvailabilityAll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckAvailabilityAll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckAvailabilityAllA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckAvailabilityAllA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckServiceAvailability(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckServiceAvailability");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckServiceAvailabilityA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckServiceAvailabilityA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckServiceAvailabilityAll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckServiceAvailabilityAll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCheckServiceAvailabilityAllA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCheckServiceAvailabilityAllA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntDestroyRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntDestroyRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntFinalize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntFinalize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppInfoIntInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppInfoIntInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntDestroyRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntDestroyRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntFinalize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntFinalize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdNum(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdNum");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpAppLaunchLinkIntInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpAppLaunchLinkIntInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestAbort(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestAbort");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestDownloadOnlyInitStart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestDownloadOnlyInitStart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestGetStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestGetStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestInitStart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestInitStart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestShutdown(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestShutdown");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestShutdownInt(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestShutdownInt");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpBandwidthTestUploadOnlyInitStart(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpBandwidthTestUploadOnlyInitStart");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupCreateAsyncRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupCreateAsyncRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupCreateTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupCreateTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupCreateTitleCtxA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupCreateTitleCtxA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupDeleteTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupDeleteTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetCensorComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetCensorComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetConvertJidToNpId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetConvertJidToNpId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetConvertNpIdToJid(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetConvertNpIdToJid");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetCreateTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetCreateTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetDeleteTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetDeleteTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetInitWithFunctionPointer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetInitWithFunctionPointer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetInitWithMemoryPool(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetInitWithMemoryPool");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetIsInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetIsInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetNpId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetNpId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetSanitizeComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetSanitizeComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetSetTimeout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetSetTimeout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNetTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNetTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupNpId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupNpId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupPollAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupPollAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupSetTimeout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupSetTimeout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpLookupWaitAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpLookupWaitAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntDestroyRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntDestroyRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntFinalize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntFinalize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntGetServiceAvailability(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntGetServiceAvailability");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntGetServiceAvailabilityA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntGetServiceAvailabilityA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceChecker2IntIsSetServiceType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceChecker2IntIsSetServiceType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntDestroyRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntDestroyRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntFinalize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntFinalize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntGetAvailability(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntGetAvailability");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntGetAvailabilityList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntGetAvailabilityList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpServiceCheckerIntIsCached(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpServiceCheckerIntIsCached");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpTitleMetadataIntAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpTitleMetadataIntAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpTitleMetadataIntCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpTitleMetadataIntCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpTitleMetadataIntDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpTitleMetadataIntDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpTitleMetadataIntGetInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpTitleMetadataIntGetInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpTitleMetadataIntGetNpTitleId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpTitleMetadataIntGetNpTitleId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpUtilityInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpUtilityInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpUtilityTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpUtilityTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterCensorComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterCensorComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterCreateAsyncRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterCreateAsyncRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterCreateTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterCreateTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterCreateTitleCtxA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterCreateTitleCtxA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterDeleteTitleCtx(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterDeleteTitleCtx");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterPollAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterPollAsync");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterSanitizeComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterSanitizeComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterSetTimeout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterSetTimeout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceNpWordFilterWaitAsync(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceNpWordFilterWaitAsync");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpUtility_libSceNpUtility[] =
{
 { 0x63BF7B4B0F7F8EA6, (void*)Pset_sceNpAppInfoIntAbortRequest },
 { 0x514848F8850CADC1, (void*)Pset_sceNpAppInfoIntCheckAvailability },
 { 0x012A279F096DC049, (void*)Pset_sceNpAppInfoIntCheckAvailabilityA },
 { 0x8D7C74FB659DD6AF, (void*)Pset_sceNpAppInfoIntCheckAvailabilityAll },
 { 0x7F53B043B8DDAA7D, (void*)Pset_sceNpAppInfoIntCheckAvailabilityAllA },
 { 0xD667C3065E340E6B, (void*)Pset_sceNpAppInfoIntCheckServiceAvailability },
 { 0x5C0983A30010845B, (void*)Pset_sceNpAppInfoIntCheckServiceAvailabilityA },
 { 0x05A8A115AF0B070D, (void*)Pset_sceNpAppInfoIntCheckServiceAvailabilityAll },
 { 0x25CA9D2A2761B8AD, (void*)Pset_sceNpAppInfoIntCheckServiceAvailabilityAllA },
 { 0x717A72112A38F64A, (void*)Pset_sceNpAppInfoIntCreateRequest },
 { 0xA5182906D1F1F0FE, (void*)Pset_sceNpAppInfoIntDestroyRequest },
 { 0xB3DFB3A0A13C7010, (void*)Pset_sceNpAppInfoIntFinalize },
 { 0x97A0E5FB6CE5B9AD, (void*)Pset_sceNpAppInfoIntInitialize },
 { 0x01057803C605C78E, (void*)Pset_sceNpAppLaunchLinkIntAbortRequest },
 { 0xF588701B80E1C2D5, (void*)Pset_sceNpAppLaunchLinkIntCreateRequest },
 { 0xFFC5A7E182992CC3, (void*)Pset_sceNpAppLaunchLinkIntDestroyRequest },
 { 0x4E742A26CC9E939A, (void*)Pset_sceNpAppLaunchLinkIntFinalize },
 { 0x181EC5864E5251A0, (void*)Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdList },
 { 0x5F87A53A8880B41E, (void*)Pset_sceNpAppLaunchLinkIntGetCompatibleTitleIdNum },
 { 0xD45E32C1E428AA08, (void*)Pset_sceNpAppLaunchLinkIntInitialize },
 { 0x92F74C178F260776, (void*)Pset_sceNpBandwidthTestAbort },
 { 0x0D6596D3631B29D9, (void*)Pset_sceNpBandwidthTestDownloadOnlyInitStart },
 { 0x05821918A9BA6CEE, (void*)Pset_sceNpBandwidthTestGetStatus },
 { 0x8E4B70C37C895E77, (void*)Pset_sceNpBandwidthTestInitStart },
 { 0xA4BAF57C4412D73F, (void*)Pset_sceNpBandwidthTestShutdown },
 { 0x3D2A6DC6D2556EFE, (void*)Pset_sceNpBandwidthTestShutdownInt },
 { 0xA173B2AB13BC757F, (void*)Pset_sceNpBandwidthTestUploadOnlyInitStart },
 { 0x798CF8BF951E93D5, (void*)Pset_sceNpLookupAbortRequest },
 { 0x240E3EB12DFD18CB, (void*)Pset_sceNpLookupCreateAsyncRequest },
 { 0x890AFD5313C7505B, (void*)Pset_sceNpLookupCreateRequest },
 { 0xF39DF743E2D4EC44, (void*)Pset_sceNpLookupCreateTitleCtx },
 { 0xBD3F7186A3CEEBED, (void*)Pset_sceNpLookupCreateTitleCtxA },
 { 0xC0B6B1721BC41279, (void*)Pset_sceNpLookupDeleteRequest },
 { 0x9ADA832BDCE4A081, (void*)Pset_sceNpLookupDeleteTitleCtx },
 { 0xD4EF7A9AE3F38605, (void*)Pset_sceNpLookupNetAbortRequest },
 { 0x374885D7CD158C69, (void*)Pset_sceNpLookupNetCensorComment },
 { 0x508E6DE91C7AB392, (void*)Pset_sceNpLookupNetConvertJidToNpId },
 { 0x89E44E617E2FB299, (void*)Pset_sceNpLookupNetConvertNpIdToJid },
 { 0x294211B24BBB10F9, (void*)Pset_sceNpLookupNetCreateRequest },
 { 0xF033C474987D4641, (void*)Pset_sceNpLookupNetCreateTitleCtx },
 { 0x1CBFEF7A7AD17274, (void*)Pset_sceNpLookupNetDeleteRequest },
 { 0x771A54C7BCFD4AD6, (void*)Pset_sceNpLookupNetDeleteTitleCtx },
 { 0xCD5644F9F0218056, (void*)Pset_sceNpLookupNetInit },
 { 0x0E2524EBF9AAFFFD, (void*)Pset_sceNpLookupNetInitWithFunctionPointer },
 { 0x7299F065E548ABC1, (void*)Pset_sceNpLookupNetInitWithMemoryPool },
 { 0x6579538FD451085A, (void*)Pset_sceNpLookupNetIsInit },
 { 0xDA7115985895E8E2, (void*)Pset_sceNpLookupNetNpId },
 { 0x8C91F63FB280E175, (void*)Pset_sceNpLookupNetSanitizeComment },
 { 0x356B5FEFB5825C9B, (void*)Pset_sceNpLookupNetSetTimeout },
 { 0x0DB779058D108C6D, (void*)Pset_sceNpLookupNetTerm },
 { 0x4FAB6733552D8B88, (void*)Pset_sceNpLookupNpId },
 { 0x578115AEBB87BB2F, (void*)Pset_sceNpLookupPollAsync },
 { 0xD0C57BD963BB577E, (void*)Pset_sceNpLookupSetTimeout },
 { 0x617F5D02EB3A6DA1, (void*)Pset_sceNpLookupWaitAsync },
 { 0x2AAF9FB51F4B1E51, (void*)Pset_sceNpServiceChecker2IntAbortRequest },
 { 0x206D4A77E93A537B, (void*)Pset_sceNpServiceChecker2IntCreateRequest },
 { 0x841B01B30AC08863, (void*)Pset_sceNpServiceChecker2IntDestroyRequest },
 { 0x72F66B9A54A5C27F, (void*)Pset_sceNpServiceChecker2IntFinalize },
 { 0x69480B09BDE948EA, (void*)Pset_sceNpServiceChecker2IntGetServiceAvailability },
 { 0x629DB22B96176FBF, (void*)Pset_sceNpServiceChecker2IntGetServiceAvailabilityA },
 { 0xFC07E2FC9A1167F5, (void*)Pset_sceNpServiceChecker2IntInitialize },
 { 0xBA406AEB638F0180, (void*)Pset_sceNpServiceChecker2IntIsSetServiceType },
 { 0xC1A784CF0C187D96, (void*)Pset_sceNpServiceCheckerIntAbortRequest },
 { 0x60B5EDFEF1B0E0A8, (void*)Pset_sceNpServiceCheckerIntCreateRequest },
 { 0xF3965677359881AB, (void*)Pset_sceNpServiceCheckerIntDestroyRequest },
 { 0x2D2437C40A44A316, (void*)Pset_sceNpServiceCheckerIntFinalize },
 { 0xC085F4D01AEC9287, (void*)Pset_sceNpServiceCheckerIntGetAvailability },
 { 0x3233857705D844A6, (void*)Pset_sceNpServiceCheckerIntGetAvailabilityList },
 { 0xAD3F58939E491A1A, (void*)Pset_sceNpServiceCheckerIntInitialize },
 { 0x6B3EDF97DB273AAC, (void*)Pset_sceNpServiceCheckerIntIsCached },
 { 0xADE8B89233928B27, (void*)Pset_sceNpTitleMetadataIntAbortRequest },
 { 0x0355D0B252C003F6, (void*)Pset_sceNpTitleMetadataIntCreateRequest },
 { 0xB729EF6BFF63AED2, (void*)Pset_sceNpTitleMetadataIntDeleteRequest },
 { 0xFCC703857F2D9D61, (void*)Pset_sceNpTitleMetadataIntGetInfo },
 { 0x2D71E4AC2578E77A, (void*)Pset_sceNpTitleMetadataIntGetNpTitleId },
 { 0x5BA896C3C69442D0, (void*)Pset_sceNpUtilityInit },
 { 0x339272A3D4CA60F2, (void*)Pset_sceNpUtilityTerm },
 { 0xAC038EA830310489, (void*)Pset_sceNpWordFilterAbortRequest },
 { 0xD5D32776A2FF4201, (void*)Pset_sceNpWordFilterCensorComment },
 { 0x20407EBE056841BC, (void*)Pset_sceNpWordFilterCreateAsyncRequest },
 { 0x882AB9C56E4A416E, (void*)Pset_sceNpWordFilterCreateRequest },
 { 0xAFD0602343DF2598, (void*)Pset_sceNpWordFilterCreateTitleCtx },
 { 0xEA9F63BE58EEBECC, (void*)Pset_sceNpWordFilterCreateTitleCtxA },
 { 0x3D8152D47EF46C3B, (void*)Pset_sceNpWordFilterDeleteRequest },
 { 0xB743F9CF9CAE14F0, (void*)Pset_sceNpWordFilterDeleteTitleCtx },
 { 0xBABE524A1C86D1D9, (void*)Pset_sceNpWordFilterPollAsync },
 { 0x263E2692914EDA01, (void*)Pset_sceNpWordFilterSanitizeComment },
 { 0x15AE1D5568267DF9, (void*)Pset_sceNpWordFilterSetTimeout },
 { 0xF3B8AF5A3E722B38, (void*)Pset_sceNpWordFilterWaitAsync },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceNpUtilityCompat_libSceNpUtility[] =
{
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceNpUtility[] =
{
 {"libSceNpUtility", gSymTable_libSceNpUtility_libSceNpUtility },
 {"libSceNpUtilityCompat", gSymTable_libSceNpUtilityCompat_libSceNpUtility },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceNpUtility("libSceNpUtility", gLibTable_libSceNpUtility);