//Generated By SceModuleGenerator
#include "pset_libSceInvitationDialog.h"


int PSET_SYSV_ABI Pset_sceInvitationDialogClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogGetResult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogGetResult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogGetResultA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogGetResultA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogGetStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogGetStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogOpenA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogOpenA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogTerminate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogTerminate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceInvitationDialogUpdateStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceInvitationDialogUpdateStatus");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceInvitationDialog_libSceInvitationDialog[] =
{
 { 0x596B422F99738BB6, (void*)Pset_sceInvitationDialogClose },
 { 0xF17291EB06BAE224, (void*)Pset_sceInvitationDialogGetResult },
 { 0x5AEB9486E28EC704, (void*)Pset_sceInvitationDialogGetResultA },
 { 0x12217DD980CD1D10, (void*)Pset_sceInvitationDialogGetStatus },
 { 0x5EF039292E7AC1CB, (void*)Pset_sceInvitationDialogInitialize },
 { 0xD335341BEC2254B0, (void*)Pset_sceInvitationDialogOpen },
 { 0xB00C5B1E10163173, (void*)Pset_sceInvitationDialogOpenA },
 { 0x07A1D526D0D8C441, (void*)Pset_sceInvitationDialogTerminate },
 { 0xF7E83D88EABEEE48, (void*)Pset_sceInvitationDialogUpdateStatus },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceInvitationDialogCompat_libSceInvitationDialog[] =
{
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceInvitationDialog[] =
{
 {"libSceInvitationDialog", gSymTable_libSceInvitationDialog_libSceInvitationDialog },
 {"libSceInvitationDialogCompat", gSymTable_libSceInvitationDialogCompat_libSceInvitationDialog },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceInvitationDialog("libSceInvitationDialog", gLibTable_libSceInvitationDialog);