//Generated By SceModuleGenerator
#include "pset_libSceVideoOut.h"


int PSET_SYSV_ABI Pset_sceDbgVideoOutAddOutputModeVr60Privilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceDbgVideoOutAddOutputModeVr60Privilege");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceDbgVideoOutAddProcessAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceDbgVideoOutAddProcessAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceDbgVideoOutRemoveProcessAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceDbgVideoOutRemoveProcessAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddBufferAnisoPrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddBufferAnisoPrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc87DE0FA368680D98(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc87DE0FA368680D98");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddBuffer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddBuffer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddBuffer4k2kPrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddBuffer4k2kPrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddBufferYccPrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddBufferYccPrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddDisplayPositionEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddDisplayPositionEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddDriver(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddDriver");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddFlipEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddFlipEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddPreVblankStartEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddPreVblankStartEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddS3dHmdPrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddS3dHmdPrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddSetModeEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddSetModeEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddStereoBuffer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddStereoBuffer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddVblankEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddVblankEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAdjustColor_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAdjustColor_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutColorSettingsSetGamma_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutColorSettingsSetGamma_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutConfigureOptionsInitialize_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutConfigureOptionsInitialize_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutConfigureOutputMode_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutConfigureOutputMode_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutConfigureOutputModeEx_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutConfigureOutputModeEx_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutControlHdcpEncryption(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutControlHdcpEncryption");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorDisable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorDisable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorEnable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorEnable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorIsUpdatePending(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorIsUpdatePending");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorSet2xMagnify(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorSet2xMagnify");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorSetHotSpot(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorSetHotSpot");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorSetImageAddress(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorSetImageAddress");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorSetPosition(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorSetPosition");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCursorSetPositionStereo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCursorSetPositionStereo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutCurveSamplePointsCalc_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutCurveSamplePointsCalc_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeleteDisplayPositionEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeleteDisplayPositionEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeleteDriver(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeleteDriver");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeleteFlipEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeleteFlipEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeletePreVblankStartEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeletePreVblankStartEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeleteSetModeEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeleteSetModeEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDeleteVblankEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDeleteVblankEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverAddEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverAddEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverDecrementBufferLabel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverDecrementBufferLabel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverDeleteEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverDeleteEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverGetBufferLabelAddress(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverGetBufferLabelAddress");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverGetEopHandle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverGetEopHandle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverGetFinishedEopHandle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverGetFinishedEopHandle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverGetLatestEopHandle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverGetLatestEopHandle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverIncrementBufferLabel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverIncrementBufferLabel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverResetBufferLabel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverResetBufferLabel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutDriverTriggerEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutDriverTriggerEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetBufferInformation(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetBufferInformation");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetBufferLabelAddress(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetBufferLabelAddress");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetCoredumpOutputMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetCoredumpOutputMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetCurrentOutputMode_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetCurrentOutputMode_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetDeviceCapabilityInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetDeviceCapabilityInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetDeviceInfoEx_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetDeviceInfoEx_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetDeviceInfoExOts_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetDeviceInfoExOts_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetEventCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetEventCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetEventData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetEventData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetEventId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetEventId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetFlipStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetFlipStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetHdmiKsvList_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetHdmiKsvList_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetHdmiMonitorInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetHdmiMonitorInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetHdmiMonitorInfoNoMask_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetHdmiMonitorInfoNoMask_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetPortStatusInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetPortStatusInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetPortStatusInfoByBusSpecifier_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetPortStatusInfoByBusSpecifier_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetResolutionStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetResolutionStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetStatusForWebcore(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetStatusForWebcore");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetVblankStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetVblankStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetVideoOutModeByBusSpecifier_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetVideoOutModeByBusSpecifier_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutIsFlipPending(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutIsFlipPending");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutLockBuffer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutLockBuffer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutModeSetAny_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutModeSetAny_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutOpen(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutOpen");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRazorAddCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRazorAddCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRazorRecallCallbacks(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRazorRecallCallbacks");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRazorRemoveCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRazorRemoveCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRegisterBufferAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRegisterBufferAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRegisterBuffers(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRegisterBuffers");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRegisterStereoBuffers(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRegisterStereoBuffers");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutRemoveBuffer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutRemoveBuffer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetBlankAfterResume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetBlankAfterResume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetBufferAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetBufferAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetDisplayEventPosition(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetDisplayEventPosition");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetFlipRate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetFlipRate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetGamutMetadata_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetGamutMetadata_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetToneMap_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetToneMap_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSetWindowModeMargins(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSetWindowModeMargins");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSubmitChangeBufferAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSubmitChangeBufferAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSubmitEopFlip(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSubmitEopFlip");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSubmitFlip(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSubmitFlip");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysAddSetModeEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysAddSetModeEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysAddVblankEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysAddVblankEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysClose(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysClose");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysConfigureOutputMode_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysConfigureOutputMode_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorDisable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorDisable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorEnable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorEnable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorIsUpdatePending(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorIsUpdatePending");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorObtain(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorObtain");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorRelease(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorRelease");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysCursorSetPosition(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysCursorSetPosition");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysDeleteVblankEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysDeleteVblankEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetColorConversionStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetColorConversionStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetCurrentOutputMode_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetCurrentOutputMode_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetDeviceCapabilityInfoByBusSpecifier_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetDeviceCapabilityInfoByBusSpecifier_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetFlipStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetFlipStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetMonitorInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetMonitorInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetPortStatusInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetPortStatusInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetPortStatusInfoByBusSpecifier_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetPortStatusInfoByBusSpecifier_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetResolutionStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetResolutionStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysGetVblankStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysGetVblankStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysIsSupportedByMonitorInfo_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysIsSupportedByMonitorInfo_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysReadCrc(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysReadCrc");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysReadCrc64(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysReadCrc64");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysResetAtGpuReset(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysResetAtGpuReset");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysResetZoomBuffers(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysResetZoomBuffers");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetBlackLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetBlackLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetDcePipeMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetDcePipeMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetDimmer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetDimmer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetDisplayParameters(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetDisplayParameters");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetInvertedColors(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetInvertedColors");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetOutputCsc(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetOutputCsc");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetOverscanRatio(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetOverscanRatio");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSetZoomBuffers(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSetZoomBuffers");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysSubmitSubWindowLayout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysSubmitSubWindowLayout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysUpdateDisplayParameter_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysUpdateDisplayParameter_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysUpdatePrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysUpdatePrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysUpdateRenderingMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysUpdateRenderingMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutSysUpdateScalerParameters(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutSysUpdateScalerParameters");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutUnlockBuffer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutUnlockBuffer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutUnregisterBufferAttribute(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutUnregisterBufferAttribute");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutUnregisterBuffers(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutUnregisterBuffers");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutWaitVblank(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutWaitVblank");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc124ED74010241580(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc124ED74010241580");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc2438D6A18553BDD9(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc2438D6A18553BDD9");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc3389533D3C6878DD(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc3389533D3C6878DD");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc3F96B7D8EBA56509(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc3F96B7D8EBA56509");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc94C92412FE1A6876(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc94C92412FE1A6876");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncBD73297BB32EADF7(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncBD73297BB32EADF7");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncC0A269161093AD7D(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncC0A269161093AD7D");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncC192387E6509325C(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncC192387E6509325C");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncFF9008114F7ED758(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncFF9008114F7ED758");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAdjustColor2_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAdjustColor2_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutGetHdmiRawEdid_(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutGetHdmiRawEdid_");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceVideoOutAddBufferHdrPrivilege(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceVideoOutAddBufferHdrPrivilege");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncDF1AD257C5341EC8(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncDF1AD257C5341EC8");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceDbgVideoOut_libSceVideoOut[] =
{
 { 0xBFE0914A9890C953, (void*)Pset_sceDbgVideoOutAddOutputModeVr60Privilege },
 { 0xD1E6691B5E88FCFB, (void*)Pset_sceDbgVideoOutAddProcessAttribute },
 { 0x808F636C6CAB259A, (void*)Pset_sceDbgVideoOutRemoveProcessAttribute },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutAniso_libSceVideoOut[] =
{
 { 0x966FB5A3258AC32D, (void*)Pset_sceVideoOutAddBufferAnisoPrivilege },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceDbgVideoOutSub4k_libSceVideoOut[] =
{
 { 0x87DE0FA368680D98, (void*)NullNameFunc87DE0FA368680D98 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOut_libSceVideoOut[] =
{
 { 0xE22CBD846F43BB5B, (void*)Pset_sceVideoOutAddBuffer },
 { 0xB70AD26A867D709B, (void*)Pset_sceVideoOutAddBuffer4k2kPrivilege },
 { 0x0F7B3C0E8127B91E, (void*)Pset_sceVideoOutAddBufferYccPrivilege },
 { 0x0B16F6C3CDADEE5C, (void*)Pset_sceVideoOutAddDisplayPositionEvent },
 { 0x1EDC127781F64F0B, (void*)Pset_sceVideoOutAddDriver },
 { 0x1D7CE32BDC88DF49, (void*)Pset_sceVideoOutAddFlipEvent },
 { 0x91E8A9925174A4C6, (void*)Pset_sceVideoOutAddPreVblankStartEvent },
 { 0x893F9A15CCC0EDA9, (void*)Pset_sceVideoOutAddS3dHmdPrivilege },
 { 0x023B6515AD87470B, (void*)Pset_sceVideoOutAddSetModeEvent },
 { 0x031D50B370A6F794, (void*)Pset_sceVideoOutAddStereoBuffer },
 { 0x5EBBBDDB01C94668, (void*)Pset_sceVideoOutAddVblankEvent },
 { 0xA6FF42239542F91D, (void*)Pset_sceVideoOutAdjustColor_ },
 { 0xBAAB951F8FC3BBBF, (void*)Pset_sceVideoOutClose },
 { 0x0D886159B2527918, (void*)Pset_sceVideoOutColorSettingsSetGamma_ },
 { 0x92D3FD8F57CDFF31, (void*)Pset_sceVideoOutConfigureOptionsInitialize_ },
 { 0x3756C4A09E12470E, (void*)Pset_sceVideoOutConfigureOutputMode_ },
 { 0x950879E50F035008, (void*)Pset_sceVideoOutConfigureOutputModeEx_ },
 { 0xFE06293289E9C363, (void*)Pset_sceVideoOutConfigureOutputModeExSubmitDoneUnsafe_ },
 { 0x33F264463ED7F8DA, (void*)Pset_sceVideoOutControlHdcpEncryption },
 { 0x7C43C4C1139D0B03, (void*)Pset_sceVideoOutCursorDisable },
 { 0x50F656087F2A4CCE, (void*)Pset_sceVideoOutCursorEnable },
 { 0x1E26CEB5ECF34FA3, (void*)Pset_sceVideoOutCursorIsUpdatePending },
 { 0x49EFD9B3A9281B39, (void*)Pset_sceVideoOutCursorSet2xMagnify },
 { 0x8EBE767F8E4E9568, (void*)Pset_sceVideoOutCursorSetHotSpot },
 { 0xBBFF5B856400A6AF, (void*)Pset_sceVideoOutCursorSetImageAddress },
 { 0x375EC02BCF0D743D, (void*)Pset_sceVideoOutCursorSetPosition },
 { 0xEF7E467D53BDBF6B, (void*)Pset_sceVideoOutCursorSetPositionStereo },
 { 0x91ACC14573EA47B7, (void*)Pset_sceVideoOutCurveSamplePointsCalc_ },
 { 0x81B27C4315CE47A8, (void*)Pset_sceVideoOutDeleteDisplayPositionEvent },
 { 0x280E75E640F9AC06, (void*)Pset_sceVideoOutDeleteDriver },
 { 0xFCECE7D05D401518, (void*)Pset_sceVideoOutDeleteFlipEvent },
 { 0x7A5590F6F11117F4, (void*)Pset_sceVideoOutDeletePreVblankStartEvent },
 { 0x7D70929034E92458, (void*)Pset_sceVideoOutDeleteSetModeEvent },
 { 0xA0D3909F79275BAB, (void*)Pset_sceVideoOutDeleteVblankEvent },
 { 0xA1E36D766BD5E082, (void*)Pset_sceVideoOutDriverAddEvent },
 { 0xD231896CD4E9495E, (void*)Pset_sceVideoOutDriverDecrementBufferLabel },
 { 0x94E47E368B3E25EF, (void*)Pset_sceVideoOutDriverDeleteEvent },
 { 0x346C84979693E1F7, (void*)Pset_sceVideoOutDriverGetBufferLabelAddress },
 { 0x3F56C81E881AE231, (void*)Pset_sceVideoOutDriverGetEopHandle },
 { 0x1BAA5E4920CFE220, (void*)Pset_sceVideoOutDriverGetFinishedEopHandle },
 { 0x18BF3EDD11D6E6F9, (void*)Pset_sceVideoOutDriverGetLatestEopHandle },
 { 0x66DC786F62E14439, (void*)Pset_sceVideoOutDriverIncrementBufferLabel },
 { 0xB280088ECA6076DF, (void*)Pset_sceVideoOutDriverResetBufferLabel },
 { 0x3879E792B51C4A13, (void*)Pset_sceVideoOutDriverTriggerEvent },
 { 0xE55F181B1F60D140, (void*)Pset_sceVideoOutGetBufferInformation },
 { 0x39C4326D07A31C46, (void*)Pset_sceVideoOutGetBufferLabelAddress },
 { 0x219C364C836273ED, (void*)Pset_sceVideoOutGetCoredumpOutputMode },
 { 0x5B489001B19A4C18, (void*)Pset_sceVideoOutGetCurrentOutputMode_ },
 { 0x90654B73786D404F, (void*)Pset_sceVideoOutGetDeviceCapabilityInfo_ },
 { 0x93A24B406B8F1180, (void*)Pset_sceVideoOutGetDeviceInfoEx_ },
 { 0xA7B155FE653A10CD, (void*)Pset_sceVideoOutGetDeviceInfoExOts_ },
 { 0x32DE101C793190E7, (void*)Pset_sceVideoOutGetEventCount },
 { 0xAD651370A7645334, (void*)Pset_sceVideoOutGetEventData },
 { 0x536249B52A8D2992, (void*)Pset_sceVideoOutGetEventId },
 { 0x49B537770A7CD254, (void*)Pset_sceVideoOutGetFlipStatus },
 { 0x859BF3432D952CA6, (void*)Pset_sceVideoOutGetHdmiKsvList_ },
 { 0xF979439EE9AF2D50, (void*)Pset_sceVideoOutGetHdmiMonitorInfo_ },
 { 0xE36D5CAFEFF932EB, (void*)Pset_sceVideoOutGetHdmiMonitorInfoNoMask_ },
 { 0x483A0F9BBDED3B22, (void*)Pset_sceVideoOutGetPortStatusInfo_ },
 { 0xE133D6DC7D9FFE53, (void*)Pset_sceVideoOutGetPortStatusInfoByBusSpecifier_ },
 { 0xEA43E78F9D53EB66, (void*)Pset_sceVideoOutGetResolutionStatus },
 { 0xFAD076F0252BF56D, (void*)Pset_sceVideoOutGetStatusForWebcore },
 { 0xD456412B2F0778D5, (void*)Pset_sceVideoOutGetVblankStatus },
 { 0x51ACEB345CD93D15, (void*)Pset_sceVideoOutGetVideoOutModeByBusSpecifier_ },
 { 0x2828A38E2837946A, (void*)Pset_sceVideoOutHdmiMonitorInfoIsSupportedHdcpVersion_ },
 { 0x58166B51A418F845, (void*)Pset_sceVideoOutHdmiMonitorInfoIsSupportedVideoOutMode_ },
 { 0xCE05E27C74FD12B6, (void*)Pset_sceVideoOutIsFlipPending },
 { 0xEE27D9171589F50E, (void*)Pset_sceVideoOutLockBuffer },
 { 0xA63903B20C658BA7, (void*)Pset_sceVideoOutModeSetAny_ },
 { 0x529DFA3D393AF3B1, (void*)Pset_sceVideoOutOpen },
 { 0x657EC2EFDB8EBA35, (void*)Pset_sceVideoOutRazorAddCallback },
 { 0x84671392CFEAA885, (void*)Pset_sceVideoOutRazorRecallCallbacks },
 { 0xCD40D6EE42057252, (void*)Pset_sceVideoOutRazorRemoveCallback },
 { 0x1094227E33A9F2CE, (void*)Pset_sceVideoOutRegisterBufferAttribute },
 { 0xC37058FAD0048906, (void*)Pset_sceVideoOutRegisterBuffers },
 { 0x9424C23A88116E4D, (void*)Pset_sceVideoOutRegisterStereoBuffers },
 { 0x1FCB5E2E7B46916B, (void*)Pset_sceVideoOutRemoveBuffer },
 { 0xCC82F2F2DFB96CFA, (void*)Pset_sceVideoOutSetBlankAfterResume },
 { 0x8BAFEC47DD56B7FE, (void*)Pset_sceVideoOutSetBufferAttribute },
 { 0xD7C34F8AF03F6F27, (void*)Pset_sceVideoOutSetDisplayEventPosition },
 { 0x0818AEE26084D430, (void*)Pset_sceVideoOutSetFlipRate },
 { 0x7A66B20FD2C762C7, (void*)Pset_sceVideoOutSetGamutMetadata_ },
 { 0x0B1533DE7534E8D1, (void*)Pset_sceVideoOutSetToneMap_ },
 { 0x313C71ACE09E4A28, (void*)Pset_sceVideoOutSetWindowModeMargins },
 { 0x20E7601E508653F9, (void*)Pset_sceVideoOutSubmitChangeBufferAttribute },
 { 0x8FCC65FBDD80D2AE, (void*)Pset_sceVideoOutSubmitEopFlip },
 { 0x538E8DC0E889A72B, (void*)Pset_sceVideoOutSubmitFlip },
 { 0x5FC14DFF9364FF21, (void*)Pset_sceVideoOutSysAddSetModeEvent },
 { 0x124F9547895C2502, (void*)Pset_sceVideoOutSysAddVblankEvent },
 { 0x7486FD2ECAE99103, (void*)Pset_sceVideoOutSysClose },
 { 0xAC10C484980CAEE6, (void*)Pset_sceVideoOutSysConfigureOutputMode_ },
 { 0xE8BD3F039A62B9D4, (void*)Pset_sceVideoOutSysCursorDisable },
 { 0xC7087218F6645BAC, (void*)Pset_sceVideoOutSysCursorEnable },
 { 0x7A4C0C07F16DAB5F, (void*)Pset_sceVideoOutSysCursorIsUpdatePending },
 { 0xF9EA54FAB80E6F2C, (void*)Pset_sceVideoOutSysCursorObtain },
 { 0x412993DDAB6D8958, (void*)Pset_sceVideoOutSysCursorRelease },
 { 0x7D98017A21AA13E7, (void*)Pset_sceVideoOutSysCursorSetPosition },
 { 0x8B0B09740642837E, (void*)Pset_sceVideoOutSysDeleteVblankEvent },
 { 0x2293214675602545, (void*)Pset_sceVideoOutSysGetColorConversionStatus },
 { 0x9571CC01CF578F3A, (void*)Pset_sceVideoOutSysGetCurrentOutputMode_ },
 { 0x3D871934B0080675, (void*)Pset_sceVideoOutSysGetDeviceCapabilityInfoByBusSpecifier_ },
 { 0xDB5B12F04538E5CC, (void*)Pset_sceVideoOutSysGetFlipStatus },
 { 0xBCC2D6B897241AFD, (void*)Pset_sceVideoOutSysGetMonitorInfo_ },
 { 0xD4E516D7ADE233EE, (void*)Pset_sceVideoOutSysGetPortStatusInfo_ },
 { 0x86604187F2094B39, (void*)Pset_sceVideoOutSysGetPortStatusInfoByBusSpecifier_ },
 { 0xF171A28C4A13844D, (void*)Pset_sceVideoOutSysGetResolutionStatus },
 { 0x7750234F6B99267D, (void*)Pset_sceVideoOutSysGetVblankStatus },
 { 0x99FC4496BEFD3BB4, (void*)Pset_sceVideoOutSysIsSupportedByMonitorInfo_ },
 { 0x13C0BAD3CFE91678, (void*)Pset_sceVideoOutSysReadCrc },
 { 0x781BE868BC1F0414, (void*)Pset_sceVideoOutSysReadCrc64 },
 { 0x76373C7CECCE5F19, (void*)Pset_sceVideoOutSysResetAtGpuReset },
 { 0x1FD153B5226E2B76, (void*)Pset_sceVideoOutSysResetZoomBuffers },
 { 0xD8A5BD5673CC5834, (void*)Pset_sceVideoOutSysSetBlackLevel },
 { 0x8EF3DEAF8873F945, (void*)Pset_sceVideoOutSysSetDcePipeMode },
 { 0x38E17460EEF71930, (void*)Pset_sceVideoOutSysSetDimmer },
 { 0x159A024132FC474E, (void*)Pset_sceVideoOutSysSetDisplayParameters },
 { 0xC388A73F47CAB832, (void*)Pset_sceVideoOutSysSetInvertedColors },
 { 0xFA56E4F119F2BE61, (void*)Pset_sceVideoOutSysSetOutputCsc },
 { 0x9CC6C0A88D6DCBCC, (void*)Pset_sceVideoOutSysSetOverscanRatio },
 { 0x7D7F64FBE4F3B909, (void*)Pset_sceVideoOutSysSetZoomBuffers },
 { 0x749A38DDED635683, (void*)Pset_sceVideoOutSysSubmitSubWindowLayout },
 { 0x76D98FC71544ACAD, (void*)Pset_sceVideoOutSysUpdateDisplayParameter_ },
 { 0x265F75021C4A734C, (void*)Pset_sceVideoOutSysUpdatePrivilege },
 { 0xE06DFB10830C0FE4, (void*)Pset_sceVideoOutSysUpdateRenderingMode },
 { 0x5E3AA634B1B22CE8, (void*)Pset_sceVideoOutSysUpdateScalerParameters },
 { 0x6A68219C0FC4BF9B, (void*)Pset_sceVideoOutUnlockBuffer },
 { 0x491412A4FE102B95, (void*)Pset_sceVideoOutUnregisterBufferAttribute },
 { 0x379283B642238C9E, (void*)Pset_sceVideoOutUnregisterBuffers },
 { 0x8FA45A01495A2EFD, (void*)Pset_sceVideoOutWaitVblank },
 { 0x124ED74010241580, (void*)NullNameFunc124ED74010241580 },
 { 0x2438D6A18553BDD9, (void*)NullNameFunc2438D6A18553BDD9 },
 { 0x3389533D3C6878DD, (void*)NullNameFunc3389533D3C6878DD },
 { 0x3F96B7D8EBA56509, (void*)NullNameFunc3F96B7D8EBA56509 },
 { 0x94C92412FE1A6876, (void*)NullNameFunc94C92412FE1A6876 },
 { 0xBD73297BB32EADF7, (void*)NullNameFuncBD73297BB32EADF7 },
 { 0xC0A269161093AD7D, (void*)NullNameFuncC0A269161093AD7D },
 { 0xC192387E6509325C, (void*)NullNameFuncC192387E6509325C },
 { 0xFF9008114F7ED758, (void*)NullNameFuncFF9008114F7ED758 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutBaseMode4k_libSceVideoOut[] =
{
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutExtra_libSceVideoOut[] =
{
 { 0xF0B7F8169D53C40D, (void*)Pset_sceVideoOutAdjustColor2_ },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutRawEdid_libSceVideoOut[] =
{
 { 0xFAC5EF475247F40C, (void*)Pset_sceVideoOutGetHdmiRawEdid_ },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutHdr_libSceVideoOut[] =
{
 { 0x540962AF9DA0A502, (void*)Pset_sceVideoOutAddBufferHdrPrivilege },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceVideoOutWindow2Pre400_libSceVideoOut[] =
{
 { 0xDF1AD257C5341EC8, (void*)NullNameFuncDF1AD257C5341EC8 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceVideoOut[] =
{
 {"libSceDbgVideoOut", gSymTable_libSceDbgVideoOut_libSceVideoOut },
 {"libSceVideoOutAniso", gSymTable_libSceVideoOutAniso_libSceVideoOut },
 {"libSceDbgVideoOutSub4k", gSymTable_libSceDbgVideoOutSub4k_libSceVideoOut },
 {"libSceVideoOut", gSymTable_libSceVideoOut_libSceVideoOut },
 {"libSceVideoOutBaseMode4k", gSymTable_libSceVideoOutBaseMode4k_libSceVideoOut },
 {"libSceVideoOutExtra", gSymTable_libSceVideoOutExtra_libSceVideoOut },
 {"libSceVideoOutRawEdid", gSymTable_libSceVideoOutRawEdid_libSceVideoOut },
 {"libSceVideoOutHdr", gSymTable_libSceVideoOutHdr_libSceVideoOut },
 {"libSceVideoOutWindow2Pre400", gSymTable_libSceVideoOutWindow2Pre400_libSceVideoOut },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceVideoOut("libSceVideoOut", gLibTable_libSceVideoOut);