//Generated By SceModuleGenerator
#include "pset_libSceHttp.h"


int PSET_SYSV_ABI Pset_sceHttpAbortRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAbortRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAbortRequestForce(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAbortRequestForce");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAbortWaitRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAbortWaitRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAddCookie(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAddCookie");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAddQuery(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAddQuery");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAddRequestHeader(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAddRequestHeader");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAddRequestHeaderRaw(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAddRequestHeaderRaw");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAuthCacheExport(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAuthCacheExport");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAuthCacheFlush(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAuthCacheFlush");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpAuthCacheImport(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpAuthCacheImport");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCacheRedirectedConnectionEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCacheRedirectedConnectionEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCookieExport(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCookieExport");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCookieFlush(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCookieFlush");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCookieImport(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCookieImport");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateConnection(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateConnection");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateConnectionWithURL(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateConnectionWithURL");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateEpoll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateEpoll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateRequest2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateRequest2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateRequestWithURL(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateRequestWithURL");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateRequestWithURL2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateRequestWithURL2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpCreateTemplate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpCreateTemplate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgEnableProfile(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgEnableProfile");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgGetConnectionStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgGetConnectionStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgGetRequestStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgGetRequestStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgSetPrintf(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgSetPrintf");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgShowConnectionStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgShowConnectionStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgShowMemoryPoolStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgShowMemoryPoolStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgShowRequestStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgShowRequestStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDbgShowStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDbgShowStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDeleteConnection(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDeleteConnection");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDeleteRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDeleteRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDeleteTemplate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDeleteTemplate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpDestroyEpoll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpDestroyEpoll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetAcceptEncodingGZIPEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetAcceptEncodingGZIPEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetAllResponseHeaders(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetAllResponseHeaders");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetAuthEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetAuthEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetAutoRedirect(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetAutoRedirect");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetConnectionStat(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetConnectionStat");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetCookie(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetCookie");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetCookieEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetCookieEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetCookieStats(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetCookieStats");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetEpoll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetEpoll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetEpollId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetEpollId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetLastErrno(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetLastErrno");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetMemoryPoolStats(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetMemoryPoolStats");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetNonblock(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetNonblock");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetRegisteredCtxIds(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetRegisteredCtxIds");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetResponseContentLength(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetResponseContentLength");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpGetStatusCode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpGetStatusCode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpInit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpInit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpParseResponseHeader(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpParseResponseHeader");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpParseStatusLine(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpParseStatusLine");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpReadData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpReadData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpRedirectCacheFlush(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpRedirectCacheFlush");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpRemoveRequestHeader(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpRemoveRequestHeader");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpRequestGetAllHeaders(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpRequestGetAllHeaders");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsDisableOption(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsDisableOption");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsDisableOptionPrivate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsDisableOptionPrivate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsEnableOption(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsEnableOption");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsEnableOptionPrivate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsEnableOptionPrivate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSendRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSendRequest");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetAcceptEncodingGZIPEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetAcceptEncodingGZIPEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetAuthEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetAuthEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetAuthInfoCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetAuthInfoCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetAutoRedirect(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetAutoRedirect");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetChunkedTransferEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetChunkedTransferEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetConnectTimeOut(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetConnectTimeOut");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieMaxNum(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieMaxNum");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieMaxNumPerDomain(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieMaxNumPerDomain");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieMaxSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieMaxSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieRecvCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieRecvCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieSendCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieSendCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetCookieTotalMaxSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetCookieTotalMaxSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetDefaultAcceptEncodingGZIPEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetDefaultAcceptEncodingGZIPEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetDelayBuildRequestEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetDelayBuildRequestEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetEpoll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetEpoll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetEpollId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetEpollId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetHttp09Enabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetHttp09Enabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetInflateGZIPEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetInflateGZIPEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetNonblock(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetNonblock");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetPolicyOption(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetPolicyOption");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetPriorityOption(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetPriorityOption");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetProxy(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetProxy");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetRecvBlockSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetRecvBlockSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetRecvTimeOut(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetRecvTimeOut");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetRedirectCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetRedirectCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetRequestContentLength(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetRequestContentLength");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetRequestStatusCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetRequestStatusCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetResolveRetry(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetResolveRetry");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetResolveTimeOut(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetResolveTimeOut");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetResponseHeaderMaxSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetResponseHeaderMaxSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetSendTimeOut(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetSendTimeOut");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpSetSocketCreationCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpSetSocketCreationCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsFreeCaList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsFreeCaList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsGetCaList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsGetCaList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsGetSslError(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsGetSslError");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsLoadCert(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsLoadCert");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsSetMinSslVersion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsSetMinSslVersion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsSetSslCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsSetSslCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsSetSslVersion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsSetSslVersion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpsUnloadCert(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpsUnloadCert");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpTerm(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpTerm");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpTryGetNonblock(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpTryGetNonblock");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpTrySetNonblock(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpTrySetNonblock");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUnsetEpoll(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUnsetEpoll");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriBuild(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriBuild");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriCopy(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriCopy");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriEscape(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriEscape");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriMerge(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriMerge");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriParse(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriParse");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriSweepPath(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriSweepPath");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpUriUnescape(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpUriUnescape");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceHttpWaitRequest(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceHttpWaitRequest");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceHttp_libSceHttp[] =
{
 { 0x86F1BA19F04C5E0F, (void*)Pset_sceHttpAbortRequest },
 { 0x24A974E9920097A0, (void*)Pset_sceHttpAbortRequestForce },
 { 0xB16422A8ABD84D50, (void*)Pset_sceHttpAbortWaitRequest },
 { 0x98D6A7E904A7A5E6, (void*)Pset_sceHttpAddCookie },
 { 0x24CE7C6B6D66B6B4, (void*)Pset_sceHttpAddQuery },
 { 0x118DBC4F66E437B9, (void*)Pset_sceHttpAddRequestHeader },
 { 0x9460237ED6A7845B, (void*)Pset_sceHttpAddRequestHeaderRaw },
 { 0x6350C28CDFECD810, (void*)Pset_sceHttpAuthCacheExport },
 { 0xCF30744ADBD169BE, (void*)Pset_sceHttpAuthCacheFlush },
 { 0xC05D0A7312B6D011, (void*)Pset_sceHttpAuthCacheImport },
 { 0x03B9FD9CD83B3418, (void*)Pset_sceHttpCacheRedirectedConnectionEnabled },
 { 0x9CE91588BD7B64EA, (void*)Pset_sceHttpCookieExport },
 { 0xB1E0AF52DF755876, (void*)Pset_sceHttpCookieFlush },
 { 0xA459D70F1A376A88, (void*)Pset_sceHttpCookieImport },
 { 0x2A2C2FF6BE086427, (void*)Pset_sceHttpCreateConnection },
 { 0xAA0C43063A2B531B, (void*)Pset_sceHttpCreateConnectionWithURL },
 { 0xEB7F3575617EC6C4, (void*)Pset_sceHttpCreateEpoll },
 { 0xB6C195AEEDE109EF, (void*)Pset_sceHttpCreateRequest },
 { 0xAC6366F858C85CA9, (void*)Pset_sceHttpCreateRequest2 },
 { 0x01EBB9C152A417DC, (void*)Pset_sceHttpCreateRequestWithURL },
 { 0x0A7A7BEE9A1D9025, (void*)Pset_sceHttpCreateRequestWithURL2 },
 { 0xD206233D347FE9C6, (void*)Pset_sceHttpCreateTemplate },
 { 0x2DF7DCC5AA3F40C3, (void*)Pset_sceHttpDbgEnableProfile },
 { 0xEA0CB1FC8D0EA1BE, (void*)Pset_sceHttpDbgGetConnectionStat },
 { 0x7F3CC1A498E6F4AC, (void*)Pset_sceHttpDbgGetRequestStat },
 { 0x566A929E3679984E, (void*)Pset_sceHttpDbgSetPrintf },
 { 0x289B541EDA7ACB45, (void*)Pset_sceHttpDbgShowConnectionStat },
 { 0xA04B8FB2C498B240, (void*)Pset_sceHttpDbgShowMemoryPoolStat },
 { 0x2F680CDEAA6DA87B, (void*)Pset_sceHttpDbgShowRequestStat },
 { 0xA7106C0FF5FD787D, (void*)Pset_sceHttpDbgShowStat },
 { 0x3FA037CADA6C8987, (void*)Pset_sceHttpDeleteConnection },
 { 0xA9EEE867EBF83D60, (void*)Pset_sceHttpDeleteRequest },
 { 0xE08F2F129B84859F, (void*)Pset_sceHttpDeleteTemplate },
 { 0xC1885755F4B612DE, (void*)Pset_sceHttpDestroyEpoll },
 { 0xD6BA59AB174C4704, (void*)Pset_sceHttpGetAcceptEncodingGZIPEnabled },
 { 0x68260F31250868FF, (void*)Pset_sceHttpGetAllResponseHeaders },
 { 0xF66F0470E1B37084, (void*)Pset_sceHttpGetAuthEnabled },
 { 0x9A62DEC546ED9DF6, (void*)Pset_sceHttpGetAutoRedirect },
 { 0x2FF0F05681D72ED5, (void*)Pset_sceHttpGetConnectionStat },
 { 0xF86F94B09A5E5CF7, (void*)Pset_sceHttpGetCookie },
 { 0x8926635B0D531A20, (void*)Pset_sceHttpGetCookieEnabled },
 { 0xC64CA65A219D3222, (void*)Pset_sceHttpGetCookieStats },
 { 0xEE3F557309EB668E, (void*)Pset_sceHttpGetEpoll },
 { 0x21038FE8C71625C6, (void*)Pset_sceHttpGetEpollId },
 { 0xD289C8ACAC7D3481, (void*)Pset_sceHttpGetLastErrno },
 { 0xD7AB0C995B8EBE05, (void*)Pset_sceHttpGetMemoryPoolStats },
 { 0x5AAE11341DEC9D24, (void*)Pset_sceHttpGetNonblock },
 { 0x86471FA8097EF36C, (void*)Pset_sceHttpGetRegisteredCtxIds },
 { 0xCAE3B61F652F9E8B, (void*)Pset_sceHttpGetResponseContentLength },
 { 0xD1AD9304D7C4DC15, (void*)Pset_sceHttpGetStatusCode },
 { 0x03D715314B44A786, (void*)Pset_sceHttpInit },
 { 0x84F4D7A376C80B32, (void*)Pset_sceHttpParseResponseHeader },
 { 0x42AF127EE24926A1, (void*)Pset_sceHttpParseStatusLine },
 { 0x3F9A5DA3290F6139, (void*)Pset_sceHttpReadData },
 { 0xBB4E4D9C8F8FF8A6, (void*)Pset_sceHttpRedirectCacheFlush },
 { 0xCCD1A1FF3A104C3D, (void*)Pset_sceHttpRemoveRequestHeader },
 { 0xE1F8247D5795B065, (void*)Pset_sceHttpRequestGetAllHeaders },
 { 0x992402C73593C152, (void*)Pset_sceHttpsDisableOption },
 { 0xCC9622E5BAFA6624, (void*)Pset_sceHttpsDisableOptionPrivate },
 { 0x7F8D8ADFB9A6E513, (void*)Pset_sceHttpsEnableOption },
 { 0x238FB884AB6DB75C, (void*)Pset_sceHttpsEnableOptionPrivate },
 { 0xD5ED8137023F5F31, (void*)Pset_sceHttpSendRequest },
 { 0x1D15F58B20E8291F, (void*)Pset_sceHttpSetAcceptEncodingGZIPEnabled },
 { 0xA858364AEC932496, (void*)Pset_sceHttpSetAuthEnabled },
 { 0x8DFE130769D43B8D, (void*)Pset_sceHttpSetAuthInfoCallback },
 { 0x4FF986A3D7F73EEE, (void*)Pset_sceHttpSetAutoRedirect },
 { 0x3C3C52E3CC4640BB, (void*)Pset_sceHttpSetChunkedTransferEnabled },
 { 0xD12F6D4C7D2EA935, (void*)Pset_sceHttpSetConnectTimeOut },
 { 0x5CD5280F607D6BA0, (void*)Pset_sceHttpSetCookieEnabled },
 { 0xA4CFFFFA421E5BFF, (void*)Pset_sceHttpSetCookieMaxNum },
 { 0x2A9EA3B822542464, (void*)Pset_sceHttpSetCookieMaxNumPerDomain },
 { 0xED8E37EB8181ADAB, (void*)Pset_sceHttpSetCookieMaxSize },
 { 0x2A1E9B4B61D029BA, (void*)Pset_sceHttpSetCookieRecvCallback },
 { 0x1A7543CD87F2FCA2, (void*)Pset_sceHttpSetCookieSendCallback },
 { 0xA477376F15338AF5, (void*)Pset_sceHttpSetCookieTotalMaxSize },
 { 0xF24CC85EC472D5B6, (void*)Pset_sceHttpSetDefaultAcceptEncodingGZIPEnabled },
 { 0xDB66EE3BF52E7C96, (void*)Pset_sceHttpSetDelayBuildRequestEnabled },
 { 0xFF19BB91940DA472, (void*)Pset_sceHttpSetEpoll },
 { 0x2C6D585B5521920A, (void*)Pset_sceHttpSetEpollId },
 { 0xA64D00BA8990335A, (void*)Pset_sceHttpSetHttp09Enabled },
 { 0x8BD9A169FCE4122F, (void*)Pset_sceHttpSetInflateGZIPEnabled },
 { 0xB36FCD3C8BF3FA20, (void*)Pset_sceHttpSetNonblock },
 { 0x819F53A5E150EC69, (void*)Pset_sceHttpSetPolicyOption },
 { 0xD8D7999CC10FDFFD, (void*)Pset_sceHttpSetPriorityOption },
 { 0x8BEAAE09908BF83F, (void*)Pset_sceHttpSetProxy },
 { 0x98C701D97203A15E, (void*)Pset_sceHttpSetRecvBlockSize },
 { 0xCA282BE15D3F1D33, (void*)Pset_sceHttpSetRecvTimeOut },
 { 0x87DC261595F88BFE, (void*)Pset_sceHttpSetRedirectCallback },
 { 0x3D3885214C42A497, (void*)Pset_sceHttpSetRequestContentLength },
 { 0xBCEE01FF8D9E7FF9, (void*)Pset_sceHttpSetRequestStatusCallback },
 { 0x2B57752EA6514074, (void*)Pset_sceHttpSetResolveRetry },
 { 0x4DCFE10180CAB507, (void*)Pset_sceHttpSetResolveTimeOut },
 { 0x6B856C678A2A9FAF, (void*)Pset_sceHttpSetResponseHeaderMaxSize },
 { 0xC5E8057D9281565C, (void*)Pset_sceHttpSetSendTimeOut },
 { 0x3CE2746B31D95F7C, (void*)Pset_sceHttpSetSocketCreationCallback },
 { 0xED670DA0023D65CC, (void*)Pset_sceHttpsFreeCaList },
 { 0x81C523C14DDF6B43, (void*)Pset_sceHttpsGetCaList },
 { 0x24137A37F118FB73, (void*)Pset_sceHttpsGetSslError },
 { 0x0CAF86A1708D4F4E, (void*)Pset_sceHttpsLoadCert },
 { 0x8D48E9FB2A8C35D4, (void*)Pset_sceHttpsSetMinSslVersion },
 { 0x86DC813A859E4B9F, (void*)Pset_sceHttpsSetSslCallback },
 { 0x539131406CB2C7DB, (void*)Pset_sceHttpsSetSslVersion },
 { 0xCD7A9C1347E2CF3D, (void*)Pset_sceHttpsUnloadCert },
 { 0x224FCAA4B4E57FB4, (void*)Pset_sceHttpTerm },
 { 0x57F9E83C48D207C7, (void*)Pset_sceHttpTryGetNonblock },
 { 0x7E63ACE8CCC246A9, (void*)Pset_sceHttpTrySetNonblock },
 { 0xE7DB4BD404016FC5, (void*)Pset_sceHttpUnsetEpoll },
 { 0xE4B640F8A3C84950, (void*)Pset_sceHttpUriBuild },
 { 0x091FE5FF223FA3BA, (void*)Pset_sceHttpUriCopy },
 { 0x62E396DDD0C02987, (void*)Pset_sceHttpUriEscape },
 { 0xDE5810E50938DA89, (void*)Pset_sceHttpUriMerge },
 { 0x2166A5027FE0B85B, (void*)Pset_sceHttpUriParse },
 { 0x994537EB79F8C9CD, (void*)Pset_sceHttpUriSweepPath },
 { 0xB614D2FB9EF3A0B3, (void*)Pset_sceHttpUriUnescape },
 { 0xA884A30C7AF138D7, (void*)Pset_sceHttpWaitRequest },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceHttp[] =
{
 {"libSceHttp", gSymTable_libSceHttp_libSceHttp },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceHttp("libSceHttp", gLibTable_libSceHttp);