//Generated By SceModuleGenerator
#include "pset_libSceUserService.h"


int PSET_SYSV_ABI Pset_sceUserServiceInitializeForShellCore(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceInitializeForShellCore");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceTerminateForShellCore(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceTerminateForShellCore");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceDestroyUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceDestroyUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAccessibilityKeyremapData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAccessibilityKeyremapData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAccessibilityKeyremapEnable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAccessibilityKeyremapEnable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAccessibilityZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAccessibilityZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAccountRemarks(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAccountRemarks");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAgeVerified(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAgeVerified");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAppearOfflineSetting(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAppearOfflineSetting");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAppSortOrder(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAppSortOrder");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetAutoLoginEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetAutoLoginEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetCreatedVersion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetCreatedVersion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetCurrentUserGroupIndex(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetCurrentUserGroupIndex");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetDefaultNewUserGroupName(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetDefaultNewUserGroupName");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetDeletedUserInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetDeletedUserInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetDiscPlayerFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetDiscPlayerFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventCalendarType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventCalendarType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventFilterTeamEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventFilterTeamEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventSortEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventSortEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventUiFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventUiFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetEventVsh(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetEventVsh");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFaceRecognitionDeleteCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFaceRecognitionDeleteCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFaceRecognitionRegisterCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFaceRecognitionRegisterCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileBrowserFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileBrowserFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileBrowserSortContent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileBrowserSortContent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileBrowserSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileBrowserSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileSelectorFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileSelectorFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileSelectorSortContent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileSelectorSortContent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFileSelectorSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFileSelectorSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetForegroundUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetForegroundUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFriendCustomListLastFocus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFriendCustomListLastFocus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetFriendFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetFriendFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsAccessTokenNiconicoLive(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsAccessTokenNiconicoLive");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsAccessTokenTwitch(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsAccessTokenTwitch");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsAccessTokenUstream(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsAccessTokenUstream");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsAnonymousUserId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsAnonymousUserId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBcTags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBcTags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBcTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBcTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBroadcastChannel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBroadcastChannel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBroadcastersComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBroadcastersComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBroadcastersCommentColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBroadcastersCommentColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBroadcastService(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBroadcastService");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsBroadcastUiLayout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsBroadcastUiLayout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCamCrop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCamCrop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraBgFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraBgFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraChromaKeyLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraChromaKeyLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraContrast(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraContrast");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraDepthLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraDepthLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraEdgeLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraEdgeLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraEffect(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraEffect");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraEliminationLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraEliminationLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraPosition(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraPosition");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraReflection(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraReflection");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCameraTransparency(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCameraTransparency");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsCommunityId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsCommunityId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsFloatingMessage(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsFloatingMessage");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsHintFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsHintFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsInitSpectating(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsInitSpectating");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsCameraHidden(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsCameraHidden");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsFacebookEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsFacebookEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsMuteEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsMuteEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsRecDisabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsRecDisabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsRecievedMessageHidden(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsRecievedMessageHidden");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsIsTwitterEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsIsTwitterEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLanguageFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLanguageFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLfpsSortOrder(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLfpsSortOrder");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLiveQuality(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLiveQuality");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLiveQuality2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLiveQuality2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLiveQuality3(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLiveQuality3");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLiveQuality4(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLiveQuality4");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsLiveQuality5(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsLiveQuality5");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsMessageFilterLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsMessageFilterLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsTtsFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsTtsFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsTtsPitch(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsTtsPitch");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsTtsSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsTtsSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetGlsTtsVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetGlsTtsVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetHmuBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetHmuBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetHmuZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetHmuZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetHoldAudioOutDevice(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetHoldAudioOutDevice");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetHomeDirectory(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetHomeDirectory");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImeAutoCapitalEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImeAutoCapitalEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImeInitFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImeInitFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImeInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImeInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImeLastUnit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImeLastUnit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImePointerMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImePointerMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImePredictiveTextEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImePredictiveTextEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetImeRunCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetImeRunCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetInitialUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetInitialUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetIPDLeft(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetIPDLeft");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetIPDRight(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetIPDRight");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetIsFakePlus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetIsFakePlus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetIsQuickSignup(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetIsQuickSignup");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetIsRemotePlayAllowed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetIsRemotePlayAllowed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetJapaneseInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetJapaneseInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetKeyboardType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetKeyboardType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetKeyRepeatSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetKeyRepeatSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetKeyRepeatStartingTime(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetKeyRepeatStartingTime");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetKratosPrimaryUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetKratosPrimaryUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetLastLoginOrder(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetLastLoginOrder");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetLightBarBaseBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetLightBarBaseBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetLoginFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetLoginFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetLoginUserIdList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetLoginUserIdList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetMicLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetMicLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetMouseHandType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetMouseHandType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetMousePointerSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetMousePointerSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNotificationBehavior(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNotificationBehavior");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNotificationSettings(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNotificationSettings");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpAccountUpgradeFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpAccountUpgradeFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpAuthErrorFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpAuthErrorFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpEnv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpEnv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpLoginId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpLoginId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpOfflineAccountAdult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpOfflineAccountAdult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpOfflineAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpOfflineAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetNpSubAccount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetNpSubAccount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPadSpeakerVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPadSpeakerVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalBdAge(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalBdAge");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalBrowser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalBrowser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalDvd(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalDvd");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalDvdRegion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalDvdRegion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalGame(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalGame");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetParentalMorpheus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetParentalMorpheus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPartyMuteList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPartyMuteList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPartyMuteListA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPartyMuteListA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPartySettingFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPartySettingFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPasscode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPasscode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPlayTogetherFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPlayTogetherFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetPsnPasswordForDebug(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetPsnPasswordForDebug");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetRegisteredHomeUserIdList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetRegisteredHomeUserIdList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetRegisteredUserIdList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetRegisteredUserIdList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSaveDataAutoUpload(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSaveDataAutoUpload");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSaveDataSort(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSaveDataSort");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSaveDataTutorialFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSaveDataTutorialFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSecureHomeDirectory(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSecureHomeDirectory");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetShareButtonAssign(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetShareButtonAssign");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetShareDailymotionAccessToken(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetShareDailymotionAccessToken");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetShareDailymotionRefreshToken(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetShareDailymotionRefreshToken");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSharePlayFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSharePlayFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSharePlayFramerateHost(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSharePlayFramerateHost");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSharePlayResolutionHost(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSharePlayResolutionHost");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetShareStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetShareStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetShareStatus2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetShareStatus2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSystemLoggerHashedAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSystemLoggerHashedAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSystemLoggerHashedAccountIdClockType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSystemLoggerHashedAccountIdClockType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSystemLoggerHashedAccountIdParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSystemLoggerHashedAccountIdParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetSystemLoggerHashedAccountIdTtl(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetSystemLoggerHashedAccountIdTtl");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetTeamShowAboutTeam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetTeamShowAboutTeam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeBgImageDimmer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeBgImageDimmer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeBgImageWaveColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeBgImageWaveColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeBgImageZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeBgImageZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeEntitlementId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeEntitlementId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeHomeShareOwner(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeHomeShareOwner");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeTextShadow(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeTextShadow");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetThemeWaveColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetThemeWaveColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetTopMenuLimitItem(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetTopMenuLimitItem");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetTopMenuNotificationFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetTopMenuNotificationFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetTopMenuTutorialFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetTopMenuTutorialFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetTraditionalChineseInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetTraditionalChineseInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserGroupName(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserGroupName");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserGroupNameList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserGroupNameList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserGroupNum(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserGroupNum");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserName(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserName");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetUserStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetUserStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVibrationEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVibrationEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVoiceRecognitionTutorialState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVoiceRecognitionTutorialState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVolumeForController(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVolumeForController");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVolumeForGenericUSB(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVolumeForGenericUSB");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVolumeForMorpheusSidetone(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVolumeForMorpheusSidetone");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceGetVolumeForSidetone(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceGetVolumeForSidetone");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceInitialize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceInitialize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceInitialize2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceInitialize2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsGuestUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsGuestUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsKratosPrimaryUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsKratosPrimaryUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsKratosUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsKratosUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsLoggedIn(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsLoggedIn");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsLoggedInWithoutLock(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsLoggedInWithoutLock");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsSharePlayClientUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsSharePlayClientUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceIsUserStorageAccountBound(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceIsUserStorageAccountBound");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceLogin(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceLogin");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceLogout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceLogout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceRegisterEventCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceRegisterEventCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAccessibilityKeyremapData(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAccessibilityKeyremapData");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAccessibilityKeyremapEnable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAccessibilityKeyremapEnable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAccessibilityZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAccessibilityZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAccountRemarks(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAccountRemarks");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAgeVerified(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAgeVerified");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAppearOfflineSetting(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAppearOfflineSetting");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAppSortOrder(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAppSortOrder");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetAutoLoginEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetAutoLoginEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetCreatedVersion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetCreatedVersion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetDiscPlayerFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetDiscPlayerFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetEventCalendarType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetEventCalendarType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetEventFilterTeamEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetEventFilterTeamEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetEventSortEvent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetEventSortEvent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetEventSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetEventSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetEventUiFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetEventUiFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFaceRecognitionDeleteCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFaceRecognitionDeleteCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFaceRecognitionRegisterCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFaceRecognitionRegisterCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileBrowserFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileBrowserFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileBrowserSortContent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileBrowserSortContent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileBrowserSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileBrowserSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileSelectorFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileSelectorFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileSelectorSortContent(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileSelectorSortContent");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFileSelectorSortTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFileSelectorSortTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetForegroundUser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetForegroundUser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFriendCustomListLastFocus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFriendCustomListLastFocus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetFriendFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetFriendFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsAccessTokenNiconicoLive(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsAccessTokenNiconicoLive");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsAccessTokenTwitch(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsAccessTokenTwitch");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsAccessTokenUstream(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsAccessTokenUstream");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsAnonymousUserId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsAnonymousUserId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBcTags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBcTags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBcTitle(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBcTitle");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBroadcastChannel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBroadcastChannel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBroadcastersComment(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBroadcastersComment");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBroadcastersCommentColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBroadcastersCommentColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBroadcastService(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBroadcastService");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsBroadcastUiLayout(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsBroadcastUiLayout");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCamCrop(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCamCrop");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraBgFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraBgFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraChromaKeyLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraChromaKeyLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraContrast(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraContrast");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraDepthLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraDepthLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraEdgeLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraEdgeLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraEffect(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraEffect");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraEliminationLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraEliminationLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraPosition(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraPosition");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraReflection(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraReflection");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraSize(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraSize");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCameraTransparency(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCameraTransparency");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsCommunityId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsCommunityId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsFloatingMessage(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsFloatingMessage");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsHintFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsHintFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsInitSpectating(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsInitSpectating");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsCameraHidden(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsCameraHidden");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsFacebookEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsFacebookEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsMuteEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsMuteEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsRecDisabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsRecDisabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsRecievedMessageHidden(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsRecievedMessageHidden");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsIsTwitterEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsIsTwitterEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLanguageFilter(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLanguageFilter");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLfpsSortOrder(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLfpsSortOrder");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLiveQuality(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLiveQuality");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLiveQuality2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLiveQuality2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLiveQuality3(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLiveQuality3");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLiveQuality4(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLiveQuality4");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsLiveQuality5(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsLiveQuality5");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsMessageFilterLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsMessageFilterLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsTtsFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsTtsFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsTtsPitch(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsTtsPitch");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsTtsSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsTtsSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetGlsTtsVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetGlsTtsVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetHmuBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetHmuBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetHmuZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetHmuZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetHoldAudioOutDevice(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetHoldAudioOutDevice");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImeAutoCapitalEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImeAutoCapitalEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImeInitFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImeInitFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImeInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImeInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImeLastUnit(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImeLastUnit");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImePointerMode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImePointerMode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImePredictiveTextEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImePredictiveTextEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetImeRunCount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetImeRunCount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetIPDLeft(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetIPDLeft");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetIPDRight(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetIPDRight");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetIsFakePlus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetIsFakePlus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetIsQuickSignup(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetIsQuickSignup");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetIsRemotePlayAllowed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetIsRemotePlayAllowed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetJapaneseInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetJapaneseInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetKeyboardType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetKeyboardType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetKeyRepeatSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetKeyRepeatSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetKeyRepeatStartingTime(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetKeyRepeatStartingTime");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetLightBarBaseBrightness(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetLightBarBaseBrightness");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetLoginFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetLoginFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetMicLevel(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetMicLevel");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetMouseHandType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetMouseHandType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetMousePointerSpeed(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetMousePointerSpeed");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNotificationBehavior(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNotificationBehavior");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNotificationSettings(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNotificationSettings");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpAccountUpgradeFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpAccountUpgradeFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpAuthErrorFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpAuthErrorFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpEnv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpEnv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpLoginId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpLoginId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpOfflineAccountAdult(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpOfflineAccountAdult");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetNpSubAccount(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetNpSubAccount");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPadSpeakerVolume(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPadSpeakerVolume");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalBdAge(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalBdAge");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalBrowser(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalBrowser");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalDvd(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalDvd");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalDvdRegion(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalDvdRegion");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalGame(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalGame");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetParentalMorpheus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetParentalMorpheus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPartyMuteList(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPartyMuteList");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPartyMuteListA(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPartyMuteListA");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPartySettingFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPartySettingFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPasscode(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPasscode");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPlayTogetherFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPlayTogetherFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetPsnPasswordForDebug(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetPsnPasswordForDebug");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSaveDataAutoUpload(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSaveDataAutoUpload");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSaveDataSort(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSaveDataSort");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSaveDataTutorialFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSaveDataTutorialFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetShareButtonAssign(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetShareButtonAssign");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetShareDailymotionAccessToken(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetShareDailymotionAccessToken");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetShareDailymotionRefreshToken(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetShareDailymotionRefreshToken");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSharePlayFlags(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSharePlayFlags");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSharePlayFramerateHost(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSharePlayFramerateHost");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSharePlayResolutionHost(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSharePlayResolutionHost");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetShareStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetShareStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetShareStatus2(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetShareStatus2");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSystemLoggerHashedAccountId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSystemLoggerHashedAccountId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSystemLoggerHashedAccountIdClockType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSystemLoggerHashedAccountIdClockType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSystemLoggerHashedAccountIdParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSystemLoggerHashedAccountIdParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetSystemLoggerHashedAccountIdTtl(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetSystemLoggerHashedAccountIdTtl");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetTeamShowAboutTeam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetTeamShowAboutTeam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeBgImageDimmer(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeBgImageDimmer");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeBgImageWaveColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeBgImageWaveColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeBgImageZoom(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeBgImageZoom");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeEntitlementId(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeEntitlementId");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeHomeShareOwner(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeHomeShareOwner");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeTextShadow(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeTextShadow");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetThemeWaveColor(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetThemeWaveColor");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetTopMenuLimitItem(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetTopMenuLimitItem");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetTopMenuNotificationFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetTopMenuNotificationFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetTopMenuTutorialFlag(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetTopMenuTutorialFlag");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetTraditionalChineseInputType(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetTraditionalChineseInputType");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetUserGroupIndex(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetUserGroupIndex");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetUserGroupName(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetUserGroupName");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetUserName(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetUserName");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetUserStatus(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetUserStatus");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVibrationEnabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVibrationEnabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVoiceRecognitionTutorialState(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVoiceRecognitionTutorialState");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVolumeForController(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVolumeForController");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVolumeForGenericUSB(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVolumeForGenericUSB");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVolumeForMorpheusSidetone(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVolumeForMorpheusSidetone");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceSetVolumeForSidetone(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceSetVolumeForSidetone");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceTerminate(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceTerminate");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceUserServiceUnregisterEventCallback(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceUserServiceUnregisterEventCallback");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFunc8AC6DC4168D5FEA5(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFunc8AC6DC4168D5FEA5");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncA6BDC9DFDAFD02B4(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncA6BDC9DFDAFD02B4");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncBB9491DFE6B4953C(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncBB9491DFE6B4953C");
	return PSET_OK;
}

int PSET_SYSV_ABI NullNameFuncD2B814603E7B4477(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: NullNameFuncD2B814603E7B4477");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceUserServiceForShellCore_libSceUserService[] =
{
 { 0x3EC97D99FB3776E3, (void*)Pset_sceUserServiceInitializeForShellCore },
 { 0x0B274FF90B40D0A2, (void*)Pset_sceUserServiceTerminateForShellCore },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceUserService_libSceUserService[] =
{
 { 0x182D7CAF9E81A7B6, (void*)Pset_sceUserServiceDestroyUser },
 { 0x83AA23A96DDCF19E, (void*)Pset_sceUserServiceGetAccessibilityKeyremapData },
 { 0xC6BB648BDB14A298, (void*)Pset_sceUserServiceGetAccessibilityKeyremapEnable },
 { 0xD730C4154981768A, (void*)Pset_sceUserServiceGetAccessibilityZoom },
 { 0xEF3BB717BCA455EA, (void*)Pset_sceUserServiceGetAccountRemarks },
 { 0xA09CDF67165C857E, (void*)Pset_sceUserServiceGetAgeVerified },
 { 0xEABE210F2AD15068, (void*)Pset_sceUserServiceGetAppearOfflineSetting },
 { 0x3E15D96E3E305611, (void*)Pset_sceUserServiceGetAppSortOrder },
 { 0x9EA0C49E3ECCD101, (void*)Pset_sceUserServiceGetAutoLoginEnabled },
 { 0x5865CEBE8530ACEB, (void*)Pset_sceUserServiceGetCreatedVersion },
 { 0xE46FCC035C79BADC, (void*)Pset_sceUserServiceGetCurrentUserGroupIndex },
 { 0xD54E5C15D4DDB28D, (void*)Pset_sceUserServiceGetDefaultNewUserGroupName },
 { 0x3624C634B90173F4, (void*)Pset_sceUserServiceGetDeletedUserInfo },
 { 0x45DA669C767743D3, (void*)Pset_sceUserServiceGetDiscPlayerFlag },
 { 0xC87D7B43A356B558, (void*)Pset_sceUserServiceGetEvent },
 { 0xCECEB432F0A51247, (void*)Pset_sceUserServiceGetEventCalendarType },
 { 0x4F010B3E8A96F2D0, (void*)Pset_sceUserServiceGetEventFilterTeamEvent },
 { 0xCA056E6751DBFE77, (void*)Pset_sceUserServiceGetEventSortEvent },
 { 0x69A0B7D34E55B58E, (void*)Pset_sceUserServiceGetEventSortTitle },
 { 0x914689515D5BF8F3, (void*)Pset_sceUserServiceGetEventUiFlag },
 { 0xDF04ED677736FB40, (void*)Pset_sceUserServiceGetEventVsh },
 { 0xB915349507BEF716, (void*)Pset_sceUserServiceGetFaceRecognitionDeleteCount },
 { 0x7DB082D32A36A554, (void*)Pset_sceUserServiceGetFaceRecognitionRegisterCount },
 { 0x93FEE4C571ABFABD, (void*)Pset_sceUserServiceGetFileBrowserFilter },
 { 0x7C20693C96C42C39, (void*)Pset_sceUserServiceGetFileBrowserSortContent },
 { 0x51847D7DC3D70D41, (void*)Pset_sceUserServiceGetFileBrowserSortTitle },
 { 0x16C381CB725F6EB3, (void*)Pset_sceUserServiceGetFileSelectorFilter },
 { 0x20007BC2C70FC22A, (void*)Pset_sceUserServiceGetFileSelectorSortContent },
 { 0xE84B77778A75BBC7, (void*)Pset_sceUserServiceGetFileSelectorSortTitle },
 { 0x78D6F9DCB4099883, (void*)Pset_sceUserServiceGetForegroundUser },
 { 0x78C185EFB84A17A5, (void*)Pset_sceUserServiceGetFriendCustomListLastFocus },
 { 0xC011A6AD14D40B5E, (void*)Pset_sceUserServiceGetFriendFlag },
 { 0xEB83C45183EE2BDF, (void*)Pset_sceUserServiceGetGlsAccessTokenNiconicoLive },
 { 0xF18F9A0EF5462E2C, (void*)Pset_sceUserServiceGetGlsAccessTokenTwitch },
 { 0x57B646ED5F9D774F, (void*)Pset_sceUserServiceGetGlsAccessTokenUstream },
 { 0x42A675037BEE9053, (void*)Pset_sceUserServiceGetGlsAnonymousUserId },
 { 0x14FE132AB7515D73, (void*)Pset_sceUserServiceGetGlsBcTags },
 { 0xC97FD3A5B140631A, (void*)Pset_sceUserServiceGetGlsBcTitle },
 { 0x326E3E3D27E51DB3, (void*)Pset_sceUserServiceGetGlsBroadcastChannel },
 { 0x3691185433B28D19, (void*)Pset_sceUserServiceGetGlsBroadcastersComment },
 { 0x5AF336D49D522345, (void*)Pset_sceUserServiceGetGlsBroadcastersCommentColor },
 { 0x1F135188259F545C, (void*)Pset_sceUserServiceGetGlsBroadcastService },
 { 0xE9943891F84CDFB7, (void*)Pset_sceUserServiceGetGlsBroadcastUiLayout },
 { 0x626985884A1E824A, (void*)Pset_sceUserServiceGetGlsCamCrop },
 { 0x63953AEA79346D47, (void*)Pset_sceUserServiceGetGlsCameraBgFilter },
 { 0x2DB43F8D4F633AC9, (void*)Pset_sceUserServiceGetGlsCameraBrightness },
 { 0xF7590E2919E4AE11, (void*)Pset_sceUserServiceGetGlsCameraChromaKeyLevel },
 { 0xD69A731E442188DB, (void*)Pset_sceUserServiceGetGlsCameraContrast },
 { 0x8C87BC6440F4E972, (void*)Pset_sceUserServiceGetGlsCameraDepthLevel },
 { 0xD07E75105C51DE67, (void*)Pset_sceUserServiceGetGlsCameraEdgeLevel },
 { 0xACB130E27E72238D, (void*)Pset_sceUserServiceGetGlsCameraEffect },
 { 0xF8FADBC7989A825D, (void*)Pset_sceUserServiceGetGlsCameraEliminationLevel },
 { 0x174C2E12F8A841DE, (void*)Pset_sceUserServiceGetGlsCameraPosition },
 { 0x1A47078A589D4079, (void*)Pset_sceUserServiceGetGlsCameraReflection },
 { 0xCC12F15FC251328A, (void*)Pset_sceUserServiceGetGlsCameraSize },
 { 0x3B59D446CC726269, (void*)Pset_sceUserServiceGetGlsCameraTransparency },
 { 0xE1338415D98555C2, (void*)Pset_sceUserServiceGetGlsCommunityId },
 { 0xFB6F434A7759F4E7, (void*)Pset_sceUserServiceGetGlsFloatingMessage },
 { 0x922F35821D726433, (void*)Pset_sceUserServiceGetGlsHintFlag },
 { 0xCD1F89D8F3C98125, (void*)Pset_sceUserServiceGetGlsInitSpectating },
 { 0xF08A9DB4C99CE547, (void*)Pset_sceUserServiceGetGlsIsCameraHidden },
 { 0x7F9940569D2C14DA, (void*)Pset_sceUserServiceGetGlsIsFacebookEnabled },
 { 0x5B79DE15802F66CB, (void*)Pset_sceUserServiceGetGlsIsMuteEnabled },
 { 0xE085EE51A071CC48, (void*)Pset_sceUserServiceGetGlsIsRecDisabled },
 { 0x8725B9C3CE797E4E, (void*)Pset_sceUserServiceGetGlsIsRecievedMessageHidden },
 { 0x5E9F4FC74574B5AB, (void*)Pset_sceUserServiceGetGlsIsTwitterEnabled },
 { 0xB8C92A826EF4B618, (void*)Pset_sceUserServiceGetGlsLanguageFilter },
 { 0x2F25F30ADCE57804, (void*)Pset_sceUserServiceGetGlsLfpsSortOrder },
 { 0x0AFC02309B73A752, (void*)Pset_sceUserServiceGetGlsLiveQuality },
 { 0x67E77335A0A5ABBC, (void*)Pset_sceUserServiceGetGlsLiveQuality2 },
 { 0x5F93A7FFB8550ACD, (void*)Pset_sceUserServiceGetGlsLiveQuality3 },
 { 0xFAA004E2D44CAD79, (void*)Pset_sceUserServiceGetGlsLiveQuality4 },
 { 0xE32B34D02454E95F, (void*)Pset_sceUserServiceGetGlsLiveQuality5 },
 { 0xEF97309F5CB67DF9, (void*)Pset_sceUserServiceGetGlsMessageFilterLevel },
 { 0xF8D54931E212ACCE, (void*)Pset_sceUserServiceGetGlsTtsFlags },
 { 0x790AC16CC999D52B, (void*)Pset_sceUserServiceGetGlsTtsPitch },
 { 0x0420C0EA39F81D56, (void*)Pset_sceUserServiceGetGlsTtsSpeed },
 { 0x481BAB15893B33BE, (void*)Pset_sceUserServiceGetGlsTtsVolume },
 { 0x615CF0E13D5F9D2E, (void*)Pset_sceUserServiceGetHmuBrightness },
 { 0x3BC38D255DDBF238, (void*)Pset_sceUserServiceGetHmuZoom },
 { 0x5632E4298D0241EC, (void*)Pset_sceUserServiceGetHoldAudioOutDevice },
 { 0x27F284AF881412F4, (void*)Pset_sceUserServiceGetHomeDirectory },
 { 0xC8B366DE7EDF829C, (void*)Pset_sceUserServiceGetImeAutoCapitalEnabled },
 { 0x827562523D1A6FC5, (void*)Pset_sceUserServiceGetImeInitFlag },
 { 0xCEBBBC661BB2D546, (void*)Pset_sceUserServiceGetImeInputType },
 { 0xDBF6FC41B53E1CD7, (void*)Pset_sceUserServiceGetImeLastUnit },
 { 0x34D6E5A521B1AD8F, (void*)Pset_sceUserServiceGetImePointerMode },
 { 0x61484133F01211C0, (void*)Pset_sceUserServiceGetImePredictiveTextEnabled },
 { 0x2161256BF8B3C93B, (void*)Pset_sceUserServiceGetImeRunCount },
 { 0x09D5A9D281D61ABD, (void*)Pset_sceUserServiceGetInitialUser },
 { 0x3D0945E1C8D4CFD5, (void*)Pset_sceUserServiceGetIPDLeft },
 { 0x503C7AECF4F3076D, (void*)Pset_sceUserServiceGetIPDRight },
 { 0x20A9371068FEC512, (void*)Pset_sceUserServiceGetIsFakePlus },
 { 0x3335666EAD88542A, (void*)Pset_sceUserServiceGetIsQuickSignup },
 { 0x2E08B90387D0C077, (void*)Pset_sceUserServiceGetIsRemotePlayAllowed },
 { 0xBBF742544E9F4005, (void*)Pset_sceUserServiceGetJapaneseInputType },
 { 0x4DAE766D7C794DE9, (void*)Pset_sceUserServiceGetKeyboardType },
 { 0x5D44FB69DFC150C7, (void*)Pset_sceUserServiceGetKeyRepeatSpeed },
 { 0x896A735E2C43D141, (void*)Pset_sceUserServiceGetKeyRepeatStartingTime },
 { 0xB803C1C3FEFAE35B, (void*)Pset_sceUserServiceGetKratosPrimaryUser },
 { 0xE2751B18605C19CA, (void*)Pset_sceUserServiceGetLastLoginOrder },
 { 0xABEED44C610BCE3E, (void*)Pset_sceUserServiceGetLightBarBaseBrightness },
 { 0x40D93BA83E1D943E, (void*)Pset_sceUserServiceGetLoginFlag },
 { 0x7CF87298A36F2BF0, (void*)Pset_sceUserServiceGetLoginUserIdList },
 { 0x61F0E02B3E52A255, (void*)Pset_sceUserServiceGetMicLevel },
 { 0xB2E90F77FC410E33, (void*)Pset_sceUserServiceGetMouseHandType },
 { 0x639CE0C3AF677681, (void*)Pset_sceUserServiceGetMousePointerSpeed },
 { 0xDE8AA02053D5915F, (void*)Pset_sceUserServiceGetNotificationBehavior },
 { 0xE62AAD52BC88FE12, (void*)Pset_sceUserServiceGetNotificationSettings },
 { 0xE9D7C3ADEA2C5C66, (void*)Pset_sceUserServiceGetNpAccountId },
 { 0x55EA353DB419CC6E, (void*)Pset_sceUserServiceGetNpAccountUpgradeFlag },
 { 0x9E5396022472C640, (void*)Pset_sceUserServiceGetNpAuthErrorFlag },
 { 0xFD870D90BCCD1A66, (void*)Pset_sceUserServiceGetNpEnv },
 { 0x5B94603D4BAFDF96, (void*)Pset_sceUserServiceGetNpLoginId },
 { 0x6AE73AE1124072EB, (void*)Pset_sceUserServiceGetNpOfflineAccountAdult },
 { 0x7C4CB4116D00475F, (void*)Pset_sceUserServiceGetNpOfflineAccountId },
 { 0xC021A791786944BE, (void*)Pset_sceUserServiceGetNpSubAccount },
 { 0xCCDBC29C7A643E63, (void*)Pset_sceUserServiceGetPadSpeakerVolume },
 { 0x9572AD00732BC228, (void*)Pset_sceUserServiceGetParentalBdAge },
 { 0xB74E12E1A0B42C23, (void*)Pset_sceUserServiceGetParentalBrowser },
 { 0xE6FB45617149ECE5, (void*)Pset_sceUserServiceGetParentalDvd },
 { 0x77D0CE98893DFF2E, (void*)Pset_sceUserServiceGetParentalDvdRegion },
 { 0x39D8974AEA082BB7, (void*)Pset_sceUserServiceGetParentalGame },
 { 0xC97BDF47E01C81A6, (void*)Pset_sceUserServiceGetParentalMorpheus },
 { 0x51E22FE9A35794EC, (void*)Pset_sceUserServiceGetPartyMuteList },
 { 0x6AAD63C25832395E, (void*)Pset_sceUserServiceGetPartyMuteListA },
 { 0xC8046741E5B385D3, (void*)Pset_sceUserServiceGetPartySettingFlags },
 { 0x5F9AC964D0D9D92B, (void*)Pset_sceUserServiceGetPasscode },
 { 0xC80594AAE8233EF1, (void*)Pset_sceUserServiceGetPlayTogetherFlags },
 { 0x552411F6A6296823, (void*)Pset_sceUserServiceGetPsnPasswordForDebug },
 { 0x39575505C7A3BE64, (void*)Pset_sceUserServiceGetRegisteredHomeUserIdList },
 { 0xE448900A72F61B56, (void*)Pset_sceUserServiceGetRegisteredUserIdList },
 { 0x531AD2747EA30371, (void*)Pset_sceUserServiceGetSaveDataAutoUpload },
 { 0xA55B0428B9396C80, (void*)Pset_sceUserServiceGetSaveDataSort },
 { 0xF3CFA7A8137F4903, (void*)Pset_sceUserServiceGetSaveDataTutorialFlag },
 { 0xC7341505C298A08F, (void*)Pset_sceUserServiceGetSecureHomeDirectory },
 { 0xCEC25C5AD13CD519, (void*)Pset_sceUserServiceGetShareButtonAssign },
 { 0x36384ADFA19F1064, (void*)Pset_sceUserServiceGetShareDailymotionAccessToken },
 { 0xB7F2362DB8FC6BED, (void*)Pset_sceUserServiceGetShareDailymotionRefreshToken },
 { 0x96B3C5FE43413EBA, (void*)Pset_sceUserServiceGetSharePlayFlags },
 { 0x782F3C75BD62FDFF, (void*)Pset_sceUserServiceGetSharePlayFramerateHost },
 { 0xB6D892BE200F2D72, (void*)Pset_sceUserServiceGetSharePlayResolutionHost },
 { 0x6275CCDAC699925E, (void*)Pset_sceUserServiceGetShareStatus },
 { 0xC0CB521CB340563D, (void*)Pset_sceUserServiceGetShareStatus2 },
 { 0xF27A36AE50E397BA, (void*)Pset_sceUserServiceGetSystemLoggerHashedAccountId },
 { 0xBD6DAA58A62696FC, (void*)Pset_sceUserServiceGetSystemLoggerHashedAccountIdClockType },
 { 0x66BE21F816F1D1DA, (void*)Pset_sceUserServiceGetSystemLoggerHashedAccountIdParam },
 { 0x71FF4120CCB89AE6, (void*)Pset_sceUserServiceGetSystemLoggerHashedAccountIdTtl },
 { 0x0060CABA92E34D93, (void*)Pset_sceUserServiceGetTeamShowAboutTeam },
 { 0x11925E717F96BC97, (void*)Pset_sceUserServiceGetThemeBgImageDimmer },
 { 0x3CE55FBC20DC554C, (void*)Pset_sceUserServiceGetThemeBgImageWaveColor },
 { 0xA88D871B5A55F8E0, (void*)Pset_sceUserServiceGetThemeBgImageZoom },
 { 0xC7A9BC3FD0C13D27, (void*)Pset_sceUserServiceGetThemeEntitlementId },
 { 0x2BC361E9F8666247, (void*)Pset_sceUserServiceGetThemeHomeShareOwner },
 { 0x12010F5C389EE574, (void*)Pset_sceUserServiceGetThemeTextShadow },
 { 0x59A1D91A9D159F69, (void*)Pset_sceUserServiceGetThemeWaveColor },
 { 0x2310A90D8B224D7D, (void*)Pset_sceUserServiceGetTopMenuLimitItem },
 { 0x4B2905709106BF3E, (void*)Pset_sceUserServiceGetTopMenuNotificationFlag },
 { 0x306F8E6C60D878FC, (void*)Pset_sceUserServiceGetTopMenuTutorialFlag },
 { 0xA1754042EB6BDCDB, (void*)Pset_sceUserServiceGetTraditionalChineseInputType },
 { 0x954A2AC1342EE06A, (void*)Pset_sceUserServiceGetUserColor },
 { 0xD7E9F12786B02C7F, (void*)Pset_sceUserServiceGetUserGroupName },
 { 0x81ADB3DC0027F172, (void*)Pset_sceUserServiceGetUserGroupNameList },
 { 0xC7376126B2F71E7B, (void*)Pset_sceUserServiceGetUserGroupNum },
 { 0xD71C5C3221AED9FA, (void*)Pset_sceUserServiceGetUserName },
 { 0x4495FB4F8B233602, (void*)Pset_sceUserServiceGetUserStatus },
 { 0x3B49AD7E813909E9, (void*)Pset_sceUserServiceGetVibrationEnabled },
 { 0xFE34462EDD836DEE, (void*)Pset_sceUserServiceGetVoiceRecognitionTutorialState },
 { 0x95DDFDE972503E03, (void*)Pset_sceUserServiceGetVolumeForController },
 { 0x4C4B10D07589F11E, (void*)Pset_sceUserServiceGetVolumeForGenericUSB },
 { 0xAF642E1C84FCBBD2, (void*)Pset_sceUserServiceGetVolumeForMorpheusSidetone },
 { 0xDD46400CB057A620, (void*)Pset_sceUserServiceGetVolumeForSidetone },
 { 0x8F760CBB531534DA, (void*)Pset_sceUserServiceInitialize },
 { 0x6B3FF447A7AF899D, (void*)Pset_sceUserServiceInitialize2 },
 { 0x1675A42CD3A6257C, (void*)Pset_sceUserServiceIsGuestUser },
 { 0x98D9C1D8F58C4A0C, (void*)Pset_sceUserServiceIsKratosPrimaryUser },
 { 0xA592F5E782AF3235, (void*)Pset_sceUserServiceIsKratosUser },
 { 0x319C47F34DBDF968, (void*)Pset_sceUserServiceIsLoggedIn },
 { 0x85375C59C51472B9, (void*)Pset_sceUserServiceIsLoggedInWithoutLock },
 { 0xFFB5E00A61302ABB, (void*)Pset_sceUserServiceIsSharePlayClientUser },
 { 0x4CBAC382B3D84C3A, (void*)Pset_sceUserServiceIsUserStorageAccountBound },
 { 0xBAF551EF467116B4, (void*)Pset_sceUserServiceLogin },
 { 0xDD3F72E710DC7CE9, (void*)Pset_sceUserServiceLogout },
 { 0xC2E23B73B50D9340, (void*)Pset_sceUserServiceRegisterEventCallback },
 { 0x49F1957F210DF22C, (void*)Pset_sceUserServiceSetAccessibilityKeyremapData },
 { 0x64FD2D8B5091C4D0, (void*)Pset_sceUserServiceSetAccessibilityKeyremapEnable },
 { 0x1CABBAF1C57372D8, (void*)Pset_sceUserServiceSetAccessibilityZoom },
 { 0xBC2FEE4844C21546, (void*)Pset_sceUserServiceSetAccountRemarks },
 { 0x8012CC1A107A07D1, (void*)Pset_sceUserServiceSetAgeVerified },
 { 0xEC88947544691F49, (void*)Pset_sceUserServiceSetAppearOfflineSetting },
 { 0x6F9FED9CB7325101, (void*)Pset_sceUserServiceSetAppSortOrder },
 { 0xBBF13EE9DF4F88FF, (void*)Pset_sceUserServiceSetAutoLoginEnabled },
 { 0x7DEAA4B5B403D5EA, (void*)Pset_sceUserServiceSetCreatedVersion },
 { 0x9BC56D49DE48E688, (void*)Pset_sceUserServiceSetDiscPlayerFlag },
 { 0xC15DE396FB13E630, (void*)Pset_sceUserServiceSetEventCalendarType },
 { 0xADECFCD7DC15EC05, (void*)Pset_sceUserServiceSetEventFilterTeamEvent },
 { 0xBA1C2CB13B6DDF2A, (void*)Pset_sceUserServiceSetEventSortEvent },
 { 0x5C481D8467EA4692, (void*)Pset_sceUserServiceSetEventSortTitle },
 { 0x4F2F706A75430BD9, (void*)Pset_sceUserServiceSetEventUiFlag },
 { 0xB273B31F4350C8ED, (void*)Pset_sceUserServiceSetFaceRecognitionDeleteCount },
 { 0x8E230D620C734FFE, (void*)Pset_sceUserServiceSetFaceRecognitionRegisterCount },
 { 0x33D9E8397321946A, (void*)Pset_sceUserServiceSetFileBrowserFilter },
 { 0x5F2E2BABC8296075, (void*)Pset_sceUserServiceSetFileBrowserSortContent },
 { 0xC0DE7344BC3827A0, (void*)Pset_sceUserServiceSetFileBrowserSortTitle },
 { 0x84FDAAF446F985FD, (void*)Pset_sceUserServiceSetFileSelectorFilter },
 { 0x165E7625E48B3F2C, (void*)Pset_sceUserServiceSetFileSelectorSortContent },
 { 0x2E5BFAF77371FA75, (void*)Pset_sceUserServiceSetFileSelectorSortTitle },
 { 0x3200485D4906B691, (void*)Pset_sceUserServiceSetForegroundUser },
 { 0x7CAE0020CD249C54, (void*)Pset_sceUserServiceSetFriendCustomListLastFocus },
 { 0xE5C2BE502E783B3E, (void*)Pset_sceUserServiceSetFriendFlag },
 { 0x54450A42E988E41F, (void*)Pset_sceUserServiceSetGlsAccessTokenNiconicoLive },
 { 0xD03DB1B47418C482, (void*)Pset_sceUserServiceSetGlsAccessTokenTwitch },
 { 0xBDD05DDCF301169E, (void*)Pset_sceUserServiceSetGlsAccessTokenUstream },
 { 0x4DEADD4B1F855EB7, (void*)Pset_sceUserServiceSetGlsAnonymousUserId },
 { 0x51D6613759D561FC, (void*)Pset_sceUserServiceSetGlsBcTags },
 { 0x849E608FE3EFDFF3, (void*)Pset_sceUserServiceSetGlsBcTitle },
 { 0x3802DDE92985DB6D, (void*)Pset_sceUserServiceSetGlsBroadcastChannel },
 { 0x668A5DBCD9581477, (void*)Pset_sceUserServiceSetGlsBroadcastersComment },
 { 0x7F90C3217093C70C, (void*)Pset_sceUserServiceSetGlsBroadcastersCommentColor },
 { 0x2C804478D35F790A, (void*)Pset_sceUserServiceSetGlsBroadcastService },
 { 0x45D02F12692CFD91, (void*)Pset_sceUserServiceSetGlsBroadcastUiLayout },
 { 0x1D832013907AD906, (void*)Pset_sceUserServiceSetGlsCamCrop },
 { 0x37FC733B9FE58AF7, (void*)Pset_sceUserServiceSetGlsCameraBgFilter },
 { 0x1B1A8C600EB40482, (void*)Pset_sceUserServiceSetGlsCameraBrightness },
 { 0x0E2D399475A608B5, (void*)Pset_sceUserServiceSetGlsCameraChromaKeyLevel },
 { 0x8066EEDD36625DE5, (void*)Pset_sceUserServiceSetGlsCameraContrast },
 { 0xF0F5D021D46C6481, (void*)Pset_sceUserServiceSetGlsCameraDepthLevel },
 { 0xE7A6E5895FAD7346, (void*)Pset_sceUserServiceSetGlsCameraEdgeLevel },
 { 0x8218EB6F08C2D151, (void*)Pset_sceUserServiceSetGlsCameraEffect },
 { 0x627067669AF75098, (void*)Pset_sceUserServiceSetGlsCameraEliminationLevel },
 { 0xC166731FF0705AE0, (void*)Pset_sceUserServiceSetGlsCameraPosition },
 { 0xA671D1FDA8FD79DA, (void*)Pset_sceUserServiceSetGlsCameraReflection },
 { 0xAEB897312D1AEC13, (void*)Pset_sceUserServiceSetGlsCameraSize },
 { 0xD1ED30CC5003CB42, (void*)Pset_sceUserServiceSetGlsCameraTransparency },
 { 0xC100E2CDD3B8F420, (void*)Pset_sceUserServiceSetGlsCommunityId },
 { 0xB75A14D3EF776FEB, (void*)Pset_sceUserServiceSetGlsFloatingMessage },
 { 0x6DD25D5F66CAA361, (void*)Pset_sceUserServiceSetGlsHintFlag },
 { 0xBD182902128927E3, (void*)Pset_sceUserServiceSetGlsInitSpectating },
 { 0x123C44FBF56FB89E, (void*)Pset_sceUserServiceSetGlsIsCameraHidden },
 { 0x1DF41388C4821C99, (void*)Pset_sceUserServiceSetGlsIsFacebookEnabled },
 { 0xEB7B7AC343201BC2, (void*)Pset_sceUserServiceSetGlsIsMuteEnabled },
 { 0xEA86770D91B38C81, (void*)Pset_sceUserServiceSetGlsIsRecDisabled },
 { 0x026277149C53EEBF, (void*)Pset_sceUserServiceSetGlsIsRecievedMessageHidden },
 { 0x96C77105E46711EB, (void*)Pset_sceUserServiceSetGlsIsTwitterEnabled },
 { 0xC20540C1ADF59741, (void*)Pset_sceUserServiceSetGlsLanguageFilter },
 { 0xAC391F9691F3AD11, (void*)Pset_sceUserServiceSetGlsLfpsSortOrder },
 { 0xA93F3F78929EFAB2, (void*)Pset_sceUserServiceSetGlsLiveQuality },
 { 0x850EF633F6116FC8, (void*)Pset_sceUserServiceSetGlsLiveQuality2 },
 { 0x6560140B38124364, (void*)Pset_sceUserServiceSetGlsLiveQuality3 },
 { 0x1F01696AC1B8FA43, (void*)Pset_sceUserServiceSetGlsLiveQuality4 },
 { 0x3AFF21B3E73518D6, (void*)Pset_sceUserServiceSetGlsLiveQuality5 },
 { 0x7E6ED7A6C3BEFA59, (void*)Pset_sceUserServiceSetGlsMessageFilterLevel },
 { 0x2E07B8B3787C0450, (void*)Pset_sceUserServiceSetGlsTtsFlags },
 { 0x341F7F0FFA3784DD, (void*)Pset_sceUserServiceSetGlsTtsPitch },
 { 0xD8459F02BA14404E, (void*)Pset_sceUserServiceSetGlsTtsSpeed },
 { 0x433788417C9ABED5, (void*)Pset_sceUserServiceSetGlsTtsVolume },
 { 0x594E6CF9C3F33BC6, (void*)Pset_sceUserServiceSetHmuBrightness },
 { 0x81087C35A09B46AA, (void*)Pset_sceUserServiceSetHmuZoom },
 { 0xEE989FE51C928BEB, (void*)Pset_sceUserServiceSetHoldAudioOutDevice },
 { 0xF1319E2393C069B8, (void*)Pset_sceUserServiceSetImeAutoCapitalEnabled },
 { 0xDDF701A130029166, (void*)Pset_sceUserServiceSetImeInitFlag },
 { 0x1A1BB49210E0BAAF, (void*)Pset_sceUserServiceSetImeInputType },
 { 0x8639549FD5028178, (void*)Pset_sceUserServiceSetImeLastUnit },
 { 0xD7DB8217DEA67E8B, (void*)Pset_sceUserServiceSetImePointerMode },
 { 0x362C0C8426E0EFAE, (void*)Pset_sceUserServiceSetImePredictiveTextEnabled },
 { 0x0191575E964910F2, (void*)Pset_sceUserServiceSetImeRunCount },
 { 0x233CBEE17993041F, (void*)Pset_sceUserServiceSetIPDLeft },
 { 0xCFF95B0ABA6D781E, (void*)Pset_sceUserServiceSetIPDRight },
 { 0xED2138B238653822, (void*)Pset_sceUserServiceSetIsFakePlus },
 { 0x9CD9FC1A79FE13A6, (void*)Pset_sceUserServiceSetIsQuickSignup },
 { 0x010EBCD0BE12AFBE, (void*)Pset_sceUserServiceSetIsRemotePlayAllowed },
 { 0x9404759E4128301A, (void*)Pset_sceUserServiceSetJapaneseInputType },
 { 0x74276138920EB51E, (void*)Pset_sceUserServiceSetKeyboardType },
 { 0xCECE22F52107CB48, (void*)Pset_sceUserServiceSetKeyRepeatSpeed },
 { 0x15F5E03129992DF9, (void*)Pset_sceUserServiceSetKeyRepeatStartingTime },
 { 0x7650507E20CE9254, (void*)Pset_sceUserServiceSetLightBarBaseBrightness },
 { 0x65D7798326EDB22D, (void*)Pset_sceUserServiceSetLoginFlag },
 { 0x73D536A64E00A3DC, (void*)Pset_sceUserServiceSetMicLevel },
 { 0x960D88F1B113899A, (void*)Pset_sceUserServiceSetMouseHandType },
 { 0xA267FA044DBF14FA, (void*)Pset_sceUserServiceSetMousePointerSpeed },
 { 0xBA2B18516327FFE5, (void*)Pset_sceUserServiceSetNotificationBehavior },
 { 0x5FD260BABD10B4B1, (void*)Pset_sceUserServiceSetNotificationSettings },
 { 0x4A41394A70858D09, (void*)Pset_sceUserServiceSetNpAccountUpgradeFlag },
 { 0xA26E23C7EA49950A, (void*)Pset_sceUserServiceSetNpAuthErrorFlag },
 { 0x2627E77234E55D5F, (void*)Pset_sceUserServiceSetNpEnv },
 { 0x660AB5F6533EBB65, (void*)Pset_sceUserServiceSetNpLoginId },
 { 0x8FA160917871A756, (void*)Pset_sceUserServiceSetNpOfflineAccountAdult },
 { 0x9E0E1794D14C882A, (void*)Pset_sceUserServiceSetNpSubAccount },
 { 0xE3591CD988736685, (void*)Pset_sceUserServiceSetPadSpeakerVolume },
 { 0x289C3AADA85835D4, (void*)Pset_sceUserServiceSetParentalBdAge },
 { 0xEA33D80421908224, (void*)Pset_sceUserServiceSetParentalBrowser },
 { 0x513F3E95BE5FCA97, (void*)Pset_sceUserServiceSetParentalDvd },
 { 0x349A54BE8FAB7B38, (void*)Pset_sceUserServiceSetParentalDvdRegion },
 { 0x81123E0673C0E942, (void*)Pset_sceUserServiceSetParentalGame },
 { 0x9A6160CA35CC401B, (void*)Pset_sceUserServiceSetParentalMorpheus },
 { 0x66CC908EF5451E79, (void*)Pset_sceUserServiceSetPartyMuteList },
 { 0xF7B6645AE6ED324D, (void*)Pset_sceUserServiceSetPartyMuteListA },
 { 0x222C214729EB0E74, (void*)Pset_sceUserServiceSetPartySettingFlags },
 { 0xECB0AAE254A59B0E, (void*)Pset_sceUserServiceSetPasscode },
 { 0xA665B9BFD84E468B, (void*)Pset_sceUserServiceSetPlayTogetherFlags },
 { 0x9C27E16EDB996E4F, (void*)Pset_sceUserServiceSetPsnPasswordForDebug },
 { 0x92C50908BD07AB6D, (void*)Pset_sceUserServiceSetSaveDataAutoUpload },
 { 0xA5FCF8AF328973A8, (void*)Pset_sceUserServiceSetSaveDataSort },
 { 0xCEAE3949138A8FD4, (void*)Pset_sceUserServiceSetSaveDataTutorialFlag },
 { 0x6C5CC0DEDEA6BAF5, (void*)Pset_sceUserServiceSetShareButtonAssign },
 { 0x07F596EA636DA76B, (void*)Pset_sceUserServiceSetShareDailymotionAccessToken },
 { 0x380347E4FF655782, (void*)Pset_sceUserServiceSetShareDailymotionRefreshToken },
 { 0x08C97C99426F49FF, (void*)Pset_sceUserServiceSetSharePlayFlags },
 { 0xAC1EF42AEAAE631B, (void*)Pset_sceUserServiceSetSharePlayFramerateHost },
 { 0x06147147E4743450, (void*)Pset_sceUserServiceSetSharePlayResolutionHost },
 { 0x118BD1175554A545, (void*)Pset_sceUserServiceSetShareStatus },
 { 0x208F95EB05CA4BF1, (void*)Pset_sceUserServiceSetShareStatus2 },
 { 0xE632FB50CF8075B4, (void*)Pset_sceUserServiceSetSystemLoggerHashedAccountId },
 { 0xB4D658DED208A343, (void*)Pset_sceUserServiceSetSystemLoggerHashedAccountIdClockType },
 { 0x534ED7DFABE06C0D, (void*)Pset_sceUserServiceSetSystemLoggerHashedAccountIdParam },
 { 0xA9282CFF0C2B94B5, (void*)Pset_sceUserServiceSetSystemLoggerHashedAccountIdTtl },
 { 0x6FAF93CAD59C70F1, (void*)Pset_sceUserServiceSetTeamShowAboutTeam },
 { 0x259E4DCCDFD31884, (void*)Pset_sceUserServiceSetThemeBgImageDimmer },
 { 0x378AAB14B7172E96, (void*)Pset_sceUserServiceSetThemeBgImageWaveColor },
 { 0x6B8D66193A56BD8E, (void*)Pset_sceUserServiceSetThemeBgImageZoom },
 { 0x00BCA352ECA8C2E2, (void*)Pset_sceUserServiceSetThemeEntitlementId },
 { 0x8E1CBA7DAE5AE24E, (void*)Pset_sceUserServiceSetThemeHomeShareOwner },
 { 0x1E4B81B9885868F8, (void*)Pset_sceUserServiceSetThemeTextShadow },
 { 0x3CA1D92BDEB4A991, (void*)Pset_sceUserServiceSetThemeWaveColor },
 { 0x7FB5521D01C1E98B, (void*)Pset_sceUserServiceSetTopMenuLimitItem },
 { 0x4E26FCCE00DDF95D, (void*)Pset_sceUserServiceSetTopMenuNotificationFlag },
 { 0xF10EF58B7BBD94DD, (void*)Pset_sceUserServiceSetTopMenuTutorialFlag },
 { 0x65F528B94C7687CC, (void*)Pset_sceUserServiceSetTraditionalChineseInputType },
 { 0x21C3367F91284510, (void*)Pset_sceUserServiceSetUserGroupIndex },
 { 0x41F61AB1964FBE84, (void*)Pset_sceUserServiceSetUserGroupName },
 { 0x26ABB65C5AF952F0, (void*)Pset_sceUserServiceSetUserName },
 { 0x70182FF699E6BA72, (void*)Pset_sceUserServiceSetUserStatus },
 { 0x0A891687CA8600D9, (void*)Pset_sceUserServiceSetVibrationEnabled },
 { 0xD4935883045C00D2, (void*)Pset_sceUserServiceSetVoiceRecognitionTutorialState },
 { 0xE271238991F52CA3, (void*)Pset_sceUserServiceSetVolumeForController },
 { 0x6E443B68DC7AD908, (void*)Pset_sceUserServiceSetVolumeForGenericUSB },
 { 0xEC49E352D9C037EA, (void*)Pset_sceUserServiceSetVolumeForMorpheusSidetone },
 { 0x590FE5FE2DA0264A, (void*)Pset_sceUserServiceSetVolumeForSidetone },
 { 0x6F01634BE6D7F660, (void*)Pset_sceUserServiceTerminate },
 { 0xB295BFFF2A0B43DA, (void*)Pset_sceUserServiceUnregisterEventCallback },
 { 0x8AC6DC4168D5FEA5, (void*)NullNameFunc8AC6DC4168D5FEA5 },
 { 0xA6BDC9DFDAFD02B4, (void*)NullNameFuncA6BDC9DFDAFD02B4 },
 { 0xBB9491DFE6B4953C, (void*)NullNameFuncBB9491DFE6B4953C },
 { 0xD2B814603E7B4477, (void*)NullNameFuncD2B814603E7B4477 },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceUserServiceForNpToolkit_libSceUserService[] =
{
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceUserService[] =
{
 {"libSceUserServiceForShellCore", gSymTable_libSceUserServiceForShellCore_libSceUserService },
 {"libSceUserService", gSymTable_libSceUserService_libSceUserService },
 {"libSceUserServiceForNpToolkit", gSymTable_libSceUserServiceForNpToolkit_libSceUserService },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceUserService("libSceUserService", gLibTable_libSceUserService);