//Generated By SceModuleGenerator
#include "pset_libSceScreenShot.h"


int PSET_SYSV_ABI Pset__Z5dummyv(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset__Z5dummyv");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotCapture(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotCapture");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotDisable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotDisable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotDisableNotification(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotDisableNotification");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotEnable(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotEnable");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotEnableNotification(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotEnableNotification");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotGetAppInfo(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotGetAppInfo");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotGetDrcParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotGetDrcParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotIsDisabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotIsDisabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotIsVshScreenCaptureDisabled(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotIsVshScreenCaptureDisabled");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotSetOverlayImage(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotSetOverlayImage");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotSetOverlayImageWithOrigin(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotSetOverlayImageWithOrigin");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotSetParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotSetParam");
	return PSET_OK;
}

int PSET_SYSV_ABI Pset_sceScreenShotSetDrcParam(void)
{
	PSET_LOG_UNIMPLEMENTED("unimplemented function: Pset_sceScreenShotSetDrcParam");
	return PSET_OK;
}

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceScreenShot_libSceScreenShot[] =
{
 { 0x012E394286078DCE, (void*)Pset__Z5dummyv },
 { 0x26E30B2E69AF4609, (void*)Pset_sceScreenShotCapture },
 { 0xB4861FD16E554E2F, (void*)Pset_sceScreenShotDisable },
 { 0xCAC7F36BBD6B9BD3, (void*)Pset_sceScreenShotDisableNotification },
 { 0xDB1C54B6E0BF4731, (void*)Pset_sceScreenShotEnable },
 { 0x04351AAA555D4806, (void*)Pset_sceScreenShotEnableNotification },
 { 0x84D98AE127613D3D, (void*)Pset_sceScreenShotGetAppInfo },
 { 0x5650102205DAD91D, (void*)Pset_sceScreenShotGetDrcParam },
 { 0xFD257FA133461509, (void*)Pset_sceScreenShotIsDisabled },
 { 0x202349FF53CEB3CE, (void*)Pset_sceScreenShotIsVshScreenCaptureDisabled },
 { 0x6A11E139FF903644, (void*)Pset_sceScreenShotSetOverlayImage },
 { 0xEF7590E098F49C92, (void*)Pset_sceScreenShotSetOverlayImageWithOrigin },
 { 0x1BB2A59886052197, (void*)Pset_sceScreenShotSetParam },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_LIB_EXPORT_SYSMBOL gSymTable_libSceScreenShotDrc_libSceScreenShot[] =
{
 { 0x8AD9561565774F37, (void*)Pset_sceScreenShotSetDrcParam },
 SPSET_LIB_EXPORT_FUNTCTION_END
};

static const SPSET_EXPORT_LIB gLibTable_libSceScreenShot[] =
{
 {"libSceScreenShot", gSymTable_libSceScreenShot_libSceScreenShot },
 {"libSceScreenShotDrc", gSymTable_libSceScreenShotDrc_libSceScreenShot },
 SPSET_EXPORT_LIB_END
};

static const SPSET_EXPORT_MODULE gExportModule_libSceScreenShot("libSceScreenShot", gLibTable_libSceScreenShot);